### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by dprotaso** [JetBrains/spek#106]
http://jetbrains.github.io/spek/docs/

**Comment by mfenniak** [comment]
http://jetbrains.github.io/spek/docs/latest/ works, and it looks like the website has been updated to point to this "latest" subdir.

**Comment by raniejade** [comment]
Hey guys, we are still polishing the docs and the site. Hopefully by next week we have something to show. :)

**Comment by hhariri** [comment]
This is actually correct. We've moved to ASCIIDOC and it should point to /latest/. IS there an issue?

**Comment by mfenniak** [comment]
There was an issue a couple weeks ago, but it is fine right now.
