### ISSUE TITLE
Is there anything similar to JUnit Test Rule?

### ISSUE THREAD

**Issue by fabiocarballo** [JetBrains/spek#118]
Hello Guys,

I wanted to be able to do something with the behavior similar to the JUnit test rule. Is that possible?

My goal would be to something like:

``` 
beforeEach {
   RxJavaPlugins.getInstance().reset()
   RxJavaPlugins.getInstance().registerSchedulersHook(rxJavaSchedulersHook)}
}

afterEach {
  RxJavaPlugins.getInstance().reset()
}
```
But without the need to repeat this code in each single test and somehow contain this logic on a separate piece of code.

Thank you

**Comment by mfulton26** [comment]
I don't think Spek has anything specific for this but you can make your own custom group functions which applies "rules". e.g.:

```kotlin
inline fun Dsl.rxGroup(description: String, pending: Pending = Pending.No,
                       crossinline body: Dsl.() -> Unit) {
    group(description, pending) {
        beforeEach {
            RxJavaPlugins.getInstance().reset()
            RxJavaPlugins.getInstance().registerSchedulersHook(rxJavaSchedulersHook)}
        }
        body()
        afterEach {
            RxJavaPlugins.getInstance().reset()
        }
    }
}
```

**Comment by fabiocarballo** [comment]
Thought so! Awesome tip! 👍

**Comment by raniejade** [comment]
Another use case for #115  :)

**Comment by christopherperry** [comment]
How would you achieve the same functionality as `RuleChain`?
