### ISSUE TITLE
it tag doesn't admit single quotes in description

### ISSUE THREAD

**Issue by jdiazcano** [JetBrains/spek#134]
I tried to write single quotes in the `it` tag as description and that resulted in `Empty test suite.` It doesn't matter if you use expekt, hamkrest or any other, the `assert` is reached because you can debug it but it will never be taken part as a test

Working example:

```Kotlin
class SingleQuoteTest: Spek({

    describe("a simple test") {
        it("should not be b") {
            "b".should.be.equal("b")
        }
    }
})
```

Empty test suite example (notice the `shouldn't`):

```Kotlin
class SingleQuoteTest: Spek({

    describe("a simple test") {
        it("shouldn't be b") {
            "b".should.be.equal("b")
        }
    }
})
```

**Comment by raniejade** [comment]
Similar to https://github.com/raniejade/spek-idea-plugin/issues/18. Currently issue tracking for the idea plugin is a different repo. Going to release `v0.3.0` of the plugin anytime this week (just doing some testing). Fix is already at master, closing this issue.
