### ISSUE TITLE
Test Generation doesn't seem to work correctly

### ISSUE THREAD

**Issue by sazzer** [JetBrains/spek#135]
I'm trying to write some tests using Spek to cover a large range of input and expected output values. As such, I'm trying to generate the tests by having a single *performTest* method that takes the input values, and contains two *it* calls inside it.

Essentially what I have is:
```
fun performTest(input: Input, expectedOutput: Output) {
    // perform setup here
    // perform test here
    it("should do this") {
    }
    it("should do that") {
    }
}

describe("situation 1") {
    describe("input 1") {
        performTest(1, 2)
    }
    describe("input 2") {
        performTest(2, 4)
    }
}
describe("situation 2") {
    describe("input 1") {
        performTest(1, 2)
    }
    describe("input 2") {
        performTest(2, 4)
    }
}
```

Which seems reasonable. Unfortunately it doesn't work as expected. Instead of getting the tree of describe -> describe -> it, I only get a single *it* at the top level, and then because I have multiple of these at the same level with the same name, it doesn't run them all.

This is happening both in IntelliJ and in Maven, with the JUnit Platform runner set up for both.

**Comment by raniejade** [comment]
In your example`performTest` captures the toplevel scope, that's why your `it`s are on the topmost level. You `describe`s are also missing because Spek automatically prunes groups without any tests (`it`). What you want is:

```kotlin
fun Dsl.performTest(input: Input, expectedOutput: Output) {
    // perform setup here
    // perform test here
    it("should do this") {
    }
    it("should do that") {
    }
}
```

Making it an extension function, ensures that it will execute in the proper scope.
