### ISSUE TITLE
Report about exceptions occurred inside fixture or action body 

### ISSUE THREAD

**Issue by Adambl4** [JetBrains/spek#160]
```
object SpekTest : Spek({
    //throw RuntimeException() // execution failed, ok
    describe("1") {
        //throw RuntimeException() // execution failed, ok

        //beforeGroup { throw RuntimeException() } // empty test suite and green report, not ok
        //beforeEachTest { throw RuntimeException() } // empty test suite and green report, not ok

        on("2") {
            //throw RuntimeException() // empty test suite and green report, not ok
        }
    }
})
```

**Comment by raniejade** [comment]
Good catch, thanks!

**Comment by nickgieschen** [comment]
For what it's worth, you also get a green report if an exception is thrown inside the "on" and execution never gets to the "it".

**Comment by raniejade** [comment]
Error reporting works on gradle, this a problem with the plugin. It's using the built-in `SMTestTreeView` which uses `service messages`. Unfortunately it doesn't support container failures, so I'll have to take a look on what we can use.

I'm closing this issue in favor of https://github.com/raniejade/spek-idea-plugin/issues/29.
