### ISSUE TITLE
Cant find spek-junit-platform-engine:1.1.0-beta3

### ISSUE THREAD

**Issue by caipivara** [JetBrains/spek#163]
I cant find `org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3`.

Last release was `1.1.0-beta3` and it exists for `org.jetbrains.spek:spek-api` but not for the engine.

**Comment by raniejade** [comment]
Are you using gradle? You have to add:

```gradle
repositories {
    maven { url "http://dl.bintray.com/jetbrains/spek" }
}
```
