### ISSUE TITLE
Allow abstract base classes for speks

### ISSUE THREAD

**Issue by pdvrieze** [JetBrains/spek#166]
While subjectspek is helpful, when testing more complex systems where testing needs a number of helper objects it is very useful to define an abstract base class similar to subjectspek. Unfortunately the class scanner happily resolves these classes and lets JUnit then complain about the fact that they can't be instantiated.

It would be worthwhile for the general all tests in package scanning to skip abstract classes and maybe also classes that don't have a default constructor (in some cases there is not really a sane default subject to specify, you just want to share code).

**Comment by raniejade** [comment]
Good catch, abstract classes should be skipped (in fact the plugin doesn't mark them as runnable). Trying to understand why you have non-abstract spek classes with no default constructor, can you give me an example?

**Comment by pdvrieze** [comment]
At some point I attempted marking one of the classes abstract but that didn't seem to help. In this case however I basically have a test I need to repeat 3 times for 3 combinations of boolean parameters (false, false is not valid). The input data is constructed (slightly) differently for each of them, but the bulk of the test is identical. I know that this could possibly be done using a function instead, but my testing requires setup code that is more than 2 lines of code that I absolutely don't want to repeat for each and every test (so the correct values are available within the test).

Btw. I wrote a small hack function + object `includelocal` that actually allows for local inclusion of a spec by having the object override `Spec`, delegate what it can to the local `SpecBody` and passing the rest to the parent `Spec`

**Comment by raniejade** [comment]
> At some point I attempted marking one of the classes abstract but that didn't seem to help. In this case however I basically have a test I need to repeat 3 times for 3 combinations of boolean parameters (false, false is not valid). The input data is constructed (slightly) differently for each of them, but the bulk of the test is identical. I know that this could possibly be done using a function instead, but my testing requires setup code that is more than 2 lines of code that I absolutely don't want to repeat for each and every test (so the correct values are available within the test).
>
> Btw. I wrote a small hack function + object includelocal that actually allows for local inclusion of a spec by having the object override Spec, delegate what it can to the local SpecBody and passing the rest to the parent Spec

Sounds like a data-driven test (see #146)?  I was previously thinking of supporting parameterizing speks:

```kotlin
object MySpec: Spek({
   val param by param("param_name", "default_value")
})
``` 

But didn't pursue it due to lack of use case.
