### ISSUE TITLE
Make the default factory a little more lenient

### ISSUE THREAD

**Issue by pdvrieze** [JetBrains/spek#171]
Currently the default factory (in SpekTestEngine) assumes that the spek has a primary constructor that is a no-arg constructor. This can be replaced by: `spek.objectInstance ?: spek.constructors.first { it.parameters.isEmpty }.call()` to allow for secondary constructors.

My use case is that I want to be able to use the case standalone and included in another spek. When included I want to reduce the amount of test cases it generates (by default 6327 tests - mostly on different data) such as to reduce test time (btw. it seems that test execution has quite a number of bottlenecks).

**Comment by raniejade** [comment]
> Currently the default factory (in SpekTestEngine) assumes that the spek has a primary constructor that is a no-arg constructor. This can be replaced by: spek.objectInstance ?: spek.constructors.first { it.parameters.isEmpty }.call() to allow for secondary constructors.
> 

:+1: 

> My use case is that I want to be able to use the case standalone and included in another spek. When included I want to reduce the amount of test cases it generates (by default 6327 tests - mostly on different data) such as to reduce test time (btw. it seems that test execution has quite a number of bottlenecks).

Would be nice if you could describe those bottlenecks in another ticket? :)
