### ISSUE TITLE
exception in action results in green test

### ISSUE THREAD

**Issue by robstoll** [JetBrains/spek#176]
The error can be reproduced by the following code:

```kotlin
describe("error sceenario"){
    on("exception thrown in action block"){
        throw IllegalArgumentException("oh no...")
        test("on should be red not green"){}
    }
}
```
The `on` should not be green (I am using intellij) but red and an exception should be shown.

**Comment by robstoll** [comment]
Hm... I realised that it also happens if one of the test fail. Am I using `on` wrong?

**Comment by raniejade** [comment]
@robstoll It's a limitation of the plugin, unfortunately (https://github.com/raniejade/spek-idea-plugin/issues/29). If you're using gradle everything should work as expected. I'm looking into ways to fixing this, but it might take a while.

**Comment by robstoll** [comment]
@raniejade you are right, it works fine in gradle, at least my first concern (described in the issue). However, my second concern (described in my comment) still holds. If an unexpected exception occurs in a group scope then none of the tests are executed. Is this intentional?

**Comment by raniejade** [comment]
@robstoll No, it's not. Re-opening the ticket, it should still continue and just ignore the failing group.

**Comment by robstoll** [comment]
Awesome, when is your next release planned?
