### ISSUE TITLE
Problem with subjects (memoized) and fixtures

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#178]
One thing I noticed when using subjects and fixtures (`after` variants specifically), is that the subject is *cleared* when the fixture is invoked.

```kotlin
class SimpleSpec: SubjectSpek<World<GameState>>({
    val initialStateHandler = memoized { InitialStateHandler() }
    val movementSystem = memoized { MovementSystem() }
    subject {
        createWorld<GameState> {
            initialState(GameState.Initial)
            registerStateHandler(GameState.Initial, initialStateHandler())
            registerSystem(movementSystem())
        }
    }

    beforeGroup {
        subject.setup()
    }

    afterGroup {
        // subject instance is new
        subject.cleanup()
    }

    on("update") {
        subject.update(5.0)


        it("there should be no entities in the origin") {
            with(initialStateHandler()) {
                entities.forEach {
                    expect(positionComponentMapper.get(it)).satisfy {
                        it!!.x != 0.0f && it.y != 0.0f && it.z != 0.0f
                    }
                }
            }
        }
    }
})

```

By the time `afterGroup` is invoked the subject has been cleared, so  using `subject` will return a new instance. Depending on the subject, it can cause a variety of problems. In my case an `NPE` is thrown since `setup` was not invoked.

There are 2 solutions:
1. Since fixtures and memoized (subjects are built on top of this) register a `LifecycleListener` to do their bidding (see FixturesAdapter and LifecycleAwareAdapter), we could just ensure that fixtures are always executed last.

2. The reason I used `afterGroup` was to do some cleanup for my subject, so we could support a "cleanup" callback for memoized (subject). This will be invoked when a subject is being cleared. This can also used when implementing `resource`, `Closeable#close` will be invoked in that callback (see #101).

    ```kotlin
       val myResource by resource(...)
    ```

**Comment by raniejade** [comment]
@artem-zinnatullin @hhariri would love to get your inputs.

**Comment by hhariri** [comment]
Probably two is more clear and flexible, unless I'm missing something.

**Comment by artem-zinnatullin** [comment]
`2` adds more entities to the framework which is not a great thing from design standpoint… Also `1` looks simpler both from usage and concept points of view.

@raniejade do you see any pitfalls of solution `1`?

**Comment by raniejade** [comment]
I prefer `1` for simplicity, my concern with `2` is how the DSL would look. One advantage of `1` is we have explicit control on when to do the cleanup.

**Comment by artem-zinnatullin** [comment]
Great! Let's stick to 1 then?

**Comment by hhariri** [comment]
ok. No objections from me.
