### ISSUE TITLE
Rework UniqueId generation for the JUnit Platform TestEngine

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#179]
Currently `UniqueId`s are based from the description passed to group/test and its direct parent. 

```kotlin
package some.example

object MySpec: Spek({
    group("some group") {
        test("some test") {
        }
    }
})
```
We have 3 scopes here and below are their `UniqueId`s:
1. `object MySpec` -> `[class:some.example.MySpec]`
2. `group("some group")` -> `[class:some.example.MySpec]/[group:some group]`
3. `test("some test")` -> `[class:some.example.MySpec]/[group:some group]/[test:some test]`

The [IDEA plugin](https://github.com/raniejade/spek-idea-plugin) relies on this to tell the engine which tests to run. Everything is good until you use string interpolation on the description. The plugin analyzes the source code to produce a valid `UniqueId`, however with string interpolation the description is only known at runtime. 

```kotlin
object MySpec: Spek({
    val number = 1
    it("should be something") {

    }

    it("should be $number") {

    }
})
```

Using the plugin, if you try running the single test `"should be $number"` it will just run the whole spec. Using the description as the basis of the `UniqueId` is inherently problematic.  It can cause problems when you start using reserved characters (`[`, `]`, `:`, and `/`).

One solution would be to use numbers instead of the description (except for `UniqueId` for the class). Using the previous example, the `UniqueIds` will now be:

1. `object MySpec` -> `[class:some.example.MySpec]`
2. `group("some group")` -> `[class:some.example.MySpec]/[group:1]`
3. `test("some test")` -> `[class:some.example.MySpec]/[group:1]/[test:1]`

This will be a breaking change with regards to the plugin, so we have to sync the releases.

**Comment by raniejade** [comment]
> One solution would be to use numbers instead of the description (except for UniqueId for the class). Using the previous example, the UniqueIds will now be:
> 
> 1. object MySpec -> [class:some.example.MySpec]
> 2. group("some group") -> [class:some.example.MySpec]/[group:1]
> 3. test("some test") -> [class:some.example.MySpec]/[group:1]/[test:1]

Disregard this, it's also problematic when you try to use extension functions that register any number of scopes.

**Comment by artem-zinnatullin** [comment]
Yeah, we actually use extension functions on `DescribeBody/Dsl/SpecBody` that accept extension on themself pretty often to apply some common tests in different parts of Spec tree… Not a fan of that, but also not a hater.

But I think we're ok with running such tests only as part of the sub-tree we're applying them on. 

Another solution would be to parse **compiled** Specs, so if extension function has `inline` modifier on it, Plugin could actually suggest to run tests that were added by extension function, but that sounds overcomplicated.

**Comment by raniejade** [comment]
Fixed in `2.x`.
