### ISSUE TITLE
Does not support nested actions

### ISSUE THREAD

**Issue by dalewking** [JetBrains/spek#189]
I want to run a test where I take my subject, perform an action, do some asserts, then take another action and verify some more asserts. The thing I am trying to test for requires doing both actions.

So I tried to structure a subject spec like this:

    given("my object")
    {
        subject { createObject() }

        on("performing first action")
        {
            subject.performFirstAction()

            it("should have performed the first action") { /* assertions */ }

            on("performing second action")
            {
                subject.performSecondAction()

                it("should have performed the first action") { /* assertions */ }
            }
        }
    }

But the inner on block is ignored and does nothing. Can you not nest action blocks like this? If not what is the better way to structure this. If I have to combine them into one action then it means I have to duplicate the tests for just doing the first action

**Comment by raniejade** [comment]
With https://github.com/JetBrains/spek/pull/186, it's possible to do:

```kotlin
given("my object")
{
    subject(CachingMode.SCOPE) { createObject() }

    on("performing first action")
    {
        subject.performFirstAction()

        it("should have performed the first action") { /* assertions */ }
    }

    on("performing second action")
    {
        subject.performSecondAction()
        it("should have performed the first action") { /* assertions */ }
    }
}
```

**Comment by dalewking** [comment]
I accept your answer and closing as hopefully 186 will be released soon. Until then will use jitpack.io to pull it in.
