### ISSUE TITLE
data driven extensions not fully working on android

### ISSUE THREAD

**Issue by xklakoux** [JetBrains/spek#194]
Hi, I'm using kotlin 1.0.3 with spek 1.1 and data-driven-extensions on android. 
I'm forced to use @RunWith(JUnitPlatform::class) annotation.

Data driven extensions test behave like on the picture. This state doesn't advance.
![calculatortest](https://cloud.githubusercontent.com/assets/1180857/24393658/3009c570-1399-11e7-9684-b08a306bf957.png)
Although all duplicated tests pass, proper tests hang indefinitely.

I suspect the android would be the troublemaker here. Is there anything that can be done with that?

**Comment by raniejade** [comment]
Btw, are you using `@RunWith(JUnitPlatform::class)`?

**Comment by raniejade** [comment]
> I'm forced to use @RunWith(JUnitPlatform::class) annotation.

Out of curiosity, why?

**Comment by xklakoux** [comment]
My tests aren't detected on android if I don't.

**Comment by raniejade** [comment]
Do you have the [Spek plugin](https://plugins.jetbrains.com/plugin/8564-spek) installed?

**Comment by xklakoux** [comment]
I indeed didn't have it installed. After I did all the test fail because of 
`java.lang.RuntimeException: Stub!` I'm looking on how to resolve that. Could be something about junit5 not being used?

**Comment by raniejade** [comment]
http://robolectric.org/ unfortunately we don't provide support for it yet #65.

**Comment by xklakoux** [comment]
We don't use robolectric, this was caused by old test configurations. I had to remove them for this to work. Also I had to downgrade mockito 1.9.5 to 1.9.0 or upgrade to mockito 2 for spek to work with the plugin because of dexmaker error. 
However, data driven extension is working fine with the plugin, my bad, this issue can be closed. Thanks for helping me.
