### ISSUE TITLE
How can I use `lateinit` with Spek?

### ISSUE THREAD

**Issue by lalunamel** [JetBrains/spek#202]
It would seem `lateinit` is designed with testing in mind, as [the example](https://kotlinlang.org/docs/reference/properties.html#late-initialized-properties) in the docs illustrates.

How can I use `lateinit` with Spek?

Given a spec file

```
       var ints: List<Int>

        beforeEachTest {
            ints = listOf(1)
        }

        it("does something") {
            assertEquals(1, ints.first())
        }
```

The call `ints.first()` will not compile with the error `Variable 'ints' must be initialized`

Seems like a perfect use for `lateinit`, since I as the developer know that `ints` will be initialized!

Modifying `var ints: List<Int>` to include `lateinit` produces the compilation error `Modifier 'lateinit' is not applicable to 'local variable'`

I'd like to use `lateinit`. What am I missing?

**Comment by raniejade** [comment]
`lateinit` does not work for local variables, you could use `memoized`.

```kotlin
var ints by memoized { listOf(1) }

it("does something") {
    assertEquals(1, ints.first())
}
```

If you're familiar with `subjects`, `memoized` also accepts a `CachingMode` which controls how spek will cache the instances.
