### ISSUE TITLE
`it` not in `group` in reporting

### ISSUE THREAD

**Issue by robstoll** [JetBrains/spek#203]
The problem can be reproduced with the following sample:
```kotlin
object Test : Spek({
    fun test(){
        it("should be in group when it succeeds"){}
        it("should be in group when it fails"){
            throw IllegalArgumentException()
        }
    }
    fun SpecBody.test2(){
        it("is in group when it succeeds"){}
        it("is in group when it fails"){
            throw IllegalArgumentException()
        }
    }
    describe("a group having `it`s which are created in functions"){
        test()
        test2()
    }
})
```

Executing the Spek in intellij shows the `it` of test2 under the `group` whereas the `it` of test are shown separately (not within the group).

**Comment by raniejade** [comment]
The `it` under `test()` refers to the top-most scope (`Spek({ ... })`), while the `it` under `SpecBody.test2()` refers to scope where it's used - in your example: ` describe("a group having `it`s which are created in functions")`. 

When `test` to is created it "captured" the scope (keeps a reference) it was declared. So when using `it` within it, it will use the said scope.
