### ISSUE TITLE
Question: What does this message mean: Run Configuration is currently not installed?

### ISSUE THREAD

**Issue by CreamyCookie** [JetBrains/spek#230]
In 2017.02 I'm getting this message on startup: "Plugin supporting feature (Run Configuration[spek-run-configuration]) is currently not installed."

I can't find a plugin that is named "spek-run-configuration".

**Comment by raniejade** [comment]
Can you reinstall the [Spek](https://plugins.jetbrains.com/plugin/8564-spek) plugin? If you have some old run configurations please delete it.

**Comment by CreamyCookie** [comment]
@raniejade  I did. There was a link "Ignore run configurations" or so, next to the above, which I think alread deleted the run configurations when I pressed it. 

And the message doesn't pop up anymore.. Should I close this or keep it open regarding the IMO confusing error message?

**Comment by raniejade** [comment]
I'll close it for now and just reopen when necessary.
