### ISSUE TITLE
Tests Ok from Gradle CLI, fails in IDE

### ISSUE THREAD

**Issue by davidsowerby** [JetBrains/spek#231]
I am getting the following error in IDEA, yet fails in the iDE with:

> Testing started at 09:34 ...
> Aug 02, 2017 9:34:23 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
> INFO: Discovered TestEngines with IDs: [spek]
> Exception in thread "main" java.lang.AbstractMethodError: Method org/jetbrains/spek/engine/Scope$Group.isTest()Z is abstract
> 	at org.jetbrains.spek.engine.Scope$Group.isTest(Scope.kt)
> 	at org.junit.platform.engine.TestDescriptor.hasTests(TestDescriptor.java:160)
> 	at org.junit.platform.launcher.core.Root.lambda$static$0(Root.java:33)
> 	at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:179)
> 	at org.junit.platform.engine.TestDescriptor.lambda$accept$0(TestDescriptor.java:181)
> 	at java.lang.Iterable.forEach(Iterable.java:75)
> 	at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:181)
> 	at org.junit.platform.launcher.core.Root.lambda$acceptInAllTestEngines$2(Root.java:85)
> 	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
> 	at org.junit.platform.launcher.core.Root.acceptInAllTestEngines(Root.java:85)
> 	at org.junit.platform.launcher.core.Root.prune(Root.java:77)
> 	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
> 	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
> 	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
> 
> Process finished with exit code 1

Relevant parts of build.gradle:

> buildscript {
>     ext.kotlin_version = '1.1.3-2'
> 
>     repositories {
>         mavenLocal()
>         jcenter()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4'
>     }
> }
> 
> apply plugin: 'kotlin'
> apply plugin: 'org.junit.platform.gradle.plugin'
> 
> junitPlatform {
>     filters {
>         engines {
>             include 'spek'
>         }
>     }
> }
> 
> repositories {
>     mavenLocal()
>     jcenter()
>     mavenCentral()
> }
> 
> version ='0.0.0.1'
> 
> dependencies {
>     compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
>     compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
> 
>     testCompile ('org.jetbrains.spek:spek-api:1.1.2') {
>         exclude group: 'org.jetbrains.kotlin'
>     }
>     testRuntime ('org.jetbrains.spek:spek-junit-platform-engine:1.1.2') {
>         exclude group: 'org.junit.platform'
>         exclude group: 'org.jetbrains.kotlin'
>     }
> }

**Comment by raniejade** [comment]
@davidsowerby try adding `testRuntime "org.junit.platform:junit-platform-launcher:1.0.0-M4"`

**Comment by davidsowerby** [comment]
@raniejade great, that was quick, thanks - solved the problem, and still works under Gradle
