### ISSUE TITLE
Rename maven coordinates

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#241]
As discussed we will be moving to `org.spekframework.spek2` as our group id. 

Below are the new coordinates:

- `org.jetbrains.spek:spek-api` -> `org.spekframework.spek2:spek-dsl` 
- `org.jetbrains.spek:spek-junit-platform-engine` -> `org.spekframework.spek2:spek-runner-junit5`
- `org.jetbrains.spek:spek-subject-extension` -> `org.spekframework.spek2:spek-extension-subject`
- `org.jetbrains.spek:spek-data-driven-extension` -> `org.spekframework.spek2:spek-extension-data-driven`

Here are some additional artifacts for `2.0`:

- `org.spekframework.spek2:spek-runtime-common`
- `org.spekframework.spek2:spek-runtime-jvm`

Do note that this not include renaming the packages.

**Comment by ming13** [comment]
What about omitting `2`? I think the difference between `org.jetbrains.spek` and `org.spekframework.spek` is enough. The version will be in the artifact version.

The only confusion point I foresee is the third version, which will force awkward naming, i. e. `org.spekframework.spek` + `org.spekframework.spek3`.

CC @artem-zinnatullin

**Comment by hhariri** [comment]
I'd keep the 2 cause as you mention, 3 will be awkward.

**Comment by artem-zinnatullin** [comment]
I'd keep 2 as well, lots of people don't understand what RxJava version belongs to `rx.` and what version belongs to `io.reactivex.`, I don't same problem for Spek.

@ming13 I understand your desire to make everything as short and beautiful as possible, but sometimes explicitness is more pragmatic :)
