### ISSUE TITLE
Introduce meta annotations for IDE consumption

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#246]
Motivation
========

The IDEA plugin hard codes all synonyms we currently provide, which is not flexible if we want to support running user implemented synonyms. 

Proposal
=======
Introduce meta annotations that any IDE can check for synonyms.

```kotlin
enum class SynonymType {
    Group,
    Action,
    Test
}

annotation class Synonym(val type: SynonymType, 
                         val prefix: String = "", 
                         val excluded: Boolean = false)
```

So with the annotations above, let's annotate `describe`:

```kotlin
@Synonym(type = SynonymType.Group, prefix = "describe ")
fun SpecBody.describe(description: String, body: SpecBody.() -> Unit) {
    group("describe $description", body = body)
}

```

and `xdescribe`:

```kotlin
@Synonym(type = SynonymType.Group, prefix = "describe ", excluded = true)
fun SpecBody.xdescribe(description: String, reason: String? = null, body: SpecBody.() -> Unit) {
    group("describe $description", Pending.Yes(reason), body = body)
}
```

**Comment by raniejade** [comment]
cc @hhariri @artem-zinnatullin

**Comment by artem-zinnatullin** [comment]
Very nice idea!

`prefix` is what IntelliJ plugin will output?

**Comment by raniejade** [comment]
More or less yes, it will use it to compute the scope's path to run.

**Comment by ming13** [comment]
I’m probably too late, but it would be nice to append a space symbol by Spek itself. I. e. not `prefix = "describe "`, but `prefix = "describe"`. Does it make sense?

**Comment by raniejade** [comment]
Well, I don't mind either way. Since @artem-zinnatullin brought up the same concern, I'm fine changing it.

**Comment by raniejade** [comment]
This is done in `2.x`, will make another PR for the changes.
