### ISSUE TITLE
beforeGroup is executed after my code in group 

### ISSUE THREAD

**Issue by Saandji** [JetBrains/spek#258]
Here is my test: 
```
object MySpek : Spek({
    val myMock1: MyMock1 = mock()
    val myMock2: MyMock2 = mock()
    val handler = StartModeHandler(myMock1, myMock2)

    val session = mock<Session> {
        on { user }.doReturn(User.builder().withUserId("userId").build())
    }
    describe("item exists for user") {
        beforeGroup {
            reset(digitalPointDao, trackDao)
        }
    whenever(myMock1.loadItem(session.user.userId)).thenReturn(Optional.of(MyItem()))
        whenever(myMock2.loadSomething()).thenReturn(ArrayList())
        context("method onLaunch was called") {
            val response = handler.onLaunch(session)
            it("should return the response for existing user") {
                //some asserts here
            }
            it("should save the item") {
                //some mock verifies here
            }
        }
    }
})
```

According to Spek documentation, i expect the flow to be following: 

1. initialize everything before `describe`
2. call `beforeGroup`
3. initalize `describe` body e.g. my whenever calls for mocks
4. run `context` 
5. run each `it` method

But i'm getting the following flow:
1. initialize everything before `describe`
2. run my `describe` body e.g. my whenever calls for mocks
3. run `context`
4. run `beforeGroup`
5. run each `it` method

Am I miss something in the documentation or is it a bug?

**Comment by raniejade** [comment]
I answered your question in SO, closing this as it's not an issue w/ Spek.
