### ISSUE TITLE
JUnit Platform Runner 1.0.0 does not work with Spek v1.1.4

### ISSUE THREAD

**Issue by ddubson** [JetBrains/spek#262]
The latest release of JUnit Platform Runner `1.0.0` does not seem to work with Spek 1.1.4, throwing the following error: 

```
WARNING: TestEngine with ID 'spek' failed to discover tests
java.lang.IllegalAccessError: tried to access method org.junit.platform.engine.support.descriptor.ClassSource.<init>(Ljava/lang/Class;)V from class org.jetbrains.spek.engine.SpekTestEngine
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:114)
```

However, JUnit platform runner `1.0.0-RC3` works just fine.

**Comment by artem-zinnatullin** [comment]
Should be fixed by #260, please wait for new release :)

**Comment by jamesbassett** [comment]
Great to see this has been fixed already :) Any ETA on the release?

**Comment by fgaule** [comment]
+1

**Comment by raniejade** [comment]
Sorry for the delays, doing the release now. `1.1.5` will be available in bintray and central in a couple of hours.

**Comment by jamesbassett** [comment]
Awesome, thanks!

**Comment by jamesbassett** [comment]
Yay it works :) Will 1.1.5 be available via jcenter/central given that it's an [EAP release](http://spekframework.org/downloads)? At the moment I have to add the jetbrains repo. If it's not, when's the next normal release?

**Comment by fgaule** [comment]
+1
