### ISSUE TITLE
Spek does not discover all spek tests

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [JetBrains/spek#263]
Hi,

In my project at https://github.com/volodymyrprokopyuk/kotlin-fp I've 19 spek unit tests. Only 15 tests are discovered and executed. The remaining 4 tests are not discovered for unknown to me reason. All the tests follow the same pattern and have the same structure and I don't see any difference that could be the reason for not discovering and executing the tests.

I'm using Spek 1.1.4 and JUnit Gradle Plugin 1.0.0-RC3 because the version 1.0.0 of the plugin does not work with Spek 1.1.4. The issue is reproducible on Linux Mint and Windows 7 machines. Could you please have a look at it? To reproduce the issue the below has to be done:
1. git clone https://github.com/volodymyrprokopyuk/kotlin-fp.git
1. cd kotlin-fp
1. gradle clean test

Is there a way to get a report of the executed tests to see what tests have been executed and what test are not discovered?

**Comment by raniejade** [comment]
Hey sorry for the delay, been busy with some personal stuff. Looks like you removed spek from your project, if you still need some help just let me know.

**Comment by volodymyrprokopyuk** [comment]
Thank you for your attention and reply! But I had to move forward so I switched to JUnit 5
