### ISSUE TITLE
Not run methods beforeEachTest and afterEachTest 

### ISSUE THREAD

**Issue by volkdown** [JetBrains/spek#265]
I'm trying to write a test. But I'm very confused. In accordance with the code, the presenter must be initialized in method beforeEachTest. And the condition must be cleared in method afterEachTest. But when I run the test, it failed an error NPE in line mPresenter!!.setPass(PASSWORD, PASSWORD). But if you uncomment the two lines in front of it, then the test will succeed. What could be the problem? Thanks in advance for answers

```
object ResetPasswordPresenterTestKotlin : Spek({

    include(RxSchedulersOverrideSpek)

    val PASSWORD = "123456aZ";

    var mView = mock<ResetPasswordView>{}

    var mMockDataManager = mock<DataManager>{}

    var mToken = mock<SuccessDetails>{}

    var mPresenter : ResetPasswordPresenter ?= null

    beforeEachTest {
        print("beforeEachTest")
        mPresenter = ResetPasswordPresenter(mMockDataManager)
        mPresenter!!.attachView(mView)
    }

    afterEachTest {
        print("afterEachTest")
        mPresenter!!.detachView()
        reset(mView)
    }


    describe("Reset password is succesful") {
        given(mMockDataManager.setNewPassword(any())).willReturn(Observable.just(mToken))
        /*mPresenter = ResetPasswordPresenter(mMockDataManager)
        mPresenter!!.attachView(mView)*/
        mPresenter!!.setPass(PASSWORD, PASSWORD)
        it("show loading progress") {
            verify(mView).showLoadingProgress()
        }
        it("hide loading progress") {
            verify(mView).hideLoadingProgress()
        }
        it("show on success") {
            verify(mView).onSuccess()
        }
        it("no show error") {
            verify(mView, never()).showError(RuntimeException())
        }
    }
})
```
testCompile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile 'org.jetbrains.spek:spek-api:1.1.2'
    testCompile 'org.jetbrains.spek:spek-subject-extension:1.1.2'
    testCompile 'org.jetbrains.spek:spek-junit-platform-engine:1.1.2'
    testCompile 'org.junit.platform:junit-platform-runner:1.0.0-M4'
    testCompile "com.nhaarman:mockito-kotlin:1.4.0"
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"

**Comment by raniejade** [comment]
As mentioned in the docs, Spek will eagerly any code within a group (`given`, `describe`, `context`). For your case you could use an action scope (`on`):

```kotlin
object ResetPasswordPresenterTestKotlin : Spek({
    ...
    
    on("Reset password is successful") {
        ...
    }
})
```
