### ISSUE TITLE
Can't run tests in IntelliJ

### ISSUE THREAD

**Issue by charleskorn** [JetBrains/spek#278]
Whenever I try to run a test from IntelliJ, I get the following error:

```
Testing started at 11:05 AM ...
objc[2826]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x107e194c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x107ea54e0). One of the two will be used. Which one is undefined.
Oct 11, 2017 11:05:31 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
java.lang.NoSuchMethodError: org.junit.platform.engine.support.descriptor.ClassSource.from(Ljava/lang/Class;)Lorg/junit/platform/engine/support/descriptor/ClassSource;
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:114)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:80)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
```

This happens whenever I right click on a test file and choose Run, or if I run a Spek configuration set to run all tests from my test package.

Running the tests from the command line with Gradle works file.

**Version info**
IntelliJ version: IntelliJ IDEA 2017.2.5
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13
Spek IntelliJ plugin: 0.4.3
Kotlin version: 1.1.51
Spek version: 1.1.5
`junit-platform-gradle-plugin` version: 1.0.1

**Comment by raniejade** [comment]
Can you try adding `org.junit.platform:junit-platform-runner:${junitPlatformVersion}` to your test classpath?

**Comment by charleskorn** [comment]
That worked, I added

```groovy
testRuntime "org.junit.platform:junit-platform-runner:$junit_version"
```

to my `dependencies`. (`junit_version` is set to `"1.0.1"`.) Is there any reason why this isn't included automatically? Seems a bit counter-intuitive to have to add a dependency to my project so that the IDE integration works correctly.

**Comment by charleskorn** [comment]
(thanks for your incredibly fast response by the way)

**Comment by raniejade** [comment]
No worries. We do bundle it, but it's an old version. Just need to update the plugin to include the latest one.

**Comment by raniejade** [comment]
Closing this in favor of https://github.com/raniejade/spek-idea-plugin/issues/52.

**Comment by sedovalx** [comment]
As far as I understand, it means the junit 4.12 runner is used. Which in turn means that ["the IDEA plugin won’t work"](http://spekframework.org/docs/latest/#setting-up-legacy). Is it right?
