### ISSUE TITLE
@CreateWith doesn't work with multiple class loader.

### ISSUE THREAD

**Issue by bangarharshit** [JetBrains/spek#286]
In robolectric, we want to run the test on a different class loader. In Junit 4 we achieved by writing our own custom runner - https://github.com/OleasterFramework/Oleaster/blob/master/oleaster-robolectric/src/main/java/org/robolectric/internal/RoboOleaster.java

The problem with spek:
```
@CreateWith(SampleInstanceFactoryTest::class)
        class RobolectricSpek(val sdkEnvironment: SdkEnvironment, val config: Config, val androidManifest: AndroidManifest ): Spek({

})
```
RobolectricSpek can't be instantiated with a custom class loader as it throws classcastexception. If it is not instantiated with a custom class loader, then all the callback method will run on the same and we will not be able to mimic android runtime.

**Comment by bangarharshit** [comment]
@artem-zinnatullin do you know how it works or if you can show me a test, it will expedite robolectric integration.

**Comment by raniejade** [comment]
@bangarharshit I'll look into it this week, sorry my internet was broken for a week.

**Comment by bangarharshit** [comment]
@raniejade Awesome. No Problem.

**Comment by artem-zinnatullin** [comment]
@bangarharshit in any case, please check our `2.x` branch, we won't merge any changes except bugfixes to `1.x`, really focusing on `2.x` now!

Btw, what if you just decouple your `RoboOleaster()` from JUnit runner API and call it in `beforeEachTest()` with required parameters?

**Comment by bangarharshit** [comment]
Thanks for the heads-up. Will check out 2.x and start working on it. 
It will not work since different callback methods such as `it`, `describe` called by frameworks will still be on the same class loader. 

In `RoboOleaster` all these methods were called from the robolectric's custom class loader (without writing my own TestEngine) .  

I want to find a way to run different callback methods on the custom classloader.

**Comment by artem-zinnatullin** [comment]
Hm, but then I guess it would require new instance of Spek class every time to load with proper classloader which will require significant changes in how Spek discovers and runs tests as well as disable some dynamic features…

If you could avoid that somehow, that would be fantastic :)

Btw, as far as I see it's only required for running test cases in same Spek with different Robolectric configurations, in simple case when we want to run whole Spek class on same Robolectric config, we just need to provide you a hook to run class with proper classloader and init/deinit function?

**Comment by bangarharshit** [comment]
Yep. That should be enough. 

RoboOleaster pretty much does that (unlike robolectric, it runs test only for 1 configuration). Developers can write different test classes to cover different configuration or we can give wrapper APIs like you suggested `listOf(Android.SDK_LEVEL_16, Android.SDK_LEVEL_21, Android.SDK_LEVEL_26).forEach`

@raniejade suggested using @CreateWith since it is designed for a similar purpose.
