### ISSUE TITLE
Spek doesn't create new instance of test class for each unit tests

### ISSUE THREAD

**Issue by bangarharshit** [JetBrains/spek#294]
JUnit creates a new instance of test class for every unit test. [Junit 5 lifecycle](http://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle)

Spek, however, uses the same instance for all tests. It breaks semantics for frameworks such as robolectric as different tests can run on different SDK version.  

A very simple spec test:
```kotlin
open class Calculator {
    var x: Int = 0

    fun setterX(x: Int) {
        this.x = x
    }

    fun getterX(): Int {
        return x
    }
}
```
Test class:
```kotlin
class CalculatorInstance: Spek({
    val calculator = Calculator()
    describe("Mutability test") {
        it("set X to 2") {
            println(calculator.getterX()) // prints 0
            calculator.setterX(2)
        }

        it("set x to 4") {
            println(calculator.getterX()) //prints 2 instead of 0 - BUG???
            calculator.setterX(4)
        }
    }
})

```

**Comment by artem-zinnatullin** [comment]
That's expected, as you can see Spek tests are basically lambdas inside lambdas which allows you do dynamic stuff like this:

```kotlin
listOf(testUser(type = regular), testUser(type = moderator), testUser(type = admin)).forEach { user -> 
  
    context("user $user signs in) {
    
        it("becomes active user") {
            assertThat(system.activeUserId).isEqualsTo(user.id)
        }

        when (user.type) {
             regular -> {
                  it("displays regular status badge) {
                      assertThat(system.badge).isEqualTo(user.displayName())
                  }
             }

             moderator -> {
                  it("displays moderator status badge) {
                      assertThat(system.badge).isEqualTo("${user.displayName()} [mod]")
                  }
             }

             admin -> {
                  it("displays admin status badge) {
                      assertThat(system.badge).isEqualTo("${user.displayName()} [admin]")
                  }
             }
         }
    }
}
```

With JUnit you declare test methods separately so framework can reason about them more statically.

Spek provides you easy to use APIs (`memoized` and `SubjectSpek`) to reinitialize test environment:

```kotlin
class CalculatorInstance: Spek({

    val calculator by memoized { Calculator() } // Note "memoized"

    describe("Mutability test") {
        it("set X to 2") {
            println(calculator.getterX()) // prints 0
            calculator.setterX(2)
        }

        it("set x to 4") {
            println(calculator.getterX()) // Should print 0 because memoized reinitializes property for every test case in a group.
            calculator.setterX(4)
        }
    }
})
```

**Comment by bangarharshit** [comment]
Got it. It still loses some flexibility (although very minor) - I can't run different tests on different configurations [SandboxTestRunner.java](https://github.com/robolectric/robolectric/blob/6fa38fc48242cbdcb08b54f4bd5b5a0a8dbee6f2/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L218)

Maybe a good thing to call out in the documentation.

**Comment by artem-zinnatullin** [comment]
Yes, definitely documentation should state that much clearer… (we'll rework it before Spek 2.x release)

Regarding running tests on different Robolectric configurations — how does it look like with JUnit (wasn't able to google it)? I only specified Android version on class level.

But in general it should be possible, Spek tests are simply code that you run, if Robolectric provides APIs to switch Android version you should be able to do something like this:

(pseudo code)

```kotlin
listOf(Android.SDK_LEVEL_16, Android.SDK_LEVEL_21, Android.SDK_LEVEL_26).forEach { sdkLevel ->

  context("android sdk level $sdkLevel") {

    beforeEachTest {
      SomeRobolectricApi.initWithAndroidSdkLevel(sdkLevel)
    }

    afterEachTest {
      SomeRobolectricApi.deinit()
    }

    it("works") {
        assertThat(something.works).isEqualTo(true)
    }
  }

}
```

**Comment by bangarharshit** [comment]
Robolectric uses reflection internally to figure out config but a similar API can be provided. I am working on the robolectric integration for spek.  

Looks like a good API. Once I am able to figure out https://github.com/spekframework/spek/issues/286, I can resume working on it.
