### ISSUE TITLE
Host Spek IntelliJ plugin in this repo.

### ISSUE THREAD

**Issue by artem-zinnatullin** [JetBrains/spek#298]
Currently plugin lives in @raniejade's personal repo https://github.com/raniejade/spek-idea-plugin, we've also allocated repo under `spekframework` https://github.com/spekframework/spek-idea-plugin.

That complicates development (especially development of unpublished `2.x`), so as discussed in https://github.com/spekframework/spek/pull/295#issuecomment-338459487 we can bring IntelliJ plugin sources to this repo.

Pros:

- Easier to keep Plugin and Spek in sync
- Much easier `2.x` sync
- Easier community contributions
- Easier testing (changes to Spek will be compiled against Plugin and we could run tests for Plugin)
- Discoverability of plugin sources for external developers

cc @hhariri, @ming13  objections?

**Comment by arturdryomov** [comment]
None, SQLDelight and even Kotlin (I guess) does the same.

**Comment by raniejade** [comment]
Repo now host the source for `2.x` IJ plugin.
