### ISSUE TITLE
central repository sync

### ISSUE THREAD

**Issue by K0zka** [JetBrains/spek#31]
Could you upload spek to the central maven repository as well?
The problem is that if I build an app tested with spek, then I will not be able to upload to central because from central repository all artifacts depending on external repositories are rejected. see [1]

Thank you!

1: http://blog.sonatype.com/2010/03/why-external-repos-are-being-phased-out-of-central/

**Comment by mfulton26** [comment]
Now that a 1.0-eap is available can getting this into The Central Repository be prioritized higher? Thanks.

**Comment by hhariri** [comment]
Absolutely. Will be putting it there with the release.
