### ISSUE TITLE
All Ons executes before Its

### ISSUE THREAD

**Issue by cardctor** [JetBrains/spek#32]
Actual: All Ons executes before Its.
Expected: Its executes after his Ons.
Kotlin M8 and Spek 0.127
  
    class SpekSpecs: Spek() {{
        given("given1") {
            var log = ""
            on("on1") {
                log += "on1"
                it("it1 goes after on1") {
                    log += "it1"
                    shouldEqual("on1it1",log)
                }
            }
    
            on("on2") {
                log += "on2"
                it("it1 goes after on1 and it2 goes after on2") {
                    log += "it2"
                    shouldEqual("on1it1on2it2",log)
                }
            }
        }
    }}

**Comment by jkcclemens** [comment]
Any news on this issue?

**Comment by hhariri** [comment]
With the current way Spek is designed it's close to impossible to get this to work, that's why we're considering changing some of the DSL and this is in process. Sorry for delay.

**Comment by alpacagh** [comment]
This issue was created 1 year 5 months 2 days ago, any chances for resolution?
May be at least some documentation note for such case?

**Comment by hhariri** [comment]
The current structure of Spek does not allow it without either 

a) A major redesign
b) Dropping complete JUnit infrastructure and writing most of the support JUnit now provides from scratch.

For now and to avoid further confusion, I've dropped before/afterOn. This can still be done just placing the function calls before the actual on.

**Comment by lkogler** [comment]
I took a stab at fixing this problem and ended up doing quite a bit of changes.  You can see my fork over at https://github.com/lkogler/spek.  Basically, I changed the DSL to behave like RSpec: you can have `describe` blocks nested to arbitrary depth, and there are `beforeEach` and `afterEach` blocks that execute before and after every `it` block. 

I know that it's quite a major change, I'd love to hear what people think before spending the time to put the finishing touches on it for a pull request.  Please let me know if this is something that sounds interesting!
