### ISSUE TITLE
spek tests

### ISSUE THREAD

**Issue by ayrat555** [JetBrains/spek#320]
I’m trying to read through spek source code. but I can’t find any tests. where should I look?

**Comment by raniejade** [comment]
Already replied to you on slack, closing this issue.

**Comment by ayrat555** [comment]
Thank you
> Most of the tests can be found here: https://github.com/spekframework/spek/tree/2.x/spek-runtime/jvm/src/test/kotlin/org/spekframework/spek2/jvm
