### ISSUE TITLE
Support for testing platform common code

### ISSUE THREAD

**Issue by markusamshove** [JetBrains/spek#327]
Hello,

we're trying to port [Kluent](https://github.com/MarkusAmshove/Kluent) to be (kotlin)platform independent in the future (MarkusAmshove/Kluent#75), so that you can use it in kotlin-jvm, -javascript and -native. In the past we only supported Java as a platform and therefore wrote all our unittests with Spek.

I've fiddled around and split the project into platform specific parts and one common project, which provides all the assertions for Kotlin stdlib things (like String, CharSequence, Int, ....).
As the common project provides the most functionality out of all others it includes roughly 1000 unittests written in Spek.

I've ported a few tests to `kotlin.test` just to try out if it would run them under the platform specific projects (which it does).

Your [2.0 milestone](https://github.com/spekframework/spek/milestone/3) suggests that you're aiming for multilplatform support.
Does this also include the Kotlin `common` projecttype (as in `kotlin.test`) or do we have to port all our tests to `kotlin.test`?

**Comment by raniejade** [comment]
I don't think you can run `test` on a common module directly, but it will be executed when you run `test` on a specific platform module. Nonetheless, it will most likely be supported in some way. Main goal for `2.x` is to prepare for multi-platform support, but the initial release will only support `JVM`.

**Comment by markusamshove** [comment]
Yeah thats true, the common module tests were run when gradle built the platform specific project, which makes sense and is actually pretty good, because it makes sure to run all tests (even from the common module) within each target platform.

It would be nice to be able to write unittests in the common library with Spek and let the platforms use their specific runner (which must be supported by Spek I guess)

**Comment by raniejade** [comment]
> It would be nice to be able to write unittests in the common library with Spek and let the platforms use their specific runner (which must be supported by Spek I guess) 

Planning to support this in the IntelliJ plugin but I'm waiting for `kotlin.test` to support it first so I have an idea on how to implement it.

**Comment by artem-zinnatullin** [comment]
I'm not sure `kotlin.test` is designed to give developers an abstract API to allow custom test frameworks like Spec.

Afaik it just pretty much 1-1 mapping to existing platform frameworks like JUnit4 and actually kinda hides that fact from you so if we'll need to hook into platform specific runner used by `kotlin.test` — that can be more complicated than supporting own multiplatform bindings.

**Comment by raniejade** [comment]
I think he only wants a way to test common modules like `kotlin.test`, not necessarily integrate with it.

**Comment by markusamshove** [comment]
@raniejade is right.

I'm trying to separate the JVM projekt into a platform independent common module, which works fine from the Kotlin perspective.

However all tests we've written (which need to be in the common module) are written in Spek.
The only platform independent way to write tests is `kotlin.test` in the moment.

What I'd like to do in the future:

* Write tests in the common module via Spek (so I don't have to port [over 1000 tests](https://github.com/MarkusAmshove/Kluent/tree/master/src/test/kotlin/org/amshove/kluent/tests) to `kotlin.test`)
* Run `build` against a platform (e.g. java)
* The platform build runs all tests for platform specific stuff and all tests in the common module

I guess this might make the way I asked my question wrong.
I don't necessarily need a Spek-wrapper around `kotlin.test`, but a platform independent Spek :-)
I thought making a wrapper would be easier because they already have runner implementations for Java (Junit), JavaScript (Qunit) and I guess something for native in the future.

**Comment by raniejade** [comment]
Possible now in `2.x`
