### ISSUE TITLE
Improve spec discovery

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#328]
Currently the `jvm` runtime will search the classpath for subclasses of `Spek` during the discovery phase. This is not optimal specially when running specs from the IDE, where most of the time we only want to run a specific class. `SpekRuntime#discover` accepts a `DiscoverRequest` parameter which currently only have a single property `path`. We could add extra properties here that each runtime could use to speed up the discovery phase. One example is adding a `source directory` parameter that can limit the search space for specs.

**Comment by raniejade** [comment]
cc @artem-zinnatullin @ming13 @hhariri

**Comment by artem-zinnatullin** [comment]
I think we should be able to rewrite `discover()` phase of `SpekRuntime` to not start with `reflections.getSubTypesOf(Spek::class.java)` if `DiscoveryRequest` has specific path?

**Comment by raniejade** [comment]
We could set a specific path for `reflections` to narrow down the search.

**Comment by artem-zinnatullin** [comment]
SGTM, my point here is that initial `path` passed in `DiscoveryRequest` should be enough :)
