### ISSUE TITLE
Incorrect reporting of exceptions in "on" clause 

### ISSUE THREAD

**Issue by serddmitry** [JetBrains/spek#33]
Tested on 0.1-SNAPSHOT (0.1-20140926.162946-6)

When there is an exception thrown inside "on" clause, IntelliJ shows me "Tests were not started".
Furthermore, other given clauses don't run at all.

Expected behavior: 
- exception in one clause shouldn't affect the others
- IntelliJ test runner should mark only failed clauses as failed

**Comment by madhead** [comment]
I'm still having the same issue...
