### ISSUE TITLE
Setup instructions not working for gradle with Kotlin DSL

### ISSUE THREAD

**Issue by favetelinguis** [JetBrains/spek#330]
Im trying to use Spek following the instructions for setting it up using Gradle with Kotlin DSL however im getting the following error for configuration:

Type inference failed: Not enogh information to infer parameter T in inline fun <reified T : Any>
Project.configure(noinline configuration T.() -> Unit): Unit
Please specify it explicitly

```kotlin
configure {
    filters {
        engines {
            include("spek")
        }
    }
}
```

**Comment by artem-zinnatullin** [comment]
Hi @favetelinguis, 

We don't control neither Kotlin Gradle DSL nor JUnit5 Gradle Plugin, not sure what we can do here…

Would be great if you could create issue in [JUnit5 Gradle Plugin](https://github.com/junit-team/junit5/tree/master/junit-platform-gradle-plugin) and crossreference it with this one. 

If JUnit team also decide that it's not in their control — please create issue against [Kotlin Gradle DSL](https://github.com/gradle/kotlin-dsl) and also crosslink it with this one

Thanks!

Sorry about that!

**Comment by rainkinz** [comment]
For those trying to get this working who are a bit new to Gradle, this worked for me:

```
configure<JUnitPlatformExtension> {
    filters {
        engines {
            include("spek")
        }
    }
}
```
