### ISSUE TITLE
Prevent users from nesting actions.

### ISSUE THREAD

**Issue by artem-zinnatullin** [JetBrains/spek#331]
```kotlin
Spec : Spek({
  on("some action") {
  
    action.run()

    it("does something") {}

    on("nested action") {
      // We should either support that or fail the spec, ideally at compile time.
    }
  }
})
```

Possible solutions:

- Detect problem at runtime and throw exception
- `@DslMarker` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-dsl-marker/

**Comment by raniejade** [comment]
https://github.com/spekframework/spek/blob/2.x/spek-dsl/common/src/main/kotlin/org/spekframework/spek2/meta/SpekDsl.kt :) If we go with route 2, the minimum supported version will be Kotlin `1.1`.
