### ISSUE TITLE
Data driven extension with >3 parameters

### ISSUE THREAD

**Issue by michaeloa** [JetBrains/spek#334]
I'm testing out the data-driven extension, since I have a use-case where I think it would be useful (have to all combinations of inputs for 9 - possible more - input parameters). It would be really useful in terms of having testers developing the test cases, rather than implementing each test case manually.
- What is the status of this?
- What are the plans for extending the number of parameters? I see that on currently only handles 3, while the data class has support for up to 9.

**Comment by michaeloa** [comment]
Any thoughts on this? The 1-3 input versions seem to work; is the code solid enough that it would make sense to fork it and simply add the variations of "on" that I require?

**Comment by raniejade** [comment]
We should sync up the extension functions and data classes, is there a way to generate them @ming13 @artem-zinnatullin?

**Comment by raniejade** [comment]
Data driven extension has been dropped in `2.x`.
