### ISSUE TITLE
Android LiveData testing @Rule InstantTaskExecutorRule

### ISSUE THREAD

**Issue by raosuj** [JetBrains/spek#337]
hey guys,

how do I use 
`@Rule
val rule = InstantTaskExecutorRule()`

inside spek to swaps the background executor.
I am trying to test MutableLiveData, but running into java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked when liveData.setValue us called
https://medium.com/@veniosg/unit-testing-with-mutablelivedata-22b3283a7819

ps: very new to spek
please help!

**Comment by raosuj** [comment]
i am getting @Rule annotation is not allowed to target local variable when I use it inside spek

**Comment by artem-zinnatullin** [comment]
`Rule` is a JUnit concept. 

Unfortunately, generic `Rule` interface is designed to wrap test case and decorate it with some behavior without exposing methods like `before()` and `after()` (only [`ExternalResource` rule does that by default](http://junit.org/junit4/javadoc/latest/org/junit/rules/ExternalResource.html)) that could be called from Spek's `beforeEachTest` and `afterEachTest`.

Spek provides all necessary callbacks to decorate tests, but generic `Rule` just not designed in a way to be used like that.

**However**, `Rule` is just bunch of code that runs before and after the test, so you should be able to extract/copy it from `Rule` and apply it in `beforeEachTest {}` / `afterEachTest {}` inside Spek!

**Comment by quiqua** [comment]
I ran into this as well and as @artem-zinnatullin pointed out its fairly easy to achieve:

```
        // In order to test LiveData, the `InstantTaskExecutorRule` rule needs to be applied via JUnit.
        // As we are running it with Spek, the "rule" will be implemented in this way instead
        beforeEachTest {
            ArchTaskExecutor.getInstance().setDelegate(object : TaskExecutor() {
                override fun executeOnDiskIO(runnable: Runnable) {
                    runnable.run()
                }

                override fun isMainThread(): Boolean {
                    return true
                }

                override fun postToMainThread(runnable: Runnable) {
                    runnable.run()
                }
            })
        }

        afterEachTest { ArchTaskExecutor.getInstance().setDelegate(null) }
```

**Comment by ailicic** [comment]
I am trying to test with LiveData in Spek and even with the above beforeEachTest/afterEachTest blocks I still get the same "Method getMainLooper in android.os.Looper not mocked" error which suggests the rule is not working. 

Is this perhaps related to LiveData being moved from androidx.arch.lifecycle to android.arch.lifecycle or ArchTaskExecutor being moved from androidx.arch.core.executor to android.arch.core.executor? Here are my versions:

AS 3.2.1
Gradle 4.6
Spek 2.0.0-rc.1

@quiqua Where did you get the source code for InstantTaskExecutorRule?

I also uploaded a [minimal sample project](https://github.com/ailicic/SpekLiveDataTest) to demonstrate the problem. Any advice you might have would be appreciated.
