### ISSUE TITLE
spec-sample tests are not run with ./gradlew test

### ISSUE THREAD

**Issue by nhekfqn** [JetBrains/spek#34]
I've changed TimingSpecification test so that it fails when running with IDEA runner, than tried to run 

```
./gradlew test
```

command from root of the project. Build succed. It looks like tests are not run while building project with gradle.

**Comment by zainfur** [comment]
Hi, I have a similar issue! Did you manage to fix it?

**Comment by hhariri** [comment]
Not ignoring this but Spek is going to need some changes soon and will get to this also.

**Comment by Chumper** [comment]
Looks like spec is not being updated anymore, is there a plan for spek 2 or is this still considered the actual development status?

Just curious since we are looking into spek and want to see if it is worth the time for a new project.

**Comment by hhariri** [comment]
Sorry. Was on the road. There are still plans. Can I ask you, what needs do you currently have? i.e. What aspects of Spek are currently interesting to you or provide benefit over existing solutions?

**Comment by Chumper** [comment]
Currently we are using Java, Cucumber and Gherkin to write test. That takes a huge amount of time and we are looking into solutions that will shorten the time to write tests without losing any quality.

We like the way how tests are written in Gherkin, but we dont like that everything needs to be defined over explicitly, so we are looking for some good compromises and spec is one of them.

**Comment by hhariri** [comment]
Thanks. Have you found any shortcomings right now in Spek? The reason we're redesigning, amongst others is to improve on the syntax for Spek. Right now you had to use {{ }} (i.e. put everything in constructor. Since Kotlin now recommends *init* keyword before constructor, it already adds to removing a nicer syntax. The code in constructor also imposed certain limitations.
