### ISSUE TITLE
Erroring tests not marked as failing in command line output or xml

### ISSUE THREAD

**Issue by Rosomack** [JetBrains/spek#344]
Hi, 

I found that getting errors in a spec does not fail any tests that are inside. This is a minimal test case that exposes the issue:

```
class ErrorSpec : Spek({
    given("error in test") {
        beforeEachTest {
            throw NullPointerException()
        }
        on("do stuff") {
            it("doesn't fail the test") {
                true `should be` true
            }
        }
    }

    given("failure in test") {
        on("do stuff") {
            it("doesn't fail the test") {
                false `should be` true
            }
        }
    }
})
```
The above example only reports 1 test as failing (the assertion failing), but I'd expect any tests contained in a given that throw NPE's to be reported as failing too!

Note that if I didn't have the `it` nested in an `on` block I would get the failure reported correctly.

**Comment by raniejade** [comment]
I guess this is kinda expected when using `on` (action scope) since tests (`it`) are discovered only during the execution phase. Since `beforeEachTest` throws an exception, execution stops and `on("do stuff")` is never executed. Nonetheless, this should still be fixed.  Thanks for reporting!
