### ISSUE TITLE
Sample maven project

### ISSUE THREAD

**Issue by nhekfqn** [JetBrains/spek#35]
I tried to configure sample maven project with spek tests runnable from IDEA and during maven build but had no luck.

What I tried:

1. configured sample maven project with kotlin JUnit test similar to https://github.com/JetBrains/kotlin-examples maven/mixed-code-hello-world. Tests runs fine both with IDEA (ultimate 14.0.2) and ```maven test``` (from command line).
2. added spek dependency as described at http://jetbrains.github.io/spek/download.html version 0.1-SNAPSHOT was used. Btw: versions like 0.127 or 0.145 mentioned on the page do not exist - should be like 0.1.127 or 0.1.145
3. added spek test

```
import kotlin.test.assertEquals
import org.jetbrains.spek.api.Spek

class BlaherSpecs: Spek() {{

    given("Let's test Blaher") {
        val blaher = Blaher()
        on("Blaher blah") {
            val blah = blaher.blah()
            it("should be Blah!") {
                assertEquals("Blah1!", blah)
            }
        }
    }
}}
```

it didn't compile because maven dependency had ```<type>pom</type>``` - compliled after commenting that out.

4. Tried to run it with IDEA runner - got

```
/bin/bash /Users/admin/Projects/kotlin/src/test/java/SpecSample.kt
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt: line 1: import: command not found
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt: line 2: import: command not found
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt: line 4: syntax error near unexpected token `('
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt: line 4: `class BlaherSpecs: Spek() {{'
```

When building with maven it looks like SpecSample gets compiled 

```
[info] Kotlin Compiler version 0.10.372
[info] Compiling Kotlin sources from [src/test/java]
[info] Classes directory is /Users/admin/Projects/kotlin/target/test-classes
[debug] Removed target directory from compiler classpath (/Users/admin/Projects/kotlin/target/test-classes)
[info] Classpath: src/test/java:/Users/admin/Projects/kotlin/target/classes:/Users/admin/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/0.10.195/kotlin-stdlib-0.10.195.jar:/Users/admin/.m2/repository/org/jetbrains/kotlin/kotlin-runtime/0.10.195/kotlin-runtime-0.10.195.jar:/Users/admin/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/admin/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/admin/.m2/repository/org/jetbrains/spek/spek/0.1-SNAPSHOT/spek-0.1-SNAPSHOT.jar
[info] Classes directory is /Users/admin/Projects/kotlin/target/test-classes
[debug] Scanning for kotlin annotations in /Users/admin/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/0.10.195/kotlin-stdlib-0.10.195.jar
[debug] Scanning for kotlin annotations in /Users/admin/.m2/repository/org/jetbrains/kotlin/kotlin-runtime/0.10.195/kotlin-runtime-0.10.195.jar
[debug] Scanning for kotlin annotations in /Users/admin/.m2/repository/junit/junit/4.10/junit-4.10.jar
[debug] Scanning for kotlin annotations in /Users/admin/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
[debug] Scanning for kotlin annotations in /Users/admin/.m2/repository/org/jetbrains/spek/spek/0.1-SNAPSHOT/spek-0.1-SNAPSHOT.jar
[info] Using kotlin annotations from /Users/admin/.m2/repository/org/jetbrains/kotlin/kotlin-jdk-annotations/0.1-SNAPSHOT/kotlin-jdk-annotations-0.1-SNAPSHOT.jar
[debug] Using Kotlin home directory <no_path>
[debug] Configuring the compilation environment
[debug] Output:
/Users/admin/Projects/kotlin/target/test-classes/BlaherSpecs.class
Sources:
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt
[debug] Output:
/Users/admin/Projects/kotlin/target/test-classes/BlaherSpecs$1.class
Sources:
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt
[debug] Output:
/Users/admin/Projects/kotlin/target/test-classes/BlaherSpecs$1$1.class
Sources:
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt
[debug] Output:
/Users/admin/Projects/kotlin/target/test-classes/BlaherSpecs$1$1$1.class
Sources:
/Users/admin/Projects/kotlin/src/test/java/SpecSample.kt
```

but SpecSample test does not run - it should fail, but build succed.

I want to setup spek project with maven and IDEA so that

1. I can run spek tests from IDEA - it works with this project spek-samples, so I assume it can be done. spek-samples is on gradle and spek dependency is ```compile project(':spek-core')``` though.

2. Spek tests get run on maven build - I found no description or working sample how to achive that.

Sample project available at https://github.com/nhekfqn/kotlin-spek-maven-sample

If you help me to configure sample project, I will publish working version on github so that others can use it.

Thanks in advance.

**Comment by hhariri** [comment]
Thanks. Going to take a look.

**Comment by krischik** [comment]
Got the same problem when importing a Gradle library project:

```
Error:Failed to find: org.jetbrains.spek:spek:0.145
```

I used:

```gradle
repositories {
   mavenCentral ()
   maven {
      url "http://repository.jetbrains.com/all/"
   }
}

dependencies {
   compile (
      [group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '0.10.195']
   )
   testCompile (
      [group: 'org.jetbrains.spek', name: 'spek', version: '0.145']
   )
}
```

Stange thing: It build just fine.

**Comment by hastebrot** [comment]
Somehow the Spek and Kotlin artifacts at http://repository.jetbrains.com/all/org/jetbrains/ seem to be outdated.

**Comment by hhariri** [comment]
Rebuilding now. Not sure why it didn't rebuild.

**Comment by jvelo** [comment]
I have the same issue as @nhekfqn. I managed to have maven build the specs, but they are not executed (they should fail, but build succeeds).
I have kotlin version ```0.12.613``` and spek version ```0.1.165```.
I have set ```<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>```, where my specs are.

**Comment by hhariri** [comment]
Can you post some sample project please?

**Comment by jvelo** [comment]
I've created https://github.com/jvelo/kotlin-spek-maven which builds successfully with ```mvn test``` when I would expect it to fail

**Comment by aneveux** [comment]
Hello,

Any news regarding that topic? We have the same problem of our tests not being executed with Maven. You can find our project right here as an example: https://github.com/ktoolz/rezult

Running `mvn test` won't do anything, but running the tests in IntelliJ actually executes everything.

Thanks a lot for your help :)

**Comment by snowe2010** [comment]
Anyone here? This is still a problem.

**Comment by hhariri** [comment]
@snowe2010 is this resolved per Slack?

**Comment by hhariri** [comment]
here's a sample. I'll update demos to also include this. https://www.dropbox.com/s/tmv8evocxuu69h5/kotlin-spek-maven.zip?dl=0

**Comment by snowe2010** [comment]
note that I had to reduce the `junit-platform-surefire-provider` version number to M3 from M4 for it to work for me.
