### ISSUE TITLE
Spek plugin fails with Android Studio 3.1 Canary 8.

### ISSUE THREAD

**Issue by yunikkk** [JetBrains/spek#354]
Spek plugin `0.5.4-studio3.0` fails to run tests.
Trying with sample https://github.com/spekframework/spek-android-example produces
`Error running 'org.spekframework.speksample.CalculatorSpec': com.android.tools.idea.gradle.project.model.AndroidModuleModel.getSelectedVariant()Lcom/android/tools/idea/gradle/project/model/ide/android/IdeVariant;` 
This is very similar to the error which appeared with gradle sync-s in Studio Canary 3, https://stackoverflow.com/questions/47290290/android-studio-3-1-canary-3-gradle-sync-failed.

**Comment by arielouziel** [comment]
Same in Canary 9...

**Comment by yunikkk** [comment]
I've created an issue for that in the spek-idea-plugin repo, https://github.com/raniejade/spek-idea-plugin/issues/64

**Comment by radityagumay** [comment]
@yunikkk did you solve this issue? i just recently update to AS 3.1 and this break my spek in IDE
