### ISSUE TITLE
Document data-driven spek support

### ISSUE THREAD

**Issue by ianbrandt** [JetBrains/spek#364]
There is no mention [in the documentation](http://spekframework.org/docs/latest/) of the functionality added by pull request #180.

**Comment by rusio** [comment]
From reading through #180 and #146 it seems that Spek features a nicer API for data-driven tests than KotlinTest, which is well documented. We would like to replace a suite of Groovy based Spock tests with Spek, but the lack of documentation carries the risk that the API can be changed. So while it looks impressive, the feature is useless without docs.

**Comment by raniejade** [comment]
Data driven extension was dropped in `2.x`, closing this issue.
