### ISSUE TITLE
SubjectSpek not found

### ISSUE THREAD

**Issue by HeliumEnd** [JetBrains/spek#365]
I was trying to use `SubjectSpek` in my tests but gradle reported back saying `Unresolved reference: subject` in `org.jetbrains.spek` (this is relating to version 1.1.5). I found no documentation on how to get `SubjectSpek`.

The only way I figured it out was looking into spek-api jar, noticed a folder in the spek github with the same name and tried adding the subject extension as a dependency and it worked.

So...

To get SubjectSpek add `spec-subject-extension` as a dependency.

```
dependecies {
...
testCompile 'org.jetbrains.spek:spek-subject-extension:1.1.5'
...
}
```

**Comment by asksahil** [comment]
I am facing same issue as well

**Comment by raniejade** [comment]
We moved subjects to another module, looks like it was not mentioned in the docs.

**Comment by raniejade** [comment]
Not relevant anymore, subject extension is dropped on `2.x`. Will add a migration docs specifically for it.
