### ISSUE TITLE
Coverage Reporting broken for "Run .. with Coverage" 

### ISSUE THREAD

**Issue by Mugurell** [JetBrains/spek#373]
Android Studio 3.0.1
Spek plugin 0.5.4-studio3.0

Using the default Intellij IDEA coverage runner results in reports that factor all the files in project.
![image](https://user-images.githubusercontent.com/11428869/36892145-8a989ad8-1e0c-11e8-8f69-6e1cb3fb2a52.png)

Using Jacoco is not possible because that option is not remembered after closing the "Run/Debug Configurations" window"
![image](https://user-images.githubusercontent.com/11428869/36892276-ef8bc348-1e0c-11e8-8fdf-b22e9c36955a.png)

**Comment by radityagumay** [comment]
@Mugurell  hi, i just made a PR spekframework/spek-android-example#2, please close this if solve you issue. @raniejade
