### ISSUE TITLE
Split Specification and Gherkin-style DSLs

### ISSUE THREAD

**Issue by arturdryomov** [JetBrains/spek#374]
The [Spectrum](https://github.com/greghaskins/spectrum) BDD testing library has an interesting approach to the `describe` + `context` vs. `given` + `when` dilemma. Basically [it identifies them as separate styles](https://github.com/greghaskins/spectrum/tree/1.2.0/docs#supported-features) and hides DSL in different packages.

Personally I think it is an awesome idea. Unfortunately I have no good ideas about how we can adopt this besides making it extra-clear in docs.

@raniejade @artem-zinnatullin What do you think?

**Comment by raniejade** [comment]
I'm game for this, one thing we could do is to introduce a different subclass for each style to prevent people mixing the different styles. Something like:

```kotlin
abstract class SpekStyle1(val body: Style1.() -> Unit)

abstract class SpekStyle2(val body: Style2.() -> Unit)
```

**Comment by hhariri** [comment]
I'd favour something that avoids people mixing and matching, cause that's led to a lot of confusion and errors in the past.

**Comment by raniejade** [comment]
@ming13 do you have the bandwidth to explore this idea?

**Comment by arturdryomov** [comment]
@raniejade I’m not sure it is a good idea to have multiple `Spek` classes because it will move confusion to a different place. Plus, the naming can be tricky, i. e. `GherkinSpek` + `SpecSpek`.

Maybe we can provide different DSL artifacts and implement them as extensions (please don’t hate me, I know I suggested to move them to functions). But! It will require each user to add another artifact... We can still stick to extensions and just place them in different packages, it will be more clear like that.

What do you guys think about all that?

**Comment by raniejade** [comment]
@ming13 That's a neat idea, it will also clearly show how customizable Spek is. We just need to clearly say in the docs the different styles and what artifacts they should include.

**Comment by raniejade** [comment]
One option for isolation is to only have a single entry DSL at the top-most scope (for each DSL styles). 

```kotlin
object SpecUsingJasmineLikeApi: Spek({
    describe("a set") {
          describe("when empty") {
               it(" ... ") { ... }
          }
    }
})
```

`describe` is defined as:
```kotlin
fun Root.describe(description: String, body: Specification.() -> Unit) { ... }
```

The gherkin style might look like:
```kotlin
fun Root.feature(description: String, body: Feature.() -> Unit) { ... }
```

Using `@DslMarker` will prevent nesting them.

```kotlin
class ThisWillFail: Spek({
    describe("something") {
        // not possible
        feature("something else") { ... }
    }
})
```

The DSLs will be using `group`, `action` and `test` under the hood. IDE support will be trivial with the new `@Synonym` annotation. Now with https://github.com/Kotlin/KEEP/issues/75, we could potentially have something like:

```kotlin
// set.kt
describe("a set") {
    describe("when empty") {
        it(" ... ") { ... }
    }
}
```

**Comment by robfletcher** [comment]
Is the plan to keep different styles structurally compatible? One thing I found infuriating with ScalaTest was that there are numerous different styles and porting an existing test from one style to another is a non-trivial effort.

**Comment by robstoll** [comment]
Would be nice if one can mix styles if one wants or it should at least be easy to add an own style.

**Comment by raniejade** [comment]
@robfletcher WDYM by structurally compatible? 

> Would be nice if one can mix styles if one wants or it should at least be easy to add an own style.

Mixing is what we are trying to avoid but you still have the option to create your own or extend an existing one.

**Comment by robfletcher** [comment]
@raniejade as in the differences are aliases for the same function rather than a fundamentally different way of structuring test cases.

**Comment by raniejade** [comment]
@robfletcher definitely, the only differences are the aliases/keywords used in each style. Structure will always be in the form of nested callbacks.

```kotlin
class Foo: Spek({
    group("some group") {
        group("another group") {
            test("some test") {
            }
        }

        action("some action") {
            test("some test") { ... }
        }
    }
})
```
