### ISSUE TITLE
Spek tests are not isolated

### ISSUE THREAD

**Issue by Odepax** [JetBrains/spek#376]
## Reproduce:

1. Initialize a Kotlin project with Spek;
2. Use the attached `src` folder;
3. Run all tests, they should fail;
4. For each `on` block:
    1. Comment out or delete all the **other** blocks;
    2. Run all tests, they should all go green.

Morality: the result of a test seems to depend on the actions executed on other tests.

* * *

**Attached:** `src` folder in [SpekTestsreNotIsolated.zip](https://github.com/spekframework/spek/files/1778498/SpekTestsAreNotIsolated.zip).

**Other info:** I'm running the tests with IntelliJ Spek plugin, with `org.jetbrains.spek:spek-api:1.1.5` and `org.jetbrains.spek:spek-junit-platform-engine:1.1.5`. Didn't use Gradle here, but it seems the problem is the same.

**Comment by raniejade** [comment]
This is expected, you should use `val counter by memoized { ThrowingCounter(3) }`. `given` is a group that will be eagerly invoked in the discovery phase. `on` on the other hand is an `action` which has the semantics you expect, the problem with it is that it can only contain tests (`it`).

**Comment by Odepax** [comment]
Ow, didn't know this one, nice anyway!

Also tried inheriting from `SubjectSpek<ThrowingCounter>` instead of  `Spek` and it worked. Same using `lateinit var subject: ThrowingCounter ; beforeEachTest { subject = ThrowingCounter(3) }`.

Is there a difference between these three methods, aside from taste preference?

* * *

PS: isn't it _memo-R-ized_?
