### ISSUE TITLE
M12 support

### ISSUE THREAD

**Issue by richardszalay** [JetBrains/spek#38]
Any chance we'll be seeing a maven drop that includes 1ac8fe232fb91ff08e56147e693178621ab0a68e?

(I realise I could use the snapshot version, but I'd rather keep my kotlin dependency on a stable release)

**Comment by hhariri** [comment]
Done. It should be published soon.

**Comment by richardszalay** [comment]
Thanks hhariri, though is there a reason the new build targets Kotlin 0.12.200 rather than 0.12.213?

**Comment by hhariri** [comment]
AFAIK 0.12.200 is M12, is it not?

**Comment by richardszalay** [comment]
It looks like 213 was released to Maven Central a day after 200, so I'm assuming its a quick bugfix release.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jetbrains.kotlin%22%20AND%20a%3A%22kotlin-stdlib%22

**Comment by hhariri** [comment]
Pushing 0.2.213 now.

**Comment by richardszalay** [comment]
Perfect, thanks!
