### ISSUE TITLE
1.1.5 release is broken

### ISSUE THREAD

**Issue by phatblat** [JetBrains/spek#380]
I ran into the same issue as #326 and found that the 1.1.5 release doesn't correspond to the `v1.1.5` tag. Can someone re-release 1.1.5?

**Comment by raniejade** [comment]
@phatblat I think you're using an incompatible version of JUnit Platform, what version are you using?

**Comment by phatblat** [comment]
@raniejade I tried several versions of the JUnit Platform, from 1.0.0-1.1.0. However, I suspect [the issue I was running into](https://github.com/spekframework/spek/issues/326#issuecomment-373492693) were due to some sort of caching issue because I'm now unable to reproduce them. I've never had any trouble with a [simple template project](https://github.com/phatblat/KotlinTemplate).
