### ISSUE TITLE
Impossible to iterate in parameterized tests

### ISSUE THREAD

**Issue by pedegie** [JetBrains/spek#389]
Hello, I'm trying to create parameterized test. I tried about ten different configurations, i put context blocks in many  places (before / after list), same to `on` and `it` sections, anyway behavior is "little" strange.  To keep it simple, lets look at this example:

```
@RunWith(JUnitPlatform::class)
class ChromeDriverConfigurationTest : Spek
({
 class DriverTest(val filePath: String, val expectedTextResult: String)
    given("Chrome Driver") {
    listOf(
        DriverTest(filePath = "js/js.html", expectedTextResult = "Text from JS!"),
        DriverTest(filePath = "jQuery/jQuery.html", expectedTextResult = "I come from jQuery!"),
        DriverTest(filePath = "angularv1/angularv1.html", expectedTextResult = "Hello from Angular v1!"),
        DriverTest(filePath = "reactJS/index.html", expectedTextResult = "Hello from reactJS!")
    ).forEach {
            it("should extract test") {
               println(it);
            }
        }
    }
})
// epomis.impl.ChromeDriverConfigurationTest$1$DriverTest@233795b6 - output
```

Why it executes only once? If i put `given` section in `forEach` there is also only one println

**Comment by pedegie** [comment]
Alright, finally I make it works. I need to 
a) move given section in forEach
b) make given description unique (so i put list closure as name)
c) mark DriverTest as data class, perhaps there was something wrong with toString metohd so point b didn't work.

**Comment by radityagumay** [comment]
@pedegie you cant doing that, description in each group for example in given is treatment as unique. so it will remains once.

please close you issue. thanks
