### ISSUE TITLE
Gradle JUnit Plugin deprecated

### ISSUE THREAD

**Issue by Khoulaiz** [JetBrains/spek#390]
Please document the proper way to include spek into a gradle build using the gradle 4.6 configuration features. The current recommended plugin is deprecated in favour of using the native gradle support.
I am afraid I am too dumb to figure out how it works correctly.

**Comment by radityagumay** [comment]
@Khoulaiz hi, i just made a PR https://github.com/spekframework/spek-android-example/pull/2, please close this if solve you issue. @raniejade

**Comment by Khoulaiz** [comment]
No, it does not resolve the issue. I don't want to know how to use a deprecated plugin (like you did in your sample project). I want to know how to use the native gradle support and I would like to read it in the official documentation of spek. I consider it as bug to use deprecated functionality, that's why I created this bug.

**Comment by raniejade** [comment]
JVM examples now use Gradle 4.7 and the built-in JUnit 5 support, unfortunately for android, we still need to rely on a 3rd party plugin - this is not deprecated.
