### ISSUE TITLE
Using 2.0 in Android Studio

### ISSUE THREAD

**Issue by curiousily** [JetBrains/spek#395]
Seeing that Milestone 2.0 is past due by [**5 months**](https://github.com/spekframework/spek/milestone/3) what is the recommended way to use the dev 2.0 version in Android Studio?

More importantly, any ETA of 2.0? Would you recommend switching to something like kotlintest or plain JUnit5 and not waiting for 2.0 release?

Thanks for all the wonderful work from the spek framework team!

**Comment by raniejade** [comment]
Firstly, very sorry for the delay. The team was pre-occupied with personal stuff and didn't have much time to work on `2.x`. As of now, you can't use `2.x` yet. I would suggest to use `1.x`, and migrate later on. We hope to make the miigration as smooth as possible, the plan is to allow projects to contain `1.x` and `2.x`  side-by-side.

Only when #374, #394 and #396 is done I can give a correct estimate. So far the IJ plugin is done for `2,x`, just a few more things for the AS plugin as well. #358 is the work needed for publishing the snaphosts.

**Comment by curiousily** [comment]
First, no need to be sorry, this is an open source, free of any charge, effort. And quite frankly, spek has been a very welcomed change for our team (living in JVM & Android world).

Thanks for the detailed response, will follow the progress on the mentioned issues!

Keep up the good work,
Thanks 😃

**Comment by raniejade** [comment]
@curiousily Hey! `2.0.0-aplha.1` is out, would you like to test it out? Didn't have time to setup a sample android project that uses it, but you can base it out the multiplatform example: https://github.com/spekframework/spek-multiplatform-example.

**Comment by radekkozak** [comment]
Hi, so i've setup quick **spek2** *proof-repo* based on original `spek-android-example` 

I'm not making PR yet - i think maybe we could incorporate it separately to have one working android sample project for each spek version. I think if someone ( @raniejade ? ) over at the spek team could prepare separete repo it would be great. I could easily PR in then 

As far as i tested in AS 3 my example includes working
- `android` spek2 tests + instrumented tests
- `non-android-lib` spek2 tests
- jacoco coverage for `non-android-lib` and all variants of `android` app. 

I've added jacoco cause i've seen many struggling to get it work with spek - not sure why is that, but here it works smoothly (as seen below):

![jacoco](https://user-images.githubusercontent.com/2744747/43930641-d3682aa6-9c3a-11e8-986c-fd524542a8b6.png)
![jacoco-non-androd-lib](https://user-images.githubusercontent.com/2744747/43930642-d387ec1a-9c3a-11e8-8348-e0fcb5f6fc43.png)
![android-instrumented](https://user-images.githubusercontent.com/2744747/43930650-da4ef2aa-9c3a-11e8-92ec-180deae14dc6.png)

Related also to: https://github.com/spekframework/spek-android-example/issues/4

**Comment by raniejade** [comment]
@radekkozak I'm thinking if the samples should be in the main repo. @artem-zinnatullin wdyt?

**Comment by artem-zinnatullin** [comment]
Yeah I'd start with samples in the repo, unless it becomes too unrelated to the Spek itself

**Comment by radekkozak** [comment]
Thanks for chiming in @artem-zinnatullin Well i guess it would probably make sense and made the  project more tight _vis-à-vis_ how it look right now. On the other hand it might be little easier from the perspective of the end user to just clone relevant sample and build on this rather than getting the whole project repo with whole caravan. Anyway, ultimately it's your call of course

**Comment by raniejade** [comment]
It will be much easier for us to maintain and keep up to date.

**Comment by radekkozak** [comment]
That is for sure. Ok then, i'm going to remove the sample in that case - or if you want to copy over it beforehand just to boot yours let me know and i will do that when you're done. 

Thanks for the great work on the framework btw, we already love it here and looking forward to 2.x getting out the beta

**Comment by raniejade** [comment]
@radekkozak if you could send the PR for the android example, it will be very appreciated :). Will submit separate PR for moving the jvm and mpp examples.

**Comment by radekkozak** [comment]
Aaa ok, i think i misunderstood you a little but no problem. I leave it to you then to merge it wherever you like as my quicky was based on original sample with 1.x version (that i think it's still beneficial to keep for those folks who use the old Spek)
