### ISSUE TITLE
JUnit5 Tags for Spek

### ISSUE THREAD

**Issue by kollikolli** [JetBrains/spek#403]
I am trying to distinguish my tests into Unit- and Integration tests.
My idea was to use the new JUnit5 Annotation `@Tag("unit")` which works nicely for my JUnit tests, but I cannot get it to work with Spek.

What I currently have is my class:

    data class MyObject(val value: Int)

My tests:

    @Tag("unit")
    object MyObjectTest {

        @Test
        fun checkEquality() {
            val o1 = MyObject(1)
            assertEquals(o1, o1)
        }
    }

With my build.gradle having:

    task utest(type: Test) {
        outputs.upToDateWhen { false }
        useJUnitPlatform {
            includeEngines 'junit-jupiter', 'junit-vintage', 'spek'
            includeTags 'unit'
            excludeTags 'performance', 'integration', 'functional'
        }

        testLogging {
            events "passed", "skipped", "failed"
        }
    }

When I execute utest, this works.
However when doing the same with Spek:

    @Tag("unit")
    object MyObjectSpek : Spek({

       given("an Object") {
           val o1 = MyObject(1)

           it("should be equal to itself") {
               assertEquals(o1, o1)
           }
       }
    })

What happens is if I run the gradle task utest it only executes the methods from `MyObjectTest` and does not execute the tests for `MyObjectSpek`

Any ideas on how to integrate Spek with JUnit5 Tags or another idea to seperate unit tests and integration tests?

**Comment by raniejade** [comment]
JUnit Jupiter and Spek are totally different frameworks, the only thing they share is JUnit Platform (`TestEngine`).  `@Tag` is a JUnit Jupiter API.
