### ISSUE TITLE
Contexts not detected unless tests are directly nested

### ISSUE THREAD

**Issue by nlwillia** [JetBrains/spek#404]
```
object SpekSpec : Spek({
	describe("root") {
		fun add() {
			it("test") {}
		}

		describe("a") {
			add()
		}
		describe("b") {
			add()
		}
	}
})
```
This ends up adding `root / test` instead of `root / a / test` and `root / b / test`.  It's not clear from the docs that there's a static structural requirement, so I'm not sure whether this is a bug, language limitation or just a bad expectation on my part.

**Comment by raniejade** [comment]
`root / test` is expected, since the `it` you are referencing in `add` belongs to the context `describe("root")` . For your expected behaviour you have to use extension functions:

```
fun SpecBody.add() {
    it("test") { }
}
```

Which will yield `root / a / test` and `root / b/ test`.

**Comment by nlwillia** [comment]
Ah, got it.  I was expecting more of a stack-like dispatch behavior.
