### ISSUE TITLE
Make a pure Java8 example of using Spek

### ISSUE THREAD

**Issue by paul-hammant** [JetBrains/spek#405]
https://github.com/mscharhag/oleaster and http://cuppa.forgerock.org are Mocha/Jasmine inspired frameworks for Java8. I'm sure Spek is usable from Java8 (albeit not as elegant).  Any chance of making an example project (Maven or Gradle)?

**Comment by raniejade** [comment]
Wouldn't count on this to happen. Spek is not designed to be used from Java so it does not make sense to create examples for it.
