### ISSUE TITLE
Remove Action in favour of Group and Test combination

### ISSUE THREAD

**Issue by arturdryomov** [JetBrains/spek#422]
### Issue

At this point there are two ways to do the same thing — using `action` and `group`.

```kotlin
group("service") {
    
    beforeEachTest { 
        service.start()
    }
    
    test("it calls backend") {
        verify(backend).call()
    }
}
```
```kotlin
action("service") {

    service.start()
    
    test("it calls backend") {
        verify(backend).call()
    }
}
```
The difference is obvious — it is possible to omit `beforeEachTest` when using `action`. At the same time `action` cannot be nested. Before 2.0 this could lead to nasty bugs related to putting nested groups into `action` which were essentially ignored. Fortunately enough `@DslMarker` magic solved this for us. It leaves a couple of open issues though.

#### Alien Concept

Judging from experience — not a lot of people recognize what the difference is and when to use `group` and when to use `action`. And it is actually understandable. People coming from JUnit have to live with two completely new concepts (`action` and `group`) because the previous experience introduced them only to `test`. People coming from other languages do not get it as well — as far as I know RSpec from Ruby, Mamba from Python and Quick from Swift do not have `action` concept at all. The concept of `action` becomes kind of alien to them.

BTW — at current projects I work on we just ban `action` altogether to avoid bugs (2.0 is not released yet). And even 2.0 would not solve things like #388.

#### Scale

At the same time `action` does not scale well. I’ve encountered a lot of situations when product changes extend the behaviour. I. e. _click shows content_ becomes _click shows content and another click shows screen_. Fortunately we have nesting but `action` in such case needs to be migrated to `group` anyway since `action` does not support nesting.

#### Syntax

Since we are leaning to have two styles in 2.0 it becomes not quite obvious what is `action` and what is `group`.

* Specification — `describe` (`group`) + `context` (`group`) + `it` (`test`).
* Gherkin — `given` (`group`) + `when` (`group`) + `then` (`test`) + `and` (`test`).

There is basically no room for `action` at this point.

#### Tech

Internally having both `group` and `action` brings some complexity. I would not say it makes things drastically worse but it is something to have to live with.

---

CC @raniejade @hhariri @artem-zinnatullin

**Comment by raniejade** [comment]
I'm up for this now :) Simplifies a lot of things in the runtime and the docs. Another problem is that `group` and `test` have before/after fixtures but `action` does not, which may have caused some confusion.

**Comment by dave08** [comment]
But doesn't before and after just add clutter to the tests? When nesting is not required, it would maybe be nice to have such an option...

**Comment by arturdryomov** [comment]
@dave08, I might be wrong from the technical perspective but since `action` is dynamic it brings a lot of nuances. @raniejade can elaborate on that. Stable, understandable and explicit behaviour is worth an extra lambda (at least in my opinion).

**Comment by arturdryomov** [comment]
@vanniktech, can you please give your opinion? Looks like you’ve monitored Spek for some time.

**Comment by artem-zinnatullin** [comment]
@dave08 `action` still requires a separate lambda to have something run before/after *each* test, the only case when it saves you a lambda is an analog of `@BeforeClass` from JUnit when you execute something once before running several tests

I really like the point about scaling @ming13 makes, other points are great too

👍

**Comment by dave08** [comment]
So in gherkin, you'd have `given { beforeEachTest { .... } }` all over the place no? I agree about the confusion, I myself recently had such problems, I'm just wondering if the most common use case is to have beforeEachTest (as is currently the default memoized CachingMode), then would there be a way to not have to riddle test code with it all over. Also, you'd need to memoize more or use `var`s all over to change context  (like in junit :disappointed:)...

**Comment by arturdryomov** [comment]
JFYI — I’ve walked through issues we had before and `action` definitely brings a lot of confusion, especially because of nesting, execution order and general difference from `group`.

**Comment by dave08** [comment]
You all have very good points, I'm just wondering if there isn't a way to avoid the beforeEachTest... even in junit, you only have it at the top of the class. Here, even just to run the SUT you have to have it every time... try adding mocking frameworks to the mix, and you've got a lot of boilerplate. I admit, that I don't fully understand theninner workings enough to be commenting, I'm only coming froma user's point of view. Also, part of my concerns will probably be covered by the new memoized, but I'm just asking if there's any alternatives... I could be wrong, but as far as I understand, Gherkin could get pretty messy with this,  since what do you put in Given and When if there is no beforeEachTest? The mocking framework I use doesn't allow overriding mocked objects, and I have a whole bunch of them that one depends on the other... and groups are evaluated at discovery stage, one would expect that given-when-then is evaluated sequentially...?

**Comment by arturdryomov** [comment]
@dave08, your concerns are totally valid and we do not dismiss them.

At projects I’m working on usually we have something like this.

```kotlin
val env by memoized { Environment() }

context("click button") {

    perform {
        env.view.button.click()
    }

    it("requests permission") {
        verify(env.permissionService).request(Permission)
    }

    context("permission granted") {

        perform {
            env.permissionService.simulateRequestResult(Permission, PermissionStatus.Granted)
        }

        it("opens screen") {
            verify(env.view).openScreen()
        }
    }

    context("permission blocked") {

        perform {
            env.permissionService.simulateRequestResult(Permission, PermissionStatus.Blocked)
        }

        it("shows dialog") {
            verify(env.view).showPermissionBlockedDialog()
        }
    }
}
```

`perform` is an alias for `beforeEachTest`. You can replace `context` with `given` and `when`, `it` with `then`. Looks pretty organic to me. And it follows the general Arrange-Act-Assert pattern.

Yes, JUnit has `beforeEachTest` only on top of the suite, but let’s admit it — you do your `beforeEachTest` in test body. Most likely you just separate them via the empty line and Spek has a dedicated structure for that.

**Comment by raniejade** [comment]
Just FYI the Gherkin DSL looks like:
```kotlin
Feature("some feature") {
   Scenario("some scenario") {
      Given("some condition") { .. }
      When("some action") { .. }
      Then("some result") { ... }
   }
}
```

Above is equivalent to:
```kotlin
group("Feature: some feature") {
   action("Scenario: some scenario") {
      test("Given: some condition") { .. }
      test("When: some action") { .. }
      test("Then: some result") { ... }
   }
}
```

Now if we proceed with dropping `action`, then `Scenario` will be aliased to `group`. We also need to make guarantees to the execution order to support the Gherkin style.

**Comment by vanniktech** [comment]
> Looks like you’ve monitored Spek for some time.

Indeed I have. And I'm really eager now that the SNAPSHOT upload mechanism have been merged.

I'm also in favor of simplifying the API and it certainly looks like we don't need `action`. Let's just nuke it.

**Comment by dave08** [comment]
@ming13 Do you have a cleaner way of dealing with this with the current proposition, or is this the way to do it?
```
group("service") {
    var result: Result = null
    beforeEachTest { 
        result = service.getResult()
    }
    
    test("it gets right result") {
        result!!.toBe(Result(3))
    }
}
```

**Comment by arturdryomov** [comment]
@dave08, `memoized` might help you with that. Actually it is a classic RSpec discussion around [fields vs. `let`](http://www.betterspecs.org/#let).

```kotlin
class ServiceSpec : Spek({
    val service by memoized { Service() }

    group("service") {
        val result by memoized { service.result() }

        test("it gets right result") {
            assertThat(result).isEqualTo(42)
        }
    }
})
```

**Comment by artem-zinnatullin** [comment]
@raniejade for Gherkin we not only need guarantees for execution order (which is relatively easy to do), but also `memoized` to cleanup after end of all `test` in a `group` and this one is more tricky to bake into runtime

**Comment by artem-zinnatullin** [comment]
Although we can force `CachingMode.GROUP` for `memoized` in Gherkin, but that's kinda hacky

**Comment by artem-zinnatullin** [comment]
So, as @raniejade pointed, removing `action` requires Gherkin to be adapted for this change.

I've talked with @ming13 for few hours about that after I've implemented PR #430 which removes `action` but keeps Gherkin working in flat style.

@ming13 suggested that Gherkin can work without action just by using nested style like:

```kotlin
Scenario("scenario 1") {
   Given("some condition") {
      
     When("something happens") {
        
       Then("some result") {

       }
     }    
   }
}
```

That's how iOS team writes tests at Juno where @ming13 works.

So as you can see it's pretty conflicting with current Gherking implementation.

---

That made us rethink Gherkin. Gherkin seems to be a product of Cucumber, later adopted in other test frameworks. 

Original Gherkin design implies flat-style, so if we want to keep it we probably need to keep it flat to avoid confusion for Gherkin users.

However, no one asked us to add Gherkin 😸 Right now, Gherkin in Spek seems to be a side-effect of `given` that existed in standard DSL in 1.x.

Thus said, we can actually remove Gherkin from Spek itself — PR #431 and allow users to make an extension to Spek that will provide Gherkin style, see PR #430 for implementation details.

@raniejade @vanniktech what do you think?

**Comment by vanniktech** [comment]
Lets nuke Gherkin then. The less the better. Keeps the API simple and focused.

**Comment by raniejade** [comment]
I would really like to keep the Gherkin style, and yes it's a side-effect of the `give-on-it` style on `1.x` which I know a lot of people still uses. If dropping action results in making implementing Gherkin a lot harder (I don't like forcing `CachingMode.GROUP`), then let's not drop it at all.

We could go with @ming13's suggestion, but maybe just drop `Feature/Scenario` synonyms and go with `Given - When - Then`. Having `Scenario` implies a flat structure. Maybe just reference it in docs as `Gherkin-like`.

**Comment by artem-zinnatullin** [comment]
@raniejade PR #430 keeps Gherkin flat without `action` and statically disables overloads of `memoized` with custom `cacheMode` by using `@Deprecated(level = ERROR)`, there is not much point in `TEST` caching mode for flat-styled Gherkin as far as I see

But that's implementation details.

As far as I know we don't have users who asked us to add Gherkin in the first place, so maybe we can roll out 2.x without it and if we have enough userbase asking for it — add it in a most appropriate way?

**Comment by arturdryomov** [comment]
@raniejade, @artem-zinnatullin, I’m in the middle ground between you two. But I like @raniejade suggestion a bit more. Let’s remove `Action`, remove `Feature` and `Scenario` and have Gherkin-like DSL using `Given`, `When` and `Then`. We can discuss further progress later since it is a separate topic aside from `Action` which was caught by crossfire. Let’s move step by step.

**Comment by raniejade** [comment]
I guess moving forward we could re-implement the Gherkin style as what @ming13 suggested, then we can proceed dropping `action`.
