### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by vanniktech** [JetBrains/spek#425]
I like that there's been some progress in the last few days. Snapshots also seem to be something that will start to work soon.

Can we get out a really early alpha release that will still super likely break and corrupt everything?

Just want to get my hands dirty and play around with it and have a stable source and not depend on SNAPSHOTS.

**Comment by arturdryomov** [comment]
I think you can just take snapshots and go with it. They [seem to be available](http://oss.jfrog.org/oss-snapshot-local/org/spekframework/spek2/) at this point.

* Repo — `http://oss.jfrog.org/artifactory/oss-snapshot-local`
* Artifacts for JVM:
    * Runtime — `org.spekframework.spek2:spek-runtime-jvm:2.0.0-SNAPSHOT`
    * JUnit 5 Runner — `org.spekframework.spek2:spek-runner-junit5:2.0.0-SNAPSHOT`
    * DSL — `org.spekframework.spek2:spek-dsl-jvm:2.0.0-SNAPSHOT`

I think you will be forced to use either `@Testable` or `@RunWith(JUnitPlatform::class)` since IJ plugin is not published yet.

Let me know how it goes. I’m curious myself but haven’t tried it yet at all.

**Comment by ailjushkin** [comment]
@ming13 hi, could you please tell me what should I set up in my pom.xml to be able to compile my project using the kotlin-reflect 1.2.x?

The latest version of spek-api seems to be using the older version of the kotlin-reflect which is apparently 1.0.6.

This problem becomes into compilation errors.

https://mvnrepository.com/artifact/org.jetbrains.spek/spek-api

I have to use the official maven repo only.

**Comment by arturdryomov** [comment]
@ailjushkin, 2.0 snapshots available only on jcenter.

**Comment by vanniktech** [comment]
Can we please sync them to mavenCentral?

**Comment by ailjushkin** [comment]
That would be great if you could sync it with the central repository. 

But the minimal task is to update dependencies: I only need to have kotlin-reflection 1.2 as a dependency for the 1.x version.

**Comment by vanniktech** [comment]
Was thinking of this again and to encourage everyone of using Spek it would be really beneficial if we had alpha / rc / beta releases or however you want to call them.

**Comment by ailjushkin** [comment]
@vanniktech sounds perfect, thank you guys for your great work

**Comment by raniejade** [comment]
First alpha is already out: https://github.com/spekframework/spek/releases/tag/2.0.0-alpha.1

**Comment by vanniktech** [comment]
Sweet. Took 10 minutes to migrate one of my pet projects. Awesome!
