### ISSUE TITLE
spek kotlin and maven

### ISSUE THREAD

**Issue by nykykof** [JetBrains/spek#437]
Hello,

I have a little web project with pure kotlin ( ktor framework). For the unit tests i decided to use spek in oder to stay in the same way of using pure kotlin in my project. The problem i am facing is that i am using spek in a maven project and for my CI purpose i want to be able to run "mvn test" in the console but i can't ( it does anything like i have not any test in th project).
I tried all the tutorials i found on the web the it doesn't work.

If somone could show me an example of how to get it work, i'll be very happy :).
Thanks

**Comment by kkurczewski** [comment]
I'm also unable to run Spek with Maven, tried example at: https://github.com/spekframework/spek-maven-sample but it throws ugly exception.

I fiddled with dependencies versions, directories and test names and I managed to run maven without errors but no test are executed.

**Comment by raniejade** [comment]
Can you guys check #490? Added a sample maven build there.

**Comment by kkurczewski** [comment]
@raniejade you maven sample is good :+1:

**Comment by raniejade** [comment]
Awesome, thanks for checking!
