### ISSUE TITLE
Spek doesn't write <error> tags in junit test report files when exception is thrown in the on{ } block

### ISSUE THREAD

**Issue by AnkBurov** [JetBrains/spek#445]
Hi. I've faced with some strange behavior of the Spek (tested with 1.1.5), not sure if this is a bug but it does look like it.

During test execution if exception is thrown in blocks given{ } or it{ } everything is ok - `test-results/junit-platform/TEST-spek.xml` file contains expected tag `<error message="!!!!!" type="java.lang.IllegalArgumentException">`

but when exception is thrown in the on{ } block, file `test-results/junit-platform/TEST-spek.xml` contains no `<error>` tags and has no indication that test has failed. It leads to behavior that CI servers cannot determine which test had failed.

How to reproduce:
Add in the class ContextGivenOnSpec (in this project) throw any exception line in the on{ } block:
```kotlin
class ContextGivenOnSpec : Spek({
    given("a calculator") {
        val calculator = Calculator()
        var result: Int

        on("addition") {
            throw IllegalArgumentException("!!!!!")
            result = calculator.add(2, 4)

            it("should return the result of adding the first number to the second number") {
                assertEquals(6, result)
            }
        }
    }
})
```
run it by gradle test and check generated TEST-spek.xml file for any `<error>` tags

**Comment by AnkBurov** [comment]
@raniejade seriously?

**Comment by raniejade** [comment]
`on` was dropped from  `2.x`, making this issue outdated. Sorry for not mentioning a reason.

**Comment by AnkBurov** [comment]
Ok, thank you. Have a nice day then.
