### ISSUE TITLE
Some typos in the migration guide? And: example usage

### ISSUE THREAD

**Issue by PHPirates** [JetBrains/spek#448]
Thanks for the [migration guide](https://spekframework.org/migration/), it's very useful!

Some things had to be changed for me though (possibly also in [setting up](https://spekframework.org/setup-jvm/) or other places): `import org.spekframework.spek2.specification.describe` should be I think `import org.spekframework.spek2.style.specification.describe` because the first is not found.
Same for `import org.spekframework.spek2.gherkin.Feature` and `import org.spekframework.spek2.style.gherkin.Feature`.

And for the Gradle dependencies, I think `testCompile 'org.spekframework.spek2:spek-junit5-runner:2.0.0-alpha.1'` should be changed to `    testCompile 'org.spekframework.spek2:spek-runner-junit5:2.0.0-alpha.1'` because the former doesn't exist for me.

**Side question about the example in the migration guide:**

I think would be very helpful for unexperienced users to elaborate the example a tiny bit more.

From the migration guide it was not entirely clear to me how it's supposed to be used. In the following example, which is how I thought it would go, the use of `var emptySize = -42` bothers me because in the previous way that wasn't necessary. But now in the Then scope you cannot use values from the When scope, which was possible in Spek 1. Is this the right way?
At the moment I threw everything in the Then clause because I don't like magic values and initialising with nulls.

```kotlin
import org.spekframework.spek2.style.gherkin.Feature
import org.spekframework.spek2.Spek
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.fail

object KotlinJUnitSpekTest: Spek({
    Feature("Testing list size") {
        Scenario("An empty list is made") {

            val empty= emptyList<Nothing>()
            var emptySize= -42

            Given("The empty list is empty (precondition)") {
                empty.isEmpty()
            }
            When("Getting the list size") {
                emptySize = empty.size
            }
            Then("It should be empty") {
                assertEquals(emptySize, 0)
            }
        }
    }
})
```

Such an example would be very helpful in the Setting Up page as well, as that's where I would look as a first time user.

PS As far as I know I didn't need the new IntelliJ plugin? I have 0.5.4, maybe that's already the new one, idk.

**Comment by PHPirates** [comment]
Also, in order to run all my tests and not only my spek tests I had to change
```
useJUnitPlatform {
    includeEngines 'spek2'
}
```
to
```
useJUnitPlatform()
```
like it was before. No need to `includeEngines`. But maybe this should be a separate issue.

**Comment by raniejade** [comment]
@PHPirates thanks for the report! The migration guide really needs some ❤️ , was rushing into doing the first alpha. Will definitely work on it.

**Comment by raniejade** [comment]
New docs at https://spekframework.org/
