### ISSUE TITLE
Cannot use junit5 @ExtendWith with Spek

### ISSUE THREAD

**Issue by micHar** [JetBrains/spek#449]
Hey, not sure if it's an issue at all, maybe a misconception on my side. I have a simple test class

```
@ExtendWith(MyExtension::class)
class MyTest : Spek({
    describe("my something") {
        on("whatever") {
            it("log something") {
                  System.out.println("abc")
            }
        }
    }
}){

    @Test
    fun whatever(){
        System.out.println("def")
    }

}
```

And an extension class:

```
class MyExtension : BeforeEachCallback, AfterEachCallback {

    override fun beforeEach(context: ExtensionContext?) {
        System.out.println("beforeEach")
    }

    override fun afterEach(context: ExtensionContext?) {
        System.out.println("afterEach")
    }

}
```

What I get is:
```
beforeEach
def
afterEach
abc
```

So the extension is only called for the traditional `whatever()` test, the Spek tests are ignored. Of course I could add Spek's own `beforeTest` closure, but the extension mechanism seems like a good idea for my case (providing trampoline schedulers for rxjava calls). Any ideas why this doesn't work?

**Comment by raniejade** [comment]
`@ExtendWith` is JUnit Jupiter API, it's a different test framework . Spek implements a JUnit Platform `TestEngine` and so does JUnit Jupiter.
