### ISSUE TITLE
Tests not executing: OpenJDK11

### ISSUE THREAD

**Issue by plannigan** [JetBrains/spek#451]
I recently updated one of my machines to Ubuntu 18.04 (with OpenJDK11) and attempted to run the [spek-multiplatform-example](https://github.com/spekframework/spek-multiplatform-example) since the alpha was just released. However, the test report shows that none were executed. I tried testing the project on two other systems with OpenJDK8/Ubuntu 16.04 and the tests are executed as expected. 

I included debug output from "clean test" builds for each. The test classes are listed for OpenJDK11 (line 1997), but there are no log lines indicating the results of the test cases. Whereas the OpenJDK8 log shows the test results just after the test classes (line 1973). 

[openjdk8-ubuntu16.04.txt](https://github.com/spekframework/spek/files/2185528/openjdk8-ubuntu16.04.txt)
[openjdk11-ubuntu18.04.txt](https://github.com/spekframework/spek/files/2185529/openjdk11-ubuntu18.04.txt)

**Comment by plannigan** [comment]
I have now run the same build using OpenJDK8 on the Ubuntu 18.04 machine and the tests ran successfully. So it seems like the issue is a difference between Java 8 and Java 11.

[openjdk8-ubuntu18.04.txt](https://github.com/spekframework/spek/files/2186371/openjdk8-ubuntu18.04.txt)

**Comment by raniejade** [comment]
The main repo can't even compile against JDK10, currently blocked by https://github.com/JetBrains/gradle-intellij-plugin/issues/298.

**Comment by raniejade** [comment]
Fixed in #460
