### ISSUE TITLE
AS Plugin for Spek 2.0.0?

### ISSUE THREAD

**Issue by fbcbl** [JetBrains/spek#452]
Hello,

This new Spek version will require a new plugin? If so, any expectations on when it will be available? 

Thanks.

**Comment by raniejade** [comment]
@fabiocarballo It's already out https://plugins.jetbrains.com/plugin/10915-spek-framework, but you need to add a repository that points to `https://plugins.jetbrains.com/plugins/dev/10915`.

![spek2-plugin-repo](https://user-images.githubusercontent.com/1041919/42638148-43e14266-8630-11e8-9a52-c8a4e97342cb.PNG)

I'll include this in the release notes for `2.0.0-alpha.2`

**Comment by fbcbl** [comment]
amazing. thanks :)

**Comment by jgandert** [comment]
@raniejade Will this always be necessary, or will it end up in the main repository at some point?
