### ISSUE TITLE
How can I inherit other classes with Spek

### ISSUE THREAD

**Issue by harry-uglow** [JetBrains/spek#453]
Hi there,

I am trying to use Akka's Route TestKit which requires inheritance of an abstract class. I cannot do this:

    class TestKitExampleTest : JUnitRouteTest(), Spek({

      describe("My routes") {
        val appRoute = testRoute(MyAppService().createRoute())

        it("calculator add") {
          // test happy path
          appRoute.run(HttpRequest.GET("/calculator/add?x=4.2&y=2.3"))
            .assertStatusCode(200)
            .assertEntity("x + y = 6.5")
        }
      }
    })

as that inherits two classes, and this does not work either: 

    class TestKitExampleTest : Spek({

      describe("My routes") {
        val appRoute = testRoute(MyAppService().createRoute())

        it("calculator add") {
          // test happy path
          appRoute.run(HttpRequest.GET("/calculator/add?x=4.2&y=2.3"))
            .assertStatusCode(200)
            .assertEntity("x + y = 6.5")
        }
      }
    }) {
      companion object : JUnitRouteTest()
    }

I receive a runtime error, `java.lang.IllegalStateException: Unknown factory null
    at akka.http.impl.util.package$.actorSystem(package.scala:34)`

I need to inherit this class to use `testRoute`, how do I get this to work? Thanks in advance.

**Comment by raniejade** [comment]
Looks like `JUnitRouteTest` is using a rule to bootstrap akka, see https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/JUnitRouteTest.scala.

You can use Spek's  `LifecycleListener` to do the same thing.

```kotlin
class SpekRouteBootstrapper: LifecycleListener, RouteTest() {
   override fun beforeExecuteTest(test: TestScope) {
      // initialize, do the same as `JUnitRouteTest`
   }

  override fun afterExecuteTest(test: TestScope) {
    // cleanup
  }
}
```

Then on your test you can do:

```kotlin
object TestKitExampleTest: Spek({
  val bootstrapper = SpekRouteBootstrapper()
  registerListener(bootstrapper)

  describe("My routes") {
    val appRoute by memoized {
      bootstrapper.testRoute(MyAppService().createRoute())
    }

    it("calculator add") {
      // test happy path
      appRoute.run(HttpRequest.GET("/calculator/add?x=4.2&y=2.3"))
        .assertStatusCode(200)
        .assertEntity("x + y = 6.5");
    }
  }
})
```

**Comment by harry-uglow** [comment]
Thank you, this worked!

Full code for time travellers:

    import akka.http.javadsl.testkit.JUnitRouteTest
    import org.jetbrains.spek.api.lifecycle.LifecycleListener
    import org.jetbrains.spek.api.lifecycle.TestScope

    class SpekRouteBootstrapper: LifecycleListener, JUnitRouteTest() {
      override fun beforeExecuteTest(test: TestScope) {
        systemResource().before()
      }

      override fun afterExecuteTest(test: TestScope) {
        systemResource().after()
      }
    }

`TestKitExampleTest` remains identical to @raniejade's comment. 

Edit: Greatly simplified. Was initially a bit confused.
