### ISSUE TITLE
Spek2 - What is the repository ?

### ISSUE THREAD

**Issue by davzucky** [JetBrains/spek#461]
Hi,

I'm really interesting of migrating my test packs to Spek2 using the new gherkin language. However following the instruction from the website https://spekframework.org/setup-jvm/ I cannot figure out which repository I need to reference. Looking around I have not been able to figure out the address.

Could you let me know ? I will be happy to update the documentation after

**Comment by raniejade** [comment]
Wow, silly me - I thought I already added it to the docs. `https://dl.bintray.com/spekframework/spek-dev/` is the maven repo url.

**Comment by davzucky** [comment]
That work. Thank you for the fast reply

**Comment by snowe2010** [comment]
This url still seems to be missing from the gradle section of the docs. It took me forever to find this thread just to go back and find that it was in the maven section of the page.
