### ISSUE TITLE
testRuntimeOnly dependencies not being added to the classpath during execution

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#474]
Only android modules are affected.

**Comment by raniejade** [comment]
@artem-zinnatullin is `testRuntimeOnly` usually used in android projects? Looking at a android studio's project structure dialog implies it should not be used:

![android-project](https://user-images.githubusercontent.com/1041919/44725336-619c5400-ab18-11e8-8643-deeaa8b25832.PNG)

I'm inclined to prefer using `testImplementation` instead.

**Comment by vanniktech** [comment]
Yeah testImplementation ist the way to go.

**Comment by raniejade** [comment]
I'll update the docs to use `testImplementation` instead.

**Comment by fawaad** [comment]
After trying this out myself, it appears that the doc still mentions `testRuntimeOnly` instead of `testImplementation`. I had to modify both my imports to the following to get this to work:

```// Spek testing
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:2.0.5"
    testImplementation "org.spekframework.spek2:spek-runner-junit5:2.0.5"
    testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
```

Is that still necessary? Should the docs be updated?
