### ISSUE TITLE
Support android project tests in Intellij Idea

### ISSUE THREAD

**Issue by DrewCarlson** [JetBrains/spek#488]
The tests in the android sample project can be run in Android Studio using the Spek Framework plugin but no tests are found when using the same run configuration in Intellij Idea.  I assume this is expected because of a technical distinction between the IDEs.  Is this something that can be supported?

**Comment by raniejade** [comment]
Unfortunately, this unlikely to be supported as IJ doesn't have the necessary infrastructure to support android projects. Why not just use Android Studio?

**Comment by dave08** [comment]
Wow, I spent an hour or two on this problem yesterday, I had no idea that theres only AS support... it might be nice to stress this in the docs, it would save lots of frustration... thanks!

**Comment by raniejade** [comment]
I don't see why we need to add this in the docs, the developer portal for android clearly states that you use android studio.

**Comment by DrewCarlson** [comment]
> Why not just use Android Studio?

I started using Android Studio from v1 and have accumulated a lengthy list of reasons why I do not use it now and will not use it anytime soon.  Some reasons that may provide enough understanding: Idea has an actual release schedule (that adds real value per release), has never caused a run config to break between versions, supports many other platforms languages that I work with on a daily basis.   I don't feel I'm that alone in using Intellij Idea for Android to require fully justifying it over Android Studio here.

A note from the Jetbrains website on Android support in Idea:
> IntelliJ IDEA provides the same coding assistance and integrated toolset for developing Android applications as Android Studio, the official IDE for Android application development from Google.

The most important thing in my eyes is that Android Studio does not have any features (that I know of) which are not supported by Idea.

> the developer portal for android clearly states that you use android studio.

Android Studio is the official IDE for Google's Android but that does not mean it's the only IDE people should use for Android development.

> this unlikely to be supported as IJ doesn't have the necessary infrastructure to support android projects.

I would love any insight you have here so I can investigate further, I'm not familiar enough with the plugin system and core IDE architecture.  If it is at all possible to support this I would be happy to do it myself, otherwise I will survive with running them via gradle.

With all that said, I agree that there should be a note with the Spek plugin documentation that Android projects are not supported by the Idea plugin as that is a perfectly reasonable assumption to make.

**Comment by raniejade** [comment]
> I would love any insight you have here so I can investigate further, I'm not familiar enough with the plugin system and core IDE architecture. If it is at all possible to support this I would be happy to do it myself, otherwise I will survive with running them via gradle.

One major difference between android and non-android projects is build variants. AS is aware of this and can setup the project (dependencies, etc) accordingly.

**Comment by DrewCarlson** [comment]
Are you referring to (for example) information used [here](https://github.com/spekframework/spek/blob/a35c1cdaee373954ff2efca0d5ced6a470dd0775/spek-ide-plugin/android-studio/src/main/kotlin/org/spekframework/android/spek2.kt#L67-L92)?

It is my understanding that everything being used in the Spek Android Studio plugin is from Intellij's android plugin and has nothing to do with Android Studio itself.  Is it possible to package the Spek AS plugin for Intellij (as a separate plugin) if it assumes the Android plugin is installed/active?

**Comment by raniejade** [comment]
> It is my understanding that everything being used in the Spek Android Studio plugin is from Intellij's android plugin and has nothing to do with Android Studio itself. Is it possible to package the Spek AS plugin for Intellij (as a separate plugin) if it assumes the Android plugin is installed/active?

The plugin is being developed by the android team and not being published in jetbrains' plugin repos. AFAIK there's no android plugin that can be used in IJ. AS is a different IDE that is based on IJ. Even though the support is implemented as plugins, it does not mean that it will work with IJ.

**Comment by DrewCarlson** [comment]
Thank you @raniejade for taking the time to communicate with me.

Like I’ve been saying: A default installation of Intellij IDEA (with the bundled Android plugin) understands and can manipulate every facet of an Android project, the same as Android Studio.  I’m sure AS has other IDE layer features and tweaks but it is not special when it comes to Android tooling.  JRebel for Android has worked great in Intellij IDEA for a long time.

While I do not understand the aversion toward this feature and would have appreciated any guidance beforehand, I respect your time and effort commitments to this project.

That said, see [this commit](https://github.com/DrewCarlson/spek/commit/7f0123a32917001d0c90afcc53e0cce95f86bd0d) which contains a version of the `intellij-idea` plugin that supports standard and Android based projects in Intellij IDEA.  The necessary changes were exceedingly trivial so it could have any number of issues but it works fine for all of my projects and the Android sample.

As I've said I have no knowledge of the IDEA plugin environment so my usefulness ends here, I hope you or another contributor can refine this so others in the future will not struggle as I and @dave08 have.  Thanks again!

**Comment by DrewCarlson** [comment]
[Here](https://www.reddit.com/r/androiddev/comments/9eb4i5/do_i_need_to_install_android_studio_if_i_already/e5o4w6d/) is a well timed explanation of the difference between Intellij IDEA and Android Studio from a member of the AS team.

> Android Studio is really just IntelliJ IDEA + the Android plugin + some tweaks to defaults (some plugins enabled / disabled, assets, etc.)
