### ISSUE TITLE
Ensure execution order for the Gherkin DSL

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#496]
Proposed solution is to add an optional param on the scope methods (`group` and `test`), which defaults to unspecified order. Can be an enum or just a boolean parameter. `Scenario` would set this variable to ensure execution when calling `group`.

see #494 for context

**Comment by davidsowerby** [comment]
This would work, but I cannot think of a situation where unspecified order is valid for test steps?

**Comment by raniejade** [comment]
@davidsowerby Thanks for pointing that out! It's an optional parameter with default value of "unspecified" , but will be set to the appropriate value by `Scenario`.  I've updated the ticket.
