### ISSUE TITLE
Maven import of 1.2.1

### ISSUE THREAD

**Issue by rikbrown** [JetBrains/spek#501]
Hi!

When can we expect to see the 1.2.1 version imported to Maven? The fix in https://github.com/spekframework/spek/pull/463 would be useful.

Thanks!
Rik

**Comment by raniejade** [comment]
@rikbrown `1.2.1` is out, but it's only available in jcenter.

**Comment by raniejade** [comment]
Need to sort out maven central syncing, will do it in a couple of days. ticket: #502
