### ISSUE TITLE
Support Kotlin 1.3 multiplatform model

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#503]
One big question is: Will it require a `1.3` as the minimum version?

**Comment by Tapchicoma** [comment]
New multiplatform plugin is already supported in `1.2.71`, though only for jvm and js targets. Proper native target support is only available in `1.3`.

**Comment by raniejade** [comment]
That's interesting, thanks @Tapchicoma!

**Comment by Lakedaemon** [comment]
Could we have a sample for the new multiplatform plugin ?
I tried to set spek2 up but couldn't with 
plugins {
    id 'kotlin-multiplatform' version '1.3.11'
}

**Comment by raniejade** [comment]
Will take a look, thanks!

**Comment by Lakedaemon** [comment]
I tried doing like in the commit implementing new multiplatform surpport
https://github.com/spekframework/spek/commit/c7f72fe28f14f670e41e6ea605305c5cb3e46130
But my intellij idea is unable to find org.spekframework.spek2:spek-dsl-metadata:$spek_version 
for ext.spek_version = '2.0.0-rc.1.181+20190113T062549Z'

It looks like the necessary artifacts are missing there : 
https://dl.bintray.com/spekframework/spek-dev/org/spekframework/spek2/spek-dsl-metadata/

**Comment by Lakedaemon** [comment]
Thanks for your work, btw. :)

**Comment by raniejade** [comment]
That's only a placeholder, the current dev version is `2.0.0-rc.1.180+b8533a4`. You can check out the project README for the current stable and dev versions.

**Comment by raniejade** [comment]
Fixed in #565.

**Comment by Lakedaemon** [comment]
Thanks, with that last precision, it worked for me. Many thanks for this. :)

**Comment by Lakedaemon** [comment]
Could you please provide the artifacts for 
https://dl.bintray.com/spekframework/spek-dev/org/spekframework/spek2/spek-dsl-jvm/

bintray only has 
2.0.0-alpha.1/
2.0.0-alpha.2/
maven-metadata.xml

and also for 
https://dl.bintray.com/spekframework/spek-dev/org/spekframework/spek2/spek-runtime-jvm/
2.0.0-alpha.1/
2.0.0-alpha.2/
maven-metadata.xml

which looks like a dependency for 
org.spekframework.spek2:spek-runner-junit5:2.0.0-rc.1.180+b8533a4
