### ISSUE TITLE
Test framework quit unexpectedly

### ISSUE THREAD

**Issue by dinuchiriac** [JetBrains/spek#505]
I really like the Spek framework format, however, I can't get it working. I'm getting `Test framework quit unexpectedly` when running the test, here is my setup:

```
buildscript {

    ext.kotlin_version = '1.2.70'
    ext.spek_version = '2.0.0-rc.1'

    repositories {
        google()
        jcenter { url "http://jcenter.bintray.com/"}
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.2.0.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: "de.mannodermaus.android-junit5"


android {
    compileSdkVersion 27
    buildToolsVersion "28.0.2"


    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets.each {
        it.java.srcDirs += "src/$it.name/kotlin"
    }

    testOptions {
        junitPlatform {
            filters {
                engines {
                    include 'spek2'
                }
            }
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.+'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:1.8.8"

    // spek
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spek_version"
    testImplementation "org.spekframework.spek2:spek-runner-junit5:$spek_version"
//

    // spek requires kotlin-reflect, omit when already in classpath
    testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
}
```
Also, I'm using Spek Plugin for Android studio `Version: 2.0.0-alpha.1-IJ2018.1`
Does anyone have any ideas what's going on here?

**Comment by raniejade** [comment]
Looks like you've got the plugin for the mainline IJ, can you try downloading the correct version here: https://plugins.jetbrains.com/plugin/10915-spek-framework?

**Comment by dinuchiriac** [comment]
Plugin `Spek Framework` is incompatible with this installation. What is the latest Android Studio supported? I'm running: 
Android Studio 3.2
Build #AI-181.5540.7.32.5014246, built on September 17, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

**Comment by raniejade** [comment]
I see, the plugin is for the beta build for 3.2. Currently updating my AS, will publish the correct version soon.

**Comment by raniejade** [comment]
In the meantime, @dinuchiriac can you try reinstalling the plugin within AS and see if you get the correct version?

**Comment by dinuchiriac** [comment]
Still getting the same alpha version `Version: 2.0.0-alpha.1-IJ2018.1`.

**Comment by raniejade** [comment]
Oops sorry, I think you still have the dev channel in your plugin repository list - can you try removing it and refresh the plugin page?

**Comment by dinuchiriac** [comment]
ahh, right, I removed it and got the correct version now.

**Comment by dinuchiriac** [comment]
Tests are running fine now, thank you @raniejade 
Looking at the spekframework website, the plugin repository link is still on dev branch:
https://plugins.jetbrains.com/plugins/dev/10915
from https://spekframework.org/setup-jvm/

**Comment by raniejade** [comment]
@dinuchiriac thanks for pointing that out, see #506 for the fix.
