### ISSUE TITLE
Spek plugin 2.0.0-rc.1.145 incompatable with Android Studio 3.2 stable release

### ISSUE THREAD

**Issue by audkar** [JetBrains/spek#509]
Latest Spek plugin version `2.0.0-rc.1.145` was released with compatibility restrictions `181.5281—181.5281.*` for Android Studio 3.2. However latest stable AS version is `181.5540.*`

Because of this plugin for IJ is pulled instead of AS3.2

**Comment by raniejade** [comment]
Thanks for the report!
