### ISSUE TITLE
Run configurations get hosed up and fail to work

### ISSUE THREAD

**Issue by codeslubber** [JetBrains/spek#51]
Somehow it is possible to end up with run configurations that throw up this error:

```
java.lang.NoSuchMethodError: kotlin.properties.Delegates.lazy(Lkotlin/jvm/functions/Function0;)Lkotlin/properties/ReadOnlyProperty;
```

This sure looks like a classloader problem. Was able to slink out of this a few times by deleting them then recreating them.

**Comment by hhariri** [comment]
Is there anything to reproduce this?

**Comment by codeslubber** [comment]
We were able to reproduce a number of times. It is possible that Kobalt played a role in this. We noticed that it appeared twice in the modules. Was going to talk to cedric about it. Main reason I made an issue here is it does seem that the runner is the problem. But maybe one of the kobalt jars had an older JUnit?

**Comment by madhead** [comment]
Had the same issue running `0.180` with latest Kotlin (they've removed `Delegates.lazy` in regards to `lazy{}`). Updating to latest Spek version resolved this.

**Comment by codeslubber** [comment]
Thanks @madhead ! Will give this a try..
