### ISSUE TITLE
IntelliJ plugin not compatible with IDEA 2018.3 EAP

### ISSUE THREAD

**Issue by michal-mally** [JetBrains/spek#516]
Spek plugin (https://plugins.jetbrains.com/plugin/10915-spek-framework) is not compatible with IDEA >= 183 (IDEA 2018.3 EAP). Are there any plans to support new IDEA? It is extremely hard not to be able to run Spek2 tests from IDE.

**Comment by raniejade** [comment]
Thanks for reporting! Currently downloading the EAP build, it will be great if you could add more info about the problem.

**Comment by michal-mally** [comment]
There isn't much more really. IntelliJ IDEA just says the "plugin is incompatible with this version" and refuses to turn it on.

**Comment by raniejade** [comment]
Ahh right, just need to publish a new build with the correct version.

**Comment by raniejade** [comment]
Had a go with it, looks like I also need to bump kotlin to `1.2.71`. Also need to backport that change to `1.x`, so not a quick fix as I previously thought.

**Comment by raniejade** [comment]
Just an update: got a branch for it locally but it's failing to build for some reason (and I don't know why) 🤷‍♂️

**Comment by raniejade** [comment]
Found the issue, Jetbrains decided to break their API in `2018.3` 😞 .

**Comment by raniejade** [comment]
Because of the breakage I'm doing a big refactor to the plugin, since we still want to support minimum `IJ2018.1` (Android Studio) and I want to avoid duplicating code between the plugins.
