### ISSUE TITLE
Test framework quit unexpectedly when running feature or scenario

### ISSUE THREAD

**Issue by NitroG42** [JetBrains/spek#518]
Using latest 2.0.0-rc.1.150+20181019T091243Z-IJ2018.2 on Intellij 2018.2, I can't run single test using the IDE:
- Running using the "Play" icon on the left of file works only when selecting the whole class inheriting Spek. When I use the icon on a Feature or Scenario block, it throws "Test framework quit unexpectedly" and I see no error message, even in the IDE logs.
- When running tests on the whole file, I can't relaunch failed/selected tests using right click.

I installed the alpha version of the plugin before seeing I can remove the repo and install the rc.1. I uninstalled and reinstalled to be sure.

If it's not a bug but unimplemented feature, maybe it could be added to the plugin section of the documentation? So futures users knows it's normal.
Thank for you great work!

If needed I can probably make a sample reproducing the issue.

**Comment by raniejade** [comment]
@NitroG42 can you try with the latest version of the plugin?

**Comment by NitroG42** [comment]
Hello, as it is not available right now (I was using the latest version from 19 October), I cloned the project and build the latest version of the plugin (I needed it because I updated the kotlin plugin to 1.3 too).
The two issues remains, I can't launch a test by clicking run on a Feature or Scenario in the class, I have to launch all, and it won't allow to rerun a finished test by right clicking on it.

**Comment by NitroG42** [comment]
I tried with the source to debug what's happening but JUnit is a bit above my league it seems.

**Comment by NitroG42** [comment]
I tried with the source to debug what's happening but JUnit is a bit above my league it seems.

**Comment by raniejade** [comment]
Are you using `@RunWith` by any chance?

**Comment by raniejade** [comment]
@NitroG42 can you share repo that help replicate your issue? I've done some testing and it works for me.

**Comment by NitroG42** [comment]
Sorry I forgot to answer, I don't use RunWith, here's the repo:
https://github.com/NitroG42/testspeck

Using "play icon" to run test on any of the two Scenario block will fail. It works on the Feature one, but I can't relaunch one test, I'll do a gif or video if I'm not clear. Thanks!

**Comment by NitroG42** [comment]
Here's the gif of what I get: 
http://recordit.co/kXxLWaNOoi
(I compare with a standard junit test for the right click after running)

**Comment by raniejade** [comment]
Thanks, I'll have a look! re: navigating to tests is not implemented yet - but should be easy after #533 lands.
