### ISSUE TITLE
Unable to run an individual JUnit test when using spek 2 

### ISSUE THREAD

**Issue by cazpr** [JetBrains/spek#519]
I have a project that uses both junit 5 and spek 2 tests, but when I run an individual junit test, the spek tests execute as well, regardless of having the spek framework plugin (2.0.0-rc.1.150) installed or not.

![screenshot 2018-10-23 at 10 10 15](https://user-images.githubusercontent.com/842442/47346531-ade5b980-d6ad-11e8-9843-2006051c8922.png)
![screenshot 2018-10-23 at 10 10 56](https://user-images.githubusercontent.com/842442/47346530-ad4d2300-d6ad-11e8-8ab7-ac2a0f46d421.png)

The project uses gradle 4.10.2 and the configuration looks like this:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71"
    }
}

apply plugin: 'kotlin'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlin:kotlin-reflect"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
    testImplementation 'org.assertj:assertj-core'
  
    testImplementation ('org.spekframework.spek2:spek-dsl-jvm:2.0.0-rc.1')  {
        exclude group: 'org.jetbrains.kotlin'
    }
    testRuntimeOnly ('org.spekframework.spek2:spek-runner-junit5:2.0.0-rc.1') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }
}

test {
    useJUnitPlatform {
        includeEngines 'junit-jupiter', 'spek2'
    }
}
```

I'm using Intellij 2018.2.5 on MacOs Mojave.

**Comment by raniejade** [comment]
Thanks for reporting! Looks like IJ is delegating execution for test to gradle.

**Comment by jordigarcl** [comment]
I'm experiencing this exact issue with Spek 2.0.10 and Gradle 6.4. How come? Doesn't matter if I configure IDEA to run tests using Gradle or IDEA.

```kotlin
testImplementation("org.spekframework.spek2:spek-dsl-jvm:2.0.10")
testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:2.0.10")
...
tasks {
  withType<Test> {
    useJUnitPlatform {
      includeEngines("spek2")
    }
  }
}
```

**Comment by R4md4c** [comment]
I'm facing the same problem as well, using Gradle 6.6 and Spek 2.0.12, along with Android Studio 4.0.1
I'd suggest to reopen this issue.

**Comment by raniejade** [comment]
@R4md4c can you file in a new issue? Also, please include a reproducer.

**Comment by IevgenBizz** [comment]
reopened ticket https://github.com/spekframework/spek/issues/916
