### ISSUE TITLE
Data driven testing in V2

### ISSUE THREAD

**Issue by recumbent** [JetBrains/spek#521]
Question:

Given that `spek-data-driven-extension` has been deprecated for V2 is there a concept around how one might do "data driven" testing?

There are a number of contexts where I find the ability to run the same test over a number of variations of the very similar data extremely useful and hence I'm curious as to the thinking in this context. (I'd like to follow the appropriate patterns in my current work and going forward.)

**Comment by raniejade** [comment]
Preference now is:
```kotlin
listOf(1, 2, 3).forEach { data -> {
  describe("data") { 
     it("should do something") { ... }
  }
}
```
Just plain old kotlin code.
