### ISSUE TITLE
Support for Kotlin 1.3 and IntelliJ 2018.3

### ISSUE THREAD

**Issue by lisandroct** [JetBrains/spek#540]
Issues #523, #525 and #527 are closed but I'm still experiencing issues with Kotlin 1.3.
First of all, I simply can't install the plugin on IntelliJ 2018.3.
And on 2018.1.7 and 2018.2.6, if I use Kotlin 1.3, I get the "nothing here" text and I can't run the tests.

**Comment by raniejade** [comment]
@lisandroct can you try this build out? 
[2.0.0-rc.1.164+e256843-IJ2018.3.zip](https://github.com/spekframework/spek/files/2617999/2.0.0-rc.1.164%2Be256843-IJ2018.3.zip)

**Comment by arturbosch** [comment]
Hey, I can verify that with your build it works again, thank you!

**Comment by raniejade** [comment]
@arturbosch Great! Want to get more feedback before publishing the plugin.

**Comment by lisandroct** [comment]
@raniejade now it's working just fine on 2018.3 and using Kotlin 1.3. :ok_hand:

**Comment by mtrewartha** [comment]
@raniejade this is working great for me with Kotlin 1.3.10 and the following version of Studio:

Android Studio 3.4 Canary 5
Build #AI-183.4284.36.34.5141831, built on November 20, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

I'll keep an eye out for any issues, but thanks for putting that build up!

**Comment by raniejade** [comment]
@miketrewartha build I posted is specific to IJ. AS has a different plugin as it require some special handling. One of the issues is that if you are using the IJ plugin any changes you made to the test won't be picked up when you run the test. I'm not sure if it is still the case for Android Studio 3.4 Canary 5.

**Comment by mtrewartha** [comment]
@raniejade I haven't noticed that, but I have noticed a few times where Studio doesn't seem to recognize tests and show the green run arrows in the gutter. Once I run any test in that file though, the issue corrects itself. Other than that, I haven't noticed anything weird.

**Comment by habutre** [comment]
Working here too.

IntelliJ IDEA 2018.3 (Community Edition)
Build #IC-183.4284.148, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.142-1-MANJARO

**Comment by raniejade** [comment]
New build already published 🎉
