### ISSUE TITLE
Selector (Class/Method) doesn't work (Junit5 + Spek2)

### ISSUE THREAD

**Issue by dymaxionuk** [JetBrains/spek#549]
Context: A (kotlin) project containing both JUnit5 and Spek2 tests, using the Junit5 engine.

When running a JUnit5 test by class, and/or method,  the Spek2 tests are also selected for running (even though from a different package/class/method

Initially filed against IntelliJ IDEA, but the team responded and believe it's an issue with the MethodSelector/ClassSelector since the IDE is correctly passing these params through to JUnit engine as witnessed by the command line str, but Spek2 runner doesn't appear to honour the filter.

https://youtrack.jetbrains.com/issue/IDEA-204183

**Comment by raniejade** [comment]
Related to #519 and fixed in #520. I'm hoping to do a GA release before the 🎄 .
