### ISSUE TITLE
Jump to source from test result in IntelliJ plugin

### ISSUE THREAD

**Issue by jcornaz** [JetBrains/spek#551]
Hello, 

First of all, thank you very much for providing this great testing framework.

When using the Plugin for IntelliJ, it is still not possible to jump to sources by double-clicking on a test result.

That is really annoying when one has to understand the cause of a test failure. In that case the first thing we always want to do, is to read the test, and therefore jump to test source.

Is there any chance to see that feature in the IntelliJ plugin?

**Comment by raniejade** [comment]
Fixed in the `2.x` branch. If you use the latest dev builds and ide plugins, you should be able to jump to source.
