### ISSUE TITLE
Design of Gherkin DSL execution

### ISSUE THREAD

**Issue by cldfzn** [JetBrains/spek#564]
I've been trying to use the Gherkin DSL for spek2. The execution of the test cases in the current build seem unintuitive to me. `Given`, `When`, `Then` and `And` are each treated as separate test cases. Based on how I understand `Given` and `When` to be defined from a test perspective I would think those would essentially be aliases for `beforeEachTest` leaving `Then` and `And` to be the actual test cases executed after the "state of the world" has been set up using the `Given` and `When` blocks.

My current situation has to do with verifying execution of an external entity in an `And` block using a memoized object. Since the object is recreated each test execution the object that was used in the `When` execution no longer exists when the `And` is run causing me to re-execute the `When` code in order for the test execution to succeed.

**Comment by raniejade** [comment]
@cldfzn the default `CachingMode` for `memoized` within a `Feature` is a `GROUP`, while the default is `SCOPE` within a `Scenario`. Can you give a sample test?

```kotlin
Feature("Some Feature") {
  // each scenario will have a unique instance of foo
 // equivalent to val foo by memoized(CachingMode.GROUP) { ... }
  val foo by memoized { ... }

  Scenario("Scenario #1") {
    // instance is shared between Given, When, Then, And.
   // equivalent to val bar by memoized(CachingMode.SCOPE) { ... }
    val bar by memoized  { ... }
     
    ...
  }

  Scenario("Scenario #2") { ... }
}
```

**Comment by cldfzn** [comment]
Figured it out, it had to do with one of my own extension functions that I had migrated that was not using the new defaultCachingMode made available in the LifecycleAware interface. Thanks for the help.
