### ISSUE TITLE
Spek doesn't make the build fail in case of crashes during the discovery phase

### ISSUE THREAD

**Issue by jcornaz** [JetBrains/spek#566]
Please consider this code:

```kotlin
object CrashDuringDiscoveryPhase : Spek({

  doSomethingDuringDiscoveryPhase()

  describe("a failing implementation") {
    it("should fail") {
      fail()
    }
  }
})
```

We would expect the test to fail right?

But if the implementation of `doSomethingDuringDiscoveryPhase` throws an exception: 
```kotlin
fun doSomethingDuringDiscoveryPhase() {
  throw Exception()
}
```

Then that exception will be thrown during the *discovery phase* of Spek. Therefore, Spek won't find any test. It will log the exception, but not make the build fail:
```
> Task :test
Jan 14, 2019 2:29:18 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek2' failed to discover tests
java.lang.Exception
[...]

BUILD SUCCESSFUL in 4s
```

I personally find this behavior quite dangerous. If at some point in time something break the discovery phase of a Specification, then Spek stop testing, and it won't be reported by the CI.

I think that, in case of an exception during the discovery phase, Spek should report an error (not a warning) and the build should fail.

**Comment by raniejade** [comment]
JUnit 5 needs to add some support for this first (see https://github.com/junit-team/junit5/issues/242), before Spek can implement it.

**Comment by jcornaz** [comment]
Couln'd Spek catch the error and create a *fake* failing test like "discovery phase failed"?

For instance in `AbstractRuntime`:
```kotlin
val collector = Collector(classScope, lifecycleManager, fixtures, CachingMode.TEST)

try {
  instance.root.invoke(collector)
} catch (t: Throwable) {
  collector.test("Discovery phase failed") {
    throw t
  }
}
```
(I didn't try it yet, and it is probably not enough. But it shows the idea)

I would definitely prefer having Spek creating a dummy test to make the suite fail, than having the build passing when something wrong happen during the discovery phase.

**Comment by jcornaz** [comment]
@raniejade Do you think that this kind of change could solve the problem: https://github.com/jcornaz/spek/commit/615790fad012d7fe365f833a6d5af5d6fa0bc101?

And it would be consistent to what we find here: https://github.com/spekframework/spek/blob/b8533a47cc5908b2c2b787d464d5db4006a25c2d/spek-runtime/src/commonMain/kotlin/org.spekframework.spek2/runtime/Collectors.kt#L59

The only thing is, I don't know how to try it out, nor how to write a test for it....

**Comment by raniejade** [comment]
@jcornaz Unfortunately, no. Fixtures (beforeGroup) are executed during the execution phase. As I mentioned JUnit 5 needs to support this first before we can do anything within Spek.

**Comment by jcornaz** [comment]
>Fixtures (beforeGroup) are executed during the execution phase

That's the point.  The exception would be caught during the discovery phase and thrown during execution phase

1. **Discovery**: Catch the exception, so the discovery no longer crash, but instead register a `beforeGroup`.
2. **Execution**: Execute `beforeGroup`, throwing the exception caught during discovery and making the test suite fail.

**Comment by raniejade** [comment]
Ahh, I get it now. Instead of adding a fixture, why not do a throw here: https://github.com/spekframework/spek/blob/b8533a47cc5908b2c2b787d464d5db4006a25c2d/spek-runtime/src/commonMain/kotlin/org.spekframework.spek2/runtime/Collectors.kt#L65?

**Comment by jcornaz** [comment]
>Ahh, I get it now. Instead of adding a fixture, why not do a throw here:

The catch block you linked does add a fixture. Here is the full try-catch block you linked from `Collectors`:

```kotlin
try {
    body.invoke(collector)
} catch (e: Throwable) {
    collector.beforeGroup { throw e }
    group.addChild(
        TestScopeImpl(
            idFor("Group Failure"),
            root.path.resolve("Group Failure"),
            root,
            {},
            skip,
            lifecycleManager
        )
    )
}
```

So it does add a fixture `collector.beforeGroup { throw e }`, doesn't it?

Now, the problem, is that this block of code is only evaluated when discovering a *group*. And actually, it already behaves as expected (because of this try-catch) when an exception is thrown during discovery phase of a *group*:
```kotlin
/* The build fail and report the exception (as expected) */
class FailDiscoveryOfGroup: Spek({
  group("test") {
    throw Exception()
  }
})

/* The build pass (unexpected) */
class FailDiscoveryOfRoot: Spek({
  throw Exception()
})
```

Here the problem is when an exception is thrown during discovery phase of the *root*.

I think we have to do something similar to [that](https://github.com/spekframework/spek/blob/b8533a47cc5908b2c2b787d464d5db4006a25c2d/spek-runtime/src/commonMain/kotlin/org.spekframework.spek2/runtime/Collectors.kt#L56-L70), but [there](https://github.com/spekframework/spek/blob/b8533a47cc5908b2c2b787d464d5db4006a25c2d/spek-runtime/src/commonMain/kotlin/org.spekframework.spek2/runtime/SpekRuntime.kt#L27):

**Comment by raniejade** [comment]
My bad, brain is not working :joy:.

Have you tried doing this:

```kotlin
        val classScope =
            GroupScopeImpl(ScopeId(ScopeType.Class, qualifiedName), path, null, Skip.No, lifecycleManager, false)
        val collector = Collector(classScope, lifecycleManager, fixtures, CachingMode.TEST)
        try {
            instance.root.invoke(collector)
        } catch (e: Exception) {
            collector.beforeGroup { throw e }
            classScope.addChild(TestScopeImpl(
                ScopeId(ScopeType.Scope, "Discovery failure"),
                path.resolve("Discovery failure"),
                classScope,
                {},
                Skip.No,
                lifecycleManager
            ))
        }
```

in `AbstractRuntime#resolveSpec`? For the tests, you can look at  [this](https://github.com/spekframework/spek/tree/2.x/spek-runner/junit5/src/test/kotlin) for inspiration.
