### ISSUE TITLE
Spek plugin breaks "run" gutter icon

### ISSUE THREAD

**Issue by mmitic-lotusflare** [JetBrains/spek#569]
With spek plugin enabled, AS 3.3 fails to show any option when clicking "run" gutter icon - both for tests classes, individual tests and even java scratch files. 
![image](https://user-images.githubusercontent.com/25745458/51242280-da913080-197f-11e9-89e4-b9301a53e65e.png) 
![image](https://user-images.githubusercontent.com/25745458/51242288-dfee7b00-197f-11e9-8f62-eae482604b37.png)

IDE restats didn't help but disabling Spek plugin restored functionality
![image](https://user-images.githubusercontent.com/25745458/51242319-f5fc3b80-197f-11e9-834b-3c815a7c1248.png)

I didn't see any errors popup in IDE. Project doesn't even uses Spek framework on this branch (I've tried spek tests on different branch). 
Env: AS 3.3, Kotlin plugin 1.3.11-release-Studio3.3-2, Win10
Do you need some more info, anything else I can do to help?

**Comment by vanniktech** [comment]
I can confirm this too.

**Comment by raniejade** [comment]
Just published a new version, just waiting for it to be accepted by JB. Hopefully that will fix it, if not I'll investigate some more.

**Comment by mmitic-lotusflare** [comment]
That's some quick response 😄

**Comment by mmitic-lotusflare** [comment]
Version `2.0.0-rc.1.180+b8533a4-IJ2018.2` doesn't have the issue. 👍

**Comment by raniejade** [comment]
`2.0.0-rc.1.180+b8533a4-IJ2018.2` is the wrong version :(. Ughh, I think they changed the build numbers in the release. Need to tweak that.

**Comment by raniejade** [comment]
So I think the order of the deploy is important, re-uploaded the AS plugins - hopefully that will fix it.

**Comment by 0mega** [comment]
Installed Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6. 
The updated Spek plugin is: 2.0.0-rc.1.180+b8533a4-IJ2018.2

It fixes the issue reported here.

**Comment by mmitic-lotusflare** [comment]
Latest plugin version on AS is 2.0.0-rc.1.180+b8533a4-Studio3.3

**Comment by boylenssen** [comment]
Why is this closed? The latest version available in Android Studio still breaks the gutter.

I installed an older version: 2.0.0-rc.1.180+b8533a4-Studio3.3 and this resolves the error

**Comment by raniejade** [comment]
> Why is this closed?

Because it's fixed. Kidding aside, I've been testing it with the sample project and everything looks fine. Can you share a project that replicates it?

**Comment by boylenssen** [comment]
Thanks for you very fast response! I was migrating from 1.x to 2.x and had various issues, I think it might have been a side effect. I guess I'm just too new at this and ran into other issues than this ticket concerns, so never mind my comment. 

(for instance, I found out that you need a package name now :) https://stackoverflow.com/questions/54902578/migration-from-spek-1-x-to-spek-2-x-error/54903496#54903496 )

**Comment by raniejade** [comment]
> (for instance, I found out that you need a package name now :) https://stackoverflow.com/questions/54902578/migration-from-spek-1-x-to-spek-2-x-error/54903496#54903496 )

Had a similar report from slack, but I'm pretty sure I have fixed it before releasing `2.0.0`.  It's only a problem if you are using JDK 1.8, JDK 9+ shouldn't have this problem.
