### ISSUE TITLE
Spek Plugin doesnt work in IntelliJ IDEA 2019.1 EAP

### ISSUE THREAD

**Issue by rburgst** [JetBrains/spek#578]
![image](https://user-images.githubusercontent.com/22971/51751613-8b50ab80-20b5-11e9-834b-7d5c38cc54ae.png)

**Comment by raniejade** [comment]
Thanks for the report! I'll download the EAP first, hopefully it will only require updating the version requirements.

**Comment by raniejade** [comment]
@rburgst plugin is available in the `dev` channel: https://plugins.jetbrains.com/plugin/10915-spek-framework

**Comment by rburgst** [comment]
Unfortunately I dont see it on the web page: 
![image](https://user-images.githubusercontent.com/22971/52048856-a6576b80-254c-11e9-8228-e0ad75dfae82.png)

**Comment by raniejade** [comment]
@rburgst forgot to mention, update is still pending JB's approval. sorry!
