### ISSUE TITLE
Spek + Android

### ISSUE THREAD

**Issue by ch4vi** [JetBrains/spek#60]
I have an Android library in Kotlin and I want to start to bulid my test clases with Spek and probably with Mockito to mock a Context. I'm trying all day long but it not works.

Can Spek works with Android?

**Comment by hhariri** [comment]
What's the actual issue? What error are you getting? Spek doesn't have any relationship with Android in principle...

**Comment by ch4vi** [comment]
Well, the issues is that Android tests should run with an instance of AndroidJUnit4, but JUnitGivenRunner does not inherits from AndroidJUnit4, so there is no way to run test on android.
Moreover, tests classes must inherit from ActivityInstrumentationTestCase*

**Comment by hhariri** [comment]
Ah sorry I'm not that familiar with Android. Yes if Android requires certain inheritance for integration tests, then it wouldn't be viable. Outside of the Android specific tests of course you could use it.
