### ISSUE TITLE
Error "No test were found" when running tests from a package that contains other packages

### ISSUE THREAD

**Issue by yaroslav-shlapak** [JetBrains/spek#606]
Environment:
Android Studio 3.3Build #AI-182.5107.16.33.5199772, built on December 25, 2018
Spek plugin versoin: 2.0.0-Studio3.3
spekVersion = "2.0.0"

Prerequirements:
a package that contains other packages with unit tests.

Steps to reproduce

1. Right click on a package-> Run 'Tests in '[package_name]''
2. "Instantiating tests... " is displayed in the Run tab
3.  "No test were found" is displayed in the Run tab

Also, the first step works only from the second attempt, so after the first attempt nothing happens - test suite is not launched.
Generally, the bug behavior is similar to https://github.com/spekframework/spek/issues/543

**Comment by raniejade** [comment]
Can you share a sample project that can reproduce the issue consistently?

**Comment by yaroslav-shlapak** [comment]
Just updated dependencies for https://github.com/yaroslav-shlapak/TestSpekProject
Please run tests against the https://github.com/yaroslav-shlapak/TestSpekProject/tree/master/app/src/test/java/com/example/testspekproject/packagetoruntests

**Comment by raniejade** [comment]
I've got a fix locally, just waiting for #621 to finish building so I can merge it.

**Comment by yaroslav-shlapak** [comment]
This bug is not fixed, instead of "No test were found" I get "Test framework is quit unexpectedly"

**Comment by raniejade** [comment]
Can you give the spek version and plugin version you are using?

**Comment by yaroslav-shlapak** [comment]
Spek version: 2.0.1
Spek plugin version: 2.0.1-Studio3.3
AS: 3.3.1 and 3.3.2
I'm also getting "No test were found" when trying to run all tests for the entire module using Junit runner

**Comment by yaroslav-shlapak** [comment]
And sometimes nothing happens when I press play button near the test in the AS editor

**Comment by raniejade** [comment]
Weird, can you share a sample project that replicates your issue?
