### ISSUE TITLE
Unable to test java classes with Spek in Android studio

### ISSUE THREAD

**Issue by csschirag** [JetBrains/spek#614]
I have create a package(testJava) in test folder and put java test class there which will test another java class.

java class :

package org.spekframework.speksample;

public class TestClass {

    public static int add(int x, int y) {
        return x+y;
    }

}

Testing Class:

package org.spekframework.speksample.testJava;

import org.junit.Assert;
import org.junit.Test;
import org.spekframework.speksample.TestClass;

import static org.junit.Assert.assertEquals;

public class TestAdd {

    @Test
    public void testAddM() {
        Assert.assertEquals(TestClass.add(2,3),5);
    }
}

Gradle class :

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'jacoco'

// junit5 doesn't support android projects out of the box
apply plugin: "de.mannodermaus.android-junit5"

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "org.spekframework.speksample"
        minSdkVersion 24
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArgument "runnerBuilder", "de.mannodermaus.junit5.AndroidJUnit5Builder"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    // Add Kotlin source directory to all source sets
    sourceSets.each {
        it.java.srcDirs += "src/$it.name/kotlin"
    }

    testOptions {
        junitPlatform {
            filters {
                engines {
                    include 'spek2'
                }
            }
            jacocoOptions {
                // here goes all jacoco config, for example
                html.enabled = true
                xml.enabled = false
                csv.enabled = false
                unitTests.all {
                    testLogging.events = ["passed", "skipped", "failed"]
                }
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    // assertion
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlin_version"

    // spek2
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spek_version"
    testImplementation "org.spekframework.spek2:spek-runner-junit5:$spek_version"

    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestRuntimeOnly "de.mannodermaus.junit5:android-instrumentation-test-runner:$junit5_runner"
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.junit.platform:junit-platform-runner:1.0.0-M5'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.0.0-M5'
    testImplementation "de.mannodermaus.gradle.plugins:android-junit5-embedded-runtime:1.0.0-RC3-rev1"
}

Now , When I am running test of testJava folder which have only java class to test. I am getting following error.

Test framework quit unexpectedly.

**Comment by raniejade** [comment]
Any way you can share a sample project that reproduces the issue? Also what spek version are you using?

**Comment by csschirag** [comment]
[spek-android-example.zip](https://github.com/spekframework/spek/files/2835545/spek-android-example.zip)

Hi @raniejade , Please find attached project.

**Comment by csschirag** [comment]
Hi @raniejade ,

As I have observed . problem is Spek plugin is unable to pick java files from the test folder.
e.g if in test folder  have two files one is .kt and another one is .java then only .kt file will get execute.

**Comment by raniejade** [comment]
@csschirag from what I understand you are expecting spek to run Java tests?

**Comment by csschirag** [comment]
yes, Right. because previous test cases are written in java.

**Comment by raniejade** [comment]
Those are JUnit tests and are not related to Spek. You have to setup them separately. Closing this as a non issue.

**Comment by csschirag** [comment]
but Spek using Junit5 but unable to run Junit test.

**Comment by quiqua** [comment]
Spek is using the `JUnit5 Platform Engine` which allows to run your custom Testing Framework via the JUnit Platform. It does however not mean that you can run JUnit tests with it. For that you'll need `JUnit Jupiter` https://junit.org/junit5/docs/current/user-guide/
