### ISSUE TITLE
Unable to find method 'org.gradle.testing.jacoco.tasks.JacocoReport.getExecutionData()Lorg/gradle/api/file/ConfigurableFileCollection

### ISSUE THREAD

**Issue by csschirag** [JetBrains/spek#616]
I am getting following error after including Spek.

Unable to find method 'org.gradle.testing.jacoco.tasks.JacocoReport.getExecutionData()Lorg/gradle/api/file/ConfigurableFileCollection.

Please find attached sample project.
[spek-android-example.zip](https://github.com/spekframework/spek/files/2836169/spek-android-example.zip)

**Comment by raniejade** [comment]
@csschirag I don't think this a spek problem, but probably you have a build file that is configured to a specific gradle version that is different to the one you use for running.

**Comment by raniejade** [comment]
Closing this as I don't think it's an issue with Spek but with your project setup.
