### ISSUE TITLE
Report package as a scope

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#620]
Given the following test classes:

- `FooBarTest`
- `com.example.FooTest`
- `com.example.BarTest`

The execution report might look like:

```
- FooBarTest
  ...
- com.example.FooTest
  ...
- com.example.FooTest
  ...
```

For better grouping, ideally we want the report to look something like:
```
- <default> // <blank>
  FooBarTest
- com.example
  - FooTest
    ...
  - BarTest
    ...
```

**Comment by raniejade** [comment]
Breaking change, need to think about it more.

**Comment by raniejade** [comment]
@vanniktech re-opening as it's required to fixing #606.

**Comment by raniejade** [comment]
nah, nvm (I thought of something else). Sorry!

**Comment by vanniktech** [comment]
All good!
