### ISSUE TITLE
Fix compatibility between 2.0.1 runtime and 2.0.0 ide plugin

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#631]
There were changes made to constructor signature of `DiscoveryRequest` as part of implementing Kotlin Native support. The change is: `DiscoveryRequest(List<String>, List<Path)` to `DiscoveryRequest(Discovery, List<Path>)`. Adding a secondary constructor that matches the old signature might fix it (hopefully) - if not we just need to accept it, move forward and communicate the breaking change.

**Comment by jcornaz** [comment]
While waiting for the fix, is there a work-around?

Should we downgrade the plugin or artifact dependency? Down to which version?

**Comment by raniejade** [comment]
Use the stable version `2.0.0` for both dependencies and IDE version.

**Comment by svenjacobs** [comment]
Since it's not possible to install an older version through IntelliJ's / Android Studio's Plugin browser, [here's](https://plugins.jetbrains.com/plugin/10915-spek-framework) the download of version 2.0.0 of the plugin.
