### ISSUE TITLE
IntelliJ Plugin should also list all successfull test

### ISSUE THREAD

**Issue by dibog** [JetBrains/spek#644]
I'm using the 2.0.0 Version.  The plugin only shows failed tests as tree. It would be nice to see every case, regardless if failed or not.

**Comment by raniejade** [comment]
@dibog there should be a toggle in the reporting tab that shows all the tests regardless of the execution result. By default, it only shows the failures.

**Comment by dibog** [comment]
Thanks, I have overseen that.
