### ISSUE TITLE
memoized produces unexpected results

### ISSUE THREAD

**Issue by feature** [JetBrains/spek#645]
The documentation for [scope values](https://spekframework.org/core-concepts/#scope-values) gives the impression that the `memoized` delegate is just a shorthand for `lateinit var`s and `beforeEach` blocks. However if the function passed to the `memoized` modifies another memoized value, the change is not reflected in the value.

I'm not sure if this is a bug with `memoized` or not, because I can't find any documentation on the expected behavior of the function. Regardless this is unintuitive, and that behavior is not documented.

Particularly I'm testing [this](https://github.com/staminadevelopment/pubsub4k/blob/master/src/main/kotlin/pw/stamina/pubsub4k/publish/StandardPublisherRegistry.kt#L40) function from a library I'm working on.

In my tests the follow code works as expected:
```kotlin
lateinit var publisher: Publisher<Any>
beforeEach {
    publisher = registry.findOrCreatePublisher(topic) { subscriptions }
}
```
But using `memoized` does not:
```kotlin
val publisher by memoized { registry.findOrCreatePublisher(topic) { subscriptions } }
```

Read comment: https://github.com/spekframework/spek/issues/645#issuecomment-469019149

**Comment by raniejade** [comment]
Can you paste in the full test?

**Comment by feature** [comment]
I was still working on the tests, but here they are. All the affected cases are commented with `Do not use memoized here`.

https://github.com/staminadevelopment/pubsub4k/blob/master/src/test/kotlin/pw/stamina/pubsub4k/publish/StandardPublisherRegistrySpec.kt

**Comment by raniejade** [comment]
> However if the function passed to the memoized modifies another memoized value, the change is not reflected in the value.

Did you mean _access_? You can't modify a memoized value.

Anyway, the exact semantics are (and you're right I need to add more documentation around it)

```
    val a by memoized { 1 }
    val b by memoized { a + 1 }
```

If `b` was accessed first then the value is initialized by calling the passed factory lambda, since it's accessing another memoized value `a`,  then the same thing will happen with `a`.

This can be seen by doing some simple `println`s.

```kotlin
    val a by memoized {
        println("a")
        1
    }
    val b by memoized {
        println("b")
        return@memoized { a + 1 }
    }

    test("foo") {
        println(b())
    }
```

The output will be:
```
b
a
2
```

`memoized` should work with your use case, so I'm probably missing something here.

**Comment by feature** [comment]
I'm not trying to change the value of a memoized property, but make changes to the object that is memoized.

The simplest example case I can come up with is this simple List spec:
```kotlin
object ListSpec : Spek({
    describe("A mutable list") {
        val list by memoized { mutableListOf<Any>() }
        
        describe("adding item to list") {
            val item by memoized { Unit }
            val added by memoized { list.add(item) }
            
            it("should return true") {
                added shouldBe true
            }
            
            it("size should be 1") {
                list.size shouldBe 1
            }
            
            it("should contain item") {
                list shouldContain item
            }
        }
    }
})
```
The first test passes fine as expected, but the last two unexpectedly fails.

If I replace
```kotlin
val added by memoized { list.add(item) }
```
with
```kotlin
var added = false
beforeEach {
    added = list.add(item)
}
```
all the test passes as expected.

**Comment by raniejade** [comment]
Ahh right, you aren't supposed to it that way. Since you're performing an action using `beforeEach` is the right way to go.

**Comment by feature** [comment]
I learned that, and it also seems reasonable, but I still think the documentation should be clarified.
