### ISSUE TITLE
Spek Framework for IntelliJ/Android Studio generates run configurations with incorrectly formatted paths

### ISSUE THREAD

**Issue by orospakr** [JetBrains/spek#666]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/16714/55648105-68293300-57ad-11e9-938b-213a02edd75b.png">

Path should apparently be `io/rover/core`, not `io.rover.core`. It looks like it's using a package identifier rather than a path.

The result of executing such a run configuration is "Test framework quit unexpectedly", with an exit code of 0.

I get run configurations formatted like this if I right click on a package in the project explorer and chose Run Spek tests.

If I right click an individual Spek test Kotlin file, I get a run configuration generated with a correct path.

My ultimate goal to run all my Spek tests in my package with a single run configuration.

(Incidentally, you also can't modify the Path field yourself as an escape valve: it's a fixed dropdown selector, not populated with any other options available to select.)

**Comment by raniejade** [comment]
@orospakr What version of spek are you using in your project and in the IJ plugin?

**Comment by orospakr** [comment]
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 15, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

And Spek Framework plugin version 2.0.2-IJ2018.2.

**Comment by orospakr** [comment]
In my project at time of reporting the bug it Spek itself was 2.0.1, but confirmed it persists with 2.0.2.

**Comment by raniejade** [comment]
> (Incidentally, you also can't modify the Path field yourself as an escape valve: it's a fixed dropdown selector, not populated with any other options available to select.)

Known issue, not a priority right now. 

I'll take a look, thanks for the info!

**Comment by orospakr** [comment]
Hey @raniejade maybe I'm missing something, but this prevents me from running more than one file's worth of tests at a time.  How should I run all my tests at once? (short of just using the JUnit runner)

**Comment by raniejade** [comment]
>  How should I run all my tests at once?

Will running via gradle work for you for now? I think I know what the issue is, just trying to find some time to do the actual change. 

probably this: https://github.com/spekframework/spek/blob/2.x/spek-ide-plugin/intellij-base/src/main/kotlin/org/spekframework/intellij/SpekRunConfigurationProducer.kt#L119

**Comment by raniejade** [comment]
@orospakr can you check this build: 
[2.1.0-alpha.0.1+4f4cd28-Studio3.3.zip](https://github.com/spekframework/spek/files/3075544/2.1.0-alpha.0.1%2B4f4cd28-Studio3.3.zip) if it fixes your issue?

**Comment by yaroslav-shlapak** [comment]
Same issue on AS 3.3 and 3.4, any progress? Running test and viewing test results inside the IDE is a paramount feature. Without it, we need to open test report in the browser with no referencing to the code.

**Comment by raniejade** [comment]
@yaroslav-shlapak have you tried the build I posted here?

**Comment by yaroslav-shlapak** [comment]
@raniejade can't install it on AS 3.4. Is there a build for AS 3.4?

**Comment by raniejade** [comment]
@yaroslav-shlapak sorry about that, probably because the build is before #676 was merged to the main branch. You can download the latest dev build from https://plugins.jetbrains.com/plugin/10915-spek-framework/versions (dev channel) - it should contain both changes.

**Comment by yaroslav-shlapak** [comment]
@raniejade this issue still persists on v2.1.0-alpha.0.7+b081e15-Studio3.4. Test project: https://github.com/yaroslav-shlapak/TestSpekProject

**Comment by raniejade** [comment]
@yaroslav-shlapak just confirming, when you say issue: is it you are unable to install the plugin? or not being able to run the test in a package (because of the invalid path - can you confirm that you are getting `com.example` instead of `com/example`)?

I'm pretty sure that path issue is fixed,

**Comment by yaroslav-shlapak** [comment]
@raniejade the path seems to be correct (with slashes instead of dots), but I still got an empty test suite when running Spek against a package.

**Comment by raniejade** [comment]
@yaroslav-shlapak thanks for the clarification, I'll take a look.

**Comment by raniejade** [comment]
@yaroslav-shlapak got your example working - just had to make a few tweaks:

```
TestSpekProject [master]× » git diff                                                                                                                                                                                                                       ~/p/s/TestSpekProject
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: app/build.gradle
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ build.gradle:106 @ android {

dependencies {
    implementation "androidx.appcompat:appcompat:$supportVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion" // note jdk8

    // Test spek2
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spekVersion"
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: versions.gradle
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ versions.gradle:16 @ project.ext {
    testRunnerVersion = "1.1.0-beta01"
    archTesting = "1.0.0"
    jacocoVersion = "0.8.3"
    spekVersion = "2.0.2"
    spekVersion = "2.1.0-alpha.0.8+9a82ca8" // new version here
    junitJupiterVersion = "5.4.0"
    junit5RunnerVersion = "0.2.2"
    junit5GradlePuginVersion = "1.4.0.0"
```

Found out that the latest dev build of a plugin is not compatible with `2.0.2`. I think moving forward I'll add in the requirement that the plugin version and the library version should be the same.
