### ISSUE TITLE
Gradle Multi-project only runs tests for one project

### ISSUE THREAD

**Issue by kleinwareio** [JetBrains/spek#671]
I have a Gradle multi-project (all Kotlin) and for some strange reason, tests are only being found in one of my projects.

Here is the entire `build.gradle` for the root project
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.21' apply false
    id "com.adarshr.test-logger" version "1.6.0" apply false
}

allprojects {
    version '1.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'com.adarshr.test-logger'
    
    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

        testImplementation 'org.jetbrains.kotlin:kotlin-test'
        testImplementation "org.spekframework.spek2:spek-dsl-jvm:2.0.1"

        testRuntimeOnly "org.spekframework.spek2:spek-runner-junit5:2.0.1"
        testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect"
    }

    test {
        useJUnitPlatform {
            includeEngines 'spek2'
        }
    }

    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
}
```

Projects X and Y don't have a `build.gradle`, they both use what is defined in the root.

Both projects also have Spek tests.

`./gradlew clean test -i` shows Project X with `WARNING: TestEngine with ID 'spek2' failed to discover tests`. The tests for Project Y run fine.

Both sets of tests run in IntelliJ using the Spek plugin, though if I right-click on the package in Project X containing my tests and `Run 'Tests in 'projectx.foo''` then I get the error in the Run Output window of `No tests found for given includes: [projectx.foo.*](filter.includeTestsMatching)`. Running the tests via the gutter in a Spek object in Project X works fine.

Right-clicking on the package in Project Y containing my tests and running them also works fine.

I am completely stumped as to what is going on... Unfortunately, I'm also a Gradle newb, so that isn't helping either...

**Comment by raniejade** [comment]
@kleinwareio can you try using spek `2.0.2`?

**Comment by kleinwareio** [comment]
Thanks @raniejade ! That fixed it!

**Comment by kleinwareio** [comment]
However... now I can only run the "top level" `object MyTests : Spek(...)` tests from the gutter in IntelliJ. None of the other groups (`describe`, `it`) have the "run" icon anymore...

**Comment by raniejade** [comment]
@kleinwareio are you using `@RunWith(...)`? or do you have the spek plugin installed?

**Comment by kleinwareio** [comment]
Hmmm..... Restarting IntelliJ brought back the missing gutter icons...

Not sure which side of the IDE / Plugin fence the issue was on... Sorry for the spam =/ and thanks for the help!
