### ISSUE TITLE
Unsuitable Spek gradle plugin to update

### ISSUE THREAD

**Issue by yaroslav-shlapak** [JetBrains/spek#676]
Android studio always propose to install spek gradle plugin for IJ, which doesn't work properly
![Screenshot from 2019-04-18 11-14-46](https://user-images.githubusercontent.com/3373419/56346748-82123f00-61cb-11e9-977b-85e776852d7c.png)
![Screenshot from 2019-04-18 11-15-21](https://user-images.githubusercontent.com/3373419/56346763-876f8980-61cb-11e9-9099-46938e82bda8.png)
whereas AS plugin is not compatible:
![Screenshot from 2019-04-18 11-17-51](https://user-images.githubusercontent.com/3373419/56346882-b7b72800-61cb-11e9-8de2-a3db4366b7bd.png)

**Comment by raniejade** [comment]
Thanks @yaroslav-shlapak, i probably need to update the version ranges for AS 3.4
