### ISSUE TITLE
Allow it on given without an on

### ISSUE THREAD

**Issue by dalewking** [JetBrains/spek#68]
Sometimes you are just checking the static state of something and not really performing an action. For example, something simple like my API exports a constant for use by users and I want to just verify its value.

In English, I basically want to say something like this:

    given("MY_CONSTANT")
    {
         it("Should have the value 5") { shouldEqual(5, MY_CONSTANT) }
    }

But I am forced to add an on in there, which isn't really needed since nothing is being done. You basically end up saying something unncessary like

    given("MY_CONSTANT")
    {
         on("inspection") { it("Sould have the value 5") { shouldEqual(5, MY_CONSTANT) } }
    }

**Comment by lkogler** [comment]
I took a stab at fixing this problem and ended up doing quite a bit of changes.  You can see my fork over at https://github.com/lkogler/spek.  Basically, I changed the DSL to behave like RSpec: you can have `describe` blocks nested to arbitrary depth, and there are `beforeEach` and `afterEach` blocks that execute before and after every `it` block. 

I know that it's quite a major change, I'd love to hear what people think before spending the time to put the finishing touches on it for a pull request.  Please let me know if this is something that sounds interesting!

**Comment by hhariri** [comment]
I believe this issue should now be solved.
