### ISSUE TITLE
Does the latest IntelliJ IDEA 2019.1.1 can be used to develop Android project with spek?

### ISSUE THREAD

**Issue by 9468305** [JetBrains/spek#681]
Hi,

In `https://github.com/spekframework/spek/blob/2.x/docs/running.md` Line 7, you said:
> !!! info Running tests for Android projects in IntelliJ IDEA is not supported, please use Android Studio.

AFAIK, IntelliJ IDEA can used to build regular Android project, just need to download Android SDK and config the right file path. (https://github.com/9468305/log-kotlin is one of my simple kotlin multiplatform project for Android, iOS, which created by IntelliJ IDEA.)
Is there any other reason for not use IntelliJ IDEA? Is it because of spek plugin?

**Comment by raniejade** [comment]
Yes, because of the plugin. Several hacks introduced to support Android Studio made it hard to have only one plugin. There's probably a way to restructure the plugin so that it can support both android and non-android projects, but not a priority right now.
