### ISSUE TITLE
Disallow empty descriptions

### ISSUE THREAD

**Issue by jordaninstil** [JetBrains/spek#689]
When running via `gradle test` no spek tests will be run when a block (group, describe, it etc) has an empty description. 

This issue does not happen when running via the spek framework plugin.

Spek version: 2.0.1 - 2.0.4 (possibly any 2.x version)
Android studio: 3.4

**Comment by raniejade** [comment]
An empty description is not allowed. Going to re-purpose this ticket to make it consistent by adding checks.
