### ISSUE TITLE
Timeout not working for "describe"

### ISSUE THREAD

**Issue by Bendat** [JetBrains/spek#698]
In 2.0.4 I am unable unable to override the default timeout. The method signature allows it but no matter what's set it still times out:

`         it("Created the device", timeout = 30000) {
                   macroOfLongApiCalls()
                }
`

Results in:
`
Timed out waiting for 10000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
`

**Comment by raniejade** [comment]
Fixed by #693 which will be included in the next release.
