### ISSUE TITLE
Add a lazily evaluated group type

### ISSUE THREAD

**Issue by Bendat** [JetBrains/spek#700]
I attempted to create a test in the following format.
```
lateinit var list: List<Thing>

it("Creates a list of things"){
   list = listOf(Thing(), Thing())
}

describe("Testing our things"){
     list.foreach{
         if("Should verify thing [$it]){
               // whatever
         } 
    }
}

```

The problem is, when the describe executes, it throws an unitialized field exception on the list. 

Is there currently any way to do this?

**Comment by raniejade** [comment]
No, that's not valid. Would suggest reading https://spekframework.org/core-concepts/ to understand why it won't work. 

You can try:

```kotlin
listOf(Thing(), Thing()).forEach {
   it("should verify thing [$it]") { ... }
}
```
