### ISSUE TITLE
too slow okhttp test

### ISSUE THREAD

**Issue by paz-raon** [JetBrains/spek#702]
- okhttp_version=3.14.1
- spek_version=2.0.4

too slow When I do to run async okhttp test.

Here is my code.

---
        it("okhttp enqueue") {
            val httpClient = OkHttpClient.Builder()
                .protocols(listOf(Protocol.HTTP_1_1))
                .build()

            val request = Request.Builder()
                .url("https://www.google.com")
                .method("GET", null)
                .build()

            val countDownLatch = CountDownLatch(1)

            httpClient.newCall(request).enqueue(object : Callback {
                override fun onFailure(call: Call, e: IOException) {
                    e.printStackTrace()
                }

                override fun onResponse(call: Call, response: Response) {
                    println("protocol: ${response.protocol()}")

                    response.body().use({ responseBody ->
                        println(responseBody?.string())
                    })
                }
            })

            countDownLatch.await()
        }
---

![스크린샷 2019-05-17 오후 9 48 22](https://user-images.githubusercontent.com/1497209/57929176-8aa28600-78ed-11e9-8974-d5ebdd40b4e8.png)

what's wrong?

**Comment by raniejade** [comment]
You're not calling `CountdownLatch#countDown` when the HTTP call completes, therefore, the call to `countDownLatch.await()` will block forever.
