### ISSUE TITLE
Fix plugin being incompatible with Android Studio updates

### ISSUE THREAD

**Issue by yaroslav-shlapak** [JetBrains/spek#709]
Spek framework gradle plugin is the only plugin being used by me which becomes incompatible with every new AS update. 
![Screenshot from 2019-05-21 19-26-16](https://user-images.githubusercontent.com/3373419/58113859-2a6a5780-7bff-11e9-8ef6-a922cf239f6d.png)
Is it possible to fix this to work the same way as the other plugins work?

**Comment by raniejade** [comment]
@yaroslav-shlapak can you try this build out?

[2.1.0-alpha.0.7+20190522T070111Z-Studio3.4.zip](https://github.com/spekframework/spek/files/3206043/2.1.0-alpha.0.7%2B20190522T070111Z-Studio3.4.zip)

**Comment by yaroslav-shlapak** [comment]
@raniejade it works on AS 3.4.1 ~~and on AS 3.5 Beta 2~~. Will it work on future AS releases?

**Comment by yaroslav-shlapak** [comment]
This issue is not about providing a working plugin for AS 3.4.1. It is about the fix of behavior that was observed for about half a year - when AS is updated Spek plugin stop working.

**Comment by raniejade** [comment]
> Is it possible for every plugin release disable blocking work on every next version of IJ/AS?

Locking the versions is intentional, there are no guarantees that the plugin for the current version of AS will work for the next major version. I'll add a plugin build for AS 3.5 on the `2.0.6` release (see #712).

**Comment by raniejade** [comment]
And the problem with this update was AS changed the build number between `3.4.0` -> `3.4.1`. I was working on the assumption that build numbers won't change between minor releases - this was the case for all previous releases.

**Comment by yaroslav-shlapak** [comment]
Thanks @raniejade

**Comment by yaroslav-shlapak** [comment]
Sorry for misinformation - 2.1.0-alpha.0.7+20190522T070111Z-Studio3.4 doesn't work on AS 3.5 Beta 2. But v2.0.4-IJ2019.1 does work.
