### ISSUE TITLE
Release date for version 2.0.5?

### ISSUE THREAD

**Issue by sraiteri** [JetBrains/spek#710]
Hi Spek Framework community,

We have a number of teams in entrenched in the process of upgrading legacy Spek tests to Spek 2. One of the significant barriers reported is the ability to provide custom timeouts during test debugging, which has since been resolved in `2.0.5` (thanks @raniejade!).

Is there an ETA on the release for this version?

Regards,
Shane.

**Comment by raniejade** [comment]
Just need to fix #709 then trigger a release. Hopefully by tonight. In the meantime, can you use the dev builds?

**Comment by sraiteri** [comment]
Thanks @raniejade :smile:.

We're are going to continue using the 2.1.0 dev build in the meantime, so at this stage it's just to satisfy an internal development rule that we don't do APK releases with pre-release dependencies.

**Comment by raniejade** [comment]
FYI, `2.0.5` is out :)
