### ISSUE TITLE
Can not run test from command line

### ISSUE THREAD

**Issue by Petrulak** [JetBrains/spek#719]
Hello, we have recently migrated from Spek 1 to Spek 2.
The migrated tests are running fine using AS plugin, however, doesn't run using the command line.
It hangs here for a few seconds (10~15?) 
```
> Task :app:testDevDebugUnitTest
objc[74407]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java (0x106cf04c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x106d744e0). One of the two will be used. Which one is undefined.
<============-> 99% EXECUTING [39s]
> :app:testDevDebugUnitTest > 0 tests completed
> IDLE
> IDLE
> IDLE
```
Adn then i can see
```
BUILD SUCCESSFUL in 39s
25 actionable tasks: 9 executed, 16 from cache
```
Any idea what can be wrong? 

We are using:
```
    const val jacoco = "0.8.3"
    const val junit5plugin = "1.4.2.0"
    const val kotlin = "1.3.31"
    const val spek2 = "2.0.5"
```

**Comment by raniejade** [comment]
Can you share the project or a reproducer?

**Comment by Petrulak** [comment]
Hello, i can not share the project, since it an enterprise app. I will try to fix it somehow on my own.

**Comment by raniejade** [comment]
If you can send in a sample project that reproduces the problem consistently, then I'll be happy to help. :)

**Comment by raniejade** [comment]
Please re-open when you are able to share a sample project.
