### ISSUE TITLE
Conflict in runtime versions

### ISSUE THREAD

**Issue by codeslubber** [JetBrains/spek#72]
> Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-stdlib'. Resolved versions for app (1.0.1) and test app (1.0.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

I saw some people talking about excluding the runtime from the test import. But since it's not in the docs, and I just spent ~ half an hour trying to add this one dependency to an Android project, going to go back to JUnit instead. 

Why are releases not made on this project?

**Comment by hhariri** [comment]
We're working on finally moving to 1.0 and there are significant changes. You can see the WIP on the 1.0 branch. Once that's final, we'll make the release.
