### ISSUE TITLE
Routes not added to Micronaut EmbeddedServer 

### ISSUE THREAD

**Issue by robZrad** [JetBrains/spek#723]
Spek test for Micronaut application fail when ran from IntelliJ Idea/Spek plugin , because EmbeddedServer has no routes defined. I encountered it in my project, but the same can be reproduced with https://github.com/micronaut-guides/creating-your-first-micronaut-app-kotlin.
Steps to reproduce:
1. install Intellij 2019.1.3
2. Install Spek-Framework Plugin v2.0.5-IJ2019.1
3. Clone and open https://github.com/micronaut-guides/creating-your-first-micronaut-app-kotlin.
4. Modify gradle.properties to use ``spekVersion=2.0.5`` (on 2.0.0-alpha.1 there is some other fail)
5. Run ./gradlew test from console - tests pass fine
6. Find creating-your-first-micronaut-app-kotlin/complete/src/test/kotlin/example.micronaut/HelloControllerSpec and Run it - it fails with error:
``
Page Not Found
io.micronaut.http.client.exceptions.HttpClientResponseException: Page Not Found
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1783)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1723)
...
``

**Comment by raniejade** [comment]
Quick question before I start investigating further: Did you follow the setting up guide found here? Particularly the section _2 Writing the App_?

**Comment by robZrad** [comment]
You mean https://guides.micronaut.io/creating-your-first-micronaut-app-kotlin/guide/index.html#writingTheApp ?
Yes, I just rechecked all the steps once again.

**Comment by raniejade** [comment]
It works for me if I have the option `Delegate build/run actions to gradle` ticked, otherwise, I get the same exception.
