### ISSUE TITLE
Test events were not received

### ISSUE THREAD

**Issue by jshinn6788** [JetBrains/spek#724]
I'm getting this "Test events were not received" error when I run my tests using the IDE and gradlew.  I'm using TestNG framework.  My goal was to use it with the Windows Application automation testing.  I have no idea how to resolve this.

**Comment by raniejade** [comment]
Hey! TestNG framework is a different framework and does not relate to Spek whatsoever. If you're really using Spek, then please describe the problem more and possibly include a reproducer (minimal sample project that replicates the problem consistently).
