### ISSUE TITLE
Validating a return value examples show use of lateinit on primitives which throws a compiler error

### ISSUE THREAD

**Issue by automationhacks** [JetBrains/spek#737]
Hello There. 

I was walking through the examples given for **Specification or Gherkin** syntax and I observed a compiler error on trying to use `lateinit` for a primitive data type like Int. Using Kotlin 1.3.40 version with Spek 2.0.5

Can you please fix the documentation so that it does not mislead people. Essentially since the examples work with a primitive data type which is not supported with lateinit. We can either initialize `result` as 0 or change the example to work with a non-primitive type and specify the kotlin docs as a link so that folks can understand rules of using lateinit.

https://kotlinlang.org/docs/reference/properties.html#late-initialized-properties-and-variables

`Error:(10, 9) Kotlin: 'lateinit' modifier is not allowed on local variables of primitive types`

Below is the full code where this is reproducible.

SpecStyle.kt

```
package graspSpek.styles

import junit.framework.Assert.assertEquals
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

object SpecStyle : Spek({

    describe("adding 1 + 2") {
        lateinit var result: Int
        beforeEachTest {
            result = 1 + 2
        }

        it("result should be 3") {
            assertEquals(result, 3)
        }
    }
})
```

Below is my build.gradle:

```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.40'
}

group 'grasp-kotlin'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    mavenLocal()
    jcenter()
}

// Spek specific
test {
    useJUnitPlatform {
        includeEngines 'spek2'
    }
}

dependencies {
    compile group: 'org.testng', name: 'testng', version: '6.8.8'
    testCompile group: 'junit', name: 'junit', version: '4.12'

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.40"
    // Spek specific dependencies
    testImplementation  "org.spekframework.spek2:spek-dsl-jvm:2.0.5"
    testRuntime "org.spekframework.spek2:spek-runner-junit5:2.0.5"
    testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect:1.3.40"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by raniejade** [comment]
Makes sense, thanks for the report!
