### ISSUE TITLE
V1.0.0: given and on should prefix description

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/spek#74]
In v1.0.0, `given` and `on` are both aliases to `describe`.
They should be aliases that prefix the description with their keyword.

`given(description, block)` should translate to `given("Given " + description, block)`
`on(description, block)` should translate to `on("On " + description, block)`

Currently, when you use `given("a calculator") {}`, the IDEA test runner shows a test group that is named "a calculator" while it should be named "Given a calculator".

**Comment by hhariri** [comment]
The only thing there is a) localisation support b) make it optional and default?

**Comment by SalomonBrys** [comment]
a) I'm not sure localisation is a problem. "Given" is an english word, using it implies an english sentence.
Being french, I wouldn't write `given("une calculatrice")`. I'd rather create my own `avec` function.

b) To me, `describe` is the default. If you're using `given`, then you're exepected to provide a sentence that completes after the word.

**Comment by hhariri** [comment]
But if you're using French and want to use given, wouldn't you want it to say "avec" ?

**Comment by SalomonBrys** [comment]
If I would want to use french sentences, I'd use `describe`.

**Comment by juanchosaravia** [comment]
I sent a PR regarding this issue: https://github.com/JetBrains/spek/pull/90
I think it's OK to leave it tied to english words as the aliases are in english too, also "it" is in this way.

**Comment by chisou** [comment]
+1 for that PR to increase consistency. 

But it would be best to support this with a set of non-spoken qualifiers in case you a) want to use a different language than English or b) have your test just structured in a different way.

I right now I need to end all my tests with an "it" like test name which quite often is just annoying. 

So - when we are having `given`, `on`, `it` with forced descriptions I'd like to have corresponding methods that don't imply a description. We have `describe`, what about adding `test` as a companion to `it`?

**Comment by raniejade** [comment]
@chisou There are some changes happening in spek right now which will allow you to extend the DSL. See https://github.com/JetBrains/spek/blob/junit5/spek-api/src/main/kotlin/org/jetbrains/spek/api/dsl/Standard.kt on how to do it. Do note that this has not been merged on master yet.

**Comment by chisou** [comment]
That looks quite cool and the Standard already seems to have all the methods I dreamed of :-) Great, looking forward to it!
