### ISSUE TITLE
Cannot run selected tests Spek tests in IntelliJ IDEA Run window

### ISSUE THREAD

**Issue by rgladwell** [JetBrains/spek#746]
Cannot select individual Spek tests in IntelliJ IDEA Run window/pane with Spek Framework plugin.

```
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

With Kotlin version `1.3.41-release-IJ2019.1-1` installed in IntellIj.

### Steps to reproduce:

 1. Install Spek Framework IntelliJ plugin
 2. Open Kotlin/Spek project
 3. Right-click on `src/test/kotlin` folder and select `Run 'All Tests'`.
 4. Right-click individual test in IntelliJ Run pane and select `Run...` for that test.

### Expected Result:

Should run individual test.

### Actual Result:

Get `No tests were found` error instead.

**Comment by raniejade** [comment]
If I remember correctly `Run 'All Tests'` is handled by the built-in JUnit plugin not Spek, you might need to do something extra to make it work. This might also apply to 4 but I'll check. To help debugging can you share a minimal spek project that replicates the issue?

**Comment by rgladwell** [comment]
I think any Kotlin/Spek project should work. I did try some of the example projects in Github but they're mostly stale and not usable with modern versions of software.

**Comment by raniejade** [comment]
Just replicated this, but I doubt I can fix this since `Run 'All Tests'` is handled by the JUnit Plugin. I have opened #750 to implement the same feature on Spek's IJ plugin.

**Comment by rgladwell** [comment]
Thanks, subscribed
