### ISSUE TITLE
Tests time out when debugging

### ISSUE THREAD

**Issue by Rosomack** [JetBrains/spek#748]
Test timeouts are great but have a bit of an unintended side effect.

The tests time out even when a debugger is attached with breakpoints in test source code or the main source code.

I know we can work around this by setting a long timeout but is it possible to detect whether a debugger is attached and not apply a timeout?

**Comment by raniejade** [comment]
I don't think it's possible, and as you mentioned the best "solution" for now is to set a long timeout.
