### ISSUE TITLE
Reuse defined steps

### ISSUE THREAD

**Issue by vincentfree** [JetBrains/spek#749]
When writing a Background type of step like
```kotlin 
Given("Setup some backend with mocks/stubs") {
    //some setup code
}
```
I would like to be able to reuse this like a function or some other way so steps defined in the past can be reused and we don't have to repeat ourselfs.

**Comment by raniejade** [comment]
You can create an extension method on `ScenarioBody`.

```kotlin
fun ScenarioBody.GivenSomething() {
  Given("Setup some backend with mocks/stubs") {
    //some setup code
  }
}
```

Then you can use it as is on any `scenario`:

```kotlin
Feature("Some feature") {
  Scenario("Some scenario") {
     GivenSomething()
  }
}
```

You can pass in some parameters there too, for example `GivenUserIsLoginAs(username, password)`. Do note for you can't pass memoized/scope values directly as parameters you need to access them via `memoized`.

```kotlin
fun ScenarioBody.GivenUserIsLoginAs(username: String, password: String) {
  val loginService: LoginService by memoized()
}
```

Then you can use it as:

```kotlin
Feature("Some feature") {
  val loginService by memoized { ... }
  Scenario("Some scenario") {
     GivenUserIsLoginAs(user, pass)
  }
}
```

**Comment by raniejade** [comment]
Closing as answered.

**Comment by vincentfree** [comment]
Thanks again for the examples!
