### ISSUE TITLE
Spek 2.0.6-IJ2019.2 is not published

### ISSUE THREAD

**Issue by jcornaz** [JetBrains/spek#757]
Hi, 

I'm not sure if you're aware of it, but `2.0.6-IJ2019.2` is not available in IntelliJ's plugin marketplace: https://plugins.jetbrains.com/plugin/10915-spek-framework/versions

So, as a consequence, it is not possible to run Spek tests from IntelliJ 2019.2.

**Comment by romeoro** [comment]
Had the same issue a couple of hours ago.
Now it should be available!

**Comment by jcornaz** [comment]
>Now it should be available!

Indeed. Thanks
