### ISSUE TITLE
Running tests with gutter icon does not respect "Run tests using: Gradle" setting

### ISSUE THREAD

**Issue by adik993** [JetBrains/spek#759]
IntelliJ offers the setting in `Build, Execution, Deployment > Build Tools > Gradle` to run the tests using Gradle. See docs [here](https://www.jetbrains.com/help/idea/gradle-settings.html#build_run_options)

**Current behaviour**
When the setting is set to "Gradle" clicking gutter icon runs the tests using IntelliJ

**Expected behaviour**
When the setting is set to "Gradle" clicking gutter icon runs the tests using Gradle with appropriet `--tests` filter

**Comment by raniejade** [comment]
Closing this as wont-fix. Gradle and Spek has a different notion of how tests are structured (Class - method vs lambdas), it's not possible to map a spek run request `org -> somepackage -> CalculatorTest -> calculator -> addition` to a gradle test filter.

```kotlin
package org.somepackage

object CalculatorTest : Spek({
  describe("calculator") {
	describe("addition") {
		// omitted
	}
  }
})
```

**Comment by raniejade** [comment]
FYI, build via gradle option is still honored.
