### ISSUE TITLE
Android documentation?

### ISSUE THREAD

**Issue by RedNifre** [JetBrains/spek#76]
I created a spek test somewhere in the androidTest package. How do I include it in the test APK? Or how to run it at all? The website states that you can "just run it" in IntelliJ, how do I "just run it" in Android Studio without getting an "Empty test suite" error?

Basically I'm looking for a quick Android tutorial for Spek.

**Comment by hhariri** [comment]
What is the base class for the test? We currently don't support Android integration tests.

**Comment by raniejade** [comment]
For reference: 
- https://developer.android.com/studio/test/index.html#TestAPI
- https://developer.android.com/topic/libraries/testing-support-library/index.html

**Comment by ZakTaccardi** [comment]
I'm interested in running a unit test on the testCompile classpath of a andoroid library gradle module.

documentation on how to set this up would be nice

**Comment by raniejade** [comment]
http://jetbrains.github.io/spek/docs/latest/#setting-up-android
