### ISSUE TITLE
Add custom ExecutionListener/Reporter

### ISSUE THREAD

**Issue by badoualy** [JetBrains/spek#761]
Is there anyway to add a custom reporter or simply to listen to an event "group failed".

In the `LifecycleListener`, we don't get any information in `afterExecuteGroup` about the result 🤔 

Thanks.

**Comment by robstoll** [comment]
I would be interested in such a feature as well but I actually need more than just a listener. More like a decorator whith the possibility to change events. E.g. turn a failing test into a successful one.
Following my current workaround in case others are interested:
https://github.com/robstoll/atrium/tree/master/samples/readme-examples/src/main/kotlin/readme/examples

**Comment by badoualy** [comment]
Thanks for the sample @robstoll , I ended up doing what you did.
Short version for anyone interested:

```kotlin
import org.junit.platform.engine.EngineDiscoveryRequest
import org.junit.platform.engine.TestDescriptor
import org.junit.platform.engine.TestEngine
import org.junit.platform.engine.UniqueId
import org.spekframework.spek2.junit.JUnitEngineExecutionListenerAdapter
import org.spekframework.spek2.junit.SpekTestDescriptor
import org.spekframework.spek2.junit.SpekTestDescriptorFactory
import org.spekframework.spek2.junit.SpekTestEngine
import org.spekframework.spek2.runtime.SpekRuntime
import org.spekframework.spek2.runtime.execution.ExecutionRequest
import org.junit.platform.engine.ExecutionRequest as JUnitExecutionRequest

class CustomSpekTestEngine : TestEngine {

    private val spekEngine = SpekTestEngine()
    private val descriptorFactory = SpekTestDescriptorFactory()
    private val runtime = SpekRuntime()

    override fun getId() = "spek2-custom"

    override fun discover(discoveryRequest: EngineDiscoveryRequest, uniqueId: UniqueId): TestDescriptor {
        return spekEngine.discover(discoveryRequest, uniqueId)
    }

    override fun execute(request: JUnitExecutionRequest) {
        val roots = request.rootTestDescriptor.children
            .filterIsInstance<SpekTestDescriptor>()
            .map(SpekTestDescriptor::scope)

        val listenerAdapter = JUnitEngineExecutionListenerAdapter(request.engineExecutionListener, descriptorFactory)

        val executionRequest = ExecutionRequest(
            roots,
            SpekExecutionListenerAdapter(
                listOf(
                    listenerAdapter,
                   // Your custom listeners here
                )
            )
        )

        return runtime.execute(executionRequest)
    }
}
```

In your `build.gradle`

```groovy
test {
    useJUnitPlatform {
        includeEngines 'spek2-custom', ...
    }
}
```

Also add a `org.junit.platform.engine.TestEngine` file in `test/resources/META-INF` with the FQCN of your custom class

**Comment by raniejade** [comment]
>  turn a failing test into a successful one.
Following my current workaround in case others are interested:

@robstoll can you elaborate more on why you need this?

@badoualy I'm keen to hear your use case as well.

**Comment by robstoll** [comment]
I am using the modified spek engine to run specs, get the result and populate the Readme.md of Atrium. For instance: https://github.com/robstoll/atrium#your-first-assertion and the corresponding spec:
https://github.com/robstoll/atrium/blob/master/samples/readme-examples/src/main/kotlin/readme/examples/ReadmeSpec.kt#L40

**Comment by raniejade** [comment]
Hmm, interesting. Though I still don't understand why you need to turn a failing test into a successful one.

**Comment by robstoll** [comment]
Because I want that the test fails but turn it into a successful test so that the build does not fail

**Comment by raniejade** [comment]
Ahh, make sense. I can probably add more info into `LifecycleListener` for now. Not to sure if I'd want to allow changing a failure to a success. I think for your use case you should be able to use:

```
test {
   ignoreFailures = true
}
```

Also, another thing to note is that a group failure is only reported when a group fixture fails (beforeGroup, afterGroup`) not when a child fails. The same applies for JUnit 5:

```
	 * <p>The {@link TestExecutionResult} describes the result of the execution
	 * for the supplied {@code testDescriptor}. The result does not include or
	 * aggregate the results of its children. For example, a container with a
	 * failing test must be reported as {@link Status#SUCCESSFUL SUCCESSFUL} even
	 * if one or more of its children are reported as {@link Status#FAILED FAILED}.
```

**Comment by raniejade** [comment]
Including it for `2.0.8`. Going to add this class:

```kotlin
sealed class ExecutionResult {
    object Success : ExecutionResult()
    class Failure(val cause: Throwable) : ExecutionResult()
}
```

**Comment by robstoll** [comment]
I cannot `ignoreFailures` in general as other failures should still fail. To be fair, it is probably a rather rare use case to turn failing tests into successful ones. So for me it is fine if I go on with the workaround. Maybe it is better if you focus here on badoualy's use case.

**Comment by badoualy** [comment]
@raniejade I'm using Spek to run Appium test on BrowserStack, once the test is finished, I need to upload the session's result on BrowserStack.

I could've done it with a `success = true` at the end of every test, but that's quite ugly IMO.
