### ISSUE TITLE
Run Junit tests along with spek

### ISSUE THREAD

**Issue by bblackbelt** [JetBrains/spek#762]
Hi is it possible to run 'normal' junit tests along with spek tests?

**Comment by christian-draeger** [comment]
would be intressted in how to archive this as well. 
@bblackbelt did you find a working solution along with junit5?

**Comment by bblackbelt** [comment]
I was able to run them with

        junitPlatform {
            filters {
                engines {
                    include 'spek2', 'junit-vintage'
                }
            }
        }

and 

     testImplementation("org.junit.vintage:junit-vintage-engine:5.5.1")

as dependency. I have to run the tests from the terminal tho. The plugin runs only spek test
