### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by 3flex** [JetBrains/spek#764]
Hi, I know this adds a burden to pushing new releases, but spek appears to be the only dependency for the detekt project that is not available on Maven Central. Any chance it could be published there?

Influential tweet (which links to a blog post that explains an issue that caused some concern last year): https://mobile.twitter.com/jakewharton/status/1073102730443526144

Thanks for your consideration!

**Comment by raniejade** [comment]
Definitely going to happen, I was supposed to do this ages ago but it fell of my radar. Just need to sign the artifacts then it should be ready to go.

**Comment by raniejade** [comment]
Starting the release process for `2.0.7` this week, hopefully everything should just work when I sync to central. :crossed_fingers:

**Comment by raniejade** [comment]
Bintray says the sync went okay but I'm still not seeing the `2.0.7` artifacts yet, keeping this open until it does.

**Comment by raniejade** [comment]
Still having issues with the sync, pushing it back to `2.0.8`

**Comment by raniejade** [comment]
Just an update, waiting for bintray to reply on my support ticket. Took a while since I needed to transfer the ownership of spekframework.org to myself - this makes it easier to get a namespace reserved in central.

**Comment by 3flex** [comment]
Thanks for your efforts!

**Comment by raniejade** [comment]
Finally done! https://search.maven.org/search?q=spekframework :tada: Though at the moment I have to click sync every release, I'll have to automate it at some point :)

**Comment by grossws** [comment]
@raniejade, could you please sync released versions to central? Currently only 2.0.9 is there.
