### ISSUE TITLE
includeEngines android studio plugin

### ISSUE THREAD

**Issue by bblackbelt** [JetBrains/spek#765]
Would it be possible to pass `includeEngines` as parameters to the runner? I am not sure my question makes sense. To give you some background, I did configure `includeEngines` to run `spek2` and `junit-vintage` tests. It works if I run it frome the terminal. If I run it from android studio with the spek plugin it runs only the spek tests.

**Comment by raniejade** [comment]
The IJ/AS plugins only support running spek tests, running vintage is out of scope. I'm not sure if the JUnit 5 support added by IJ includes running tests engines other than `jupiter` and `vintage`. If it does then there is a probability that you could use whatever the plugin provides to run spek tests as we provide a `TestEngine` implementation (`spek-runner-junit5`).
