### ISSUE TITLE
Adjust default timeout globally

### ISSUE THREAD

**Issue by svenjacobs** [JetBrains/spek#769]
As an enhancement to #692 I think Spek should offer a possibility to override/specify the default timeout **globally** for all tests. At the moment the timeout can only be specified per test suite or test.

I encounter random `TimeoutCancellationException` in various tests when my machine seems to be under heavy load. Increasing the timeout of a test usually fixes this. However I don't want to override the timeout in each of my hundreds of tests.

**Comment by raniejade** [comment]
Nice idea! For JVM the configuration can be passed via https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-config-params.

**Comment by plannigan** [comment]
This 10 second timeout surprised me when I needed to use the debugger to walk through a test case. Being able to alter/disable this behavior would make stepping through code much nicer.

**Comment by raniejade** [comment]
Scheduling this for the next release.

**Comment by schalkms** [comment]
Thanks for the quick update @raniejade.
Could you please share with us how one can configure this global timeout?

**Comment by svenjacobs** [comment]
Thanks for implementing this so quickly! Any plans when the next release is ready? :)

**Comment by raniejade** [comment]
@schalkms it can be set via the property `SPEK_TIMEOUT`. You can try it out with the latest dev builds but it has pretty big changes internally that might have issues (like #781 and #789)

@svenjacobs No hard deadlines yet but hopefully in two weeks time. Two main things I'd like to finish first before releasing are:

- Publish to maven central (sorting out domain ownership and reserving namespace in OSSH)
- Allow disabling timeouts (#792)
