### ISSUE TITLE
Inheritance hierarchy: Base class support in Spek

### ISSUE THREAD

**Issue by schalkms** [JetBrains/spek#777]
I have the following use case.
I implemented an abstract base class, which creates expensive objects before each test and disposes them after each test. To have this boilerplate code not spread through the code base, I created the following base class. Other `Spek` classes derive from this base class called `BaseSpek`.

How can I access the `object` variable in derived classes in order to call methods on this object? Is there maybe another way to accomplish my objective? Is this use case even supported by the Spek framework?

```Kotlin
abstract class BaseSpek(root: Root.() -> Unit) : Spek({

    // how can I access this variable in a class that derives from 'BaseSpek'
    var object: ExpensiveObject? = null
    
    beforeEachTest {
        object = createExpensiveObject()
    }
    
    afterEachTest {
        object.dispose() // dispose manually
    }
    
    root()
})
```

**Comment by raniejade** [comment]
Have you tried something like:

```kotlin
fun Root.setupExpensiveObject() {
   val expensiveObject by memoized(::createExpensiveObject, destructor = { it.dispose } )
}
```

Then in one of your test:

```kotlin
object Test: Spek({
   setupExpensiveObject()
   
   // fetch object, keyed by name.
   val expensiveObject by memoized()
})
```

**Comment by schalkms** [comment]
That was quick. Thanks for helping me out!
Do you think this is worth adding to the documentation, because in my opinion this pattern is missing?
I'd submit a PR then.

**Comment by raniejade** [comment]
Definitely, any help is appreciated! :)
