### ISSUE TITLE
Docs site appears to be out of date.

### ISSUE THREAD

**Issue by Zoltu** [JetBrains/spek#78]
I just updated to the latest version of spek `1.0.9` and now the `Spek` constructor wants a body.

**Comment by marcomorain** [comment]
This is tripping me up too.

**Comment by marcomorain** [comment]
Looks like this is the new syntax:

```Kotlin
class ContextGivenOnTest : Spek({
  given("a calculator") {
  }
}) 
```

**Comment by hhariri** [comment]
Yes. Will be getting it all updated and ready for release.
