### ISSUE TITLE
Delete CachingMode.GROUP

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#798]
Using `CachingMode.GROUP` in `2.0.9` is considered as a compilation error, drop it in the next release.

**Comment by robstoll** [comment]
What should be used instead? SCOPE?
And another question in a similar area, the LifecycleListener does not provide the methods beforeScope/afterScope: how I am supposed to know when a memoized value gets out of its cachingMode-scope? should I use `memoized(... descrutor)` for that purpose?

**Comment by raniejade** [comment]
> What should be used instead? SCOPE?

Use `CachingMode.EACH_GROUP`, it was poorly named.

> the LifecycleListener does not provide the methods beforeScope/afterScope

Use `beforeGroup/afterGroup`. From the top of my head, the following pairs have the same semantics:

- `CachingMode.SCOPE` -> `beforeGroup/afterGroup`
- `CachingMode.EACH_GROUP` (previously known as `CachingMode.GROUP`) -> `beforeEachGroup/afterEachGroup`
- `CachingMode.TEST` -> `beforeEachTest/afterEachTest`

> how I am supposed to know when a memoized value gets out of its cachingMode-scope? should I use memoized(... descrutor) for that purpose?

I'm not following, can you give an example?

**Comment by robstoll** [comment]
Ah OK. I won't bother you with my problem I guess I have to use the destructor anyway. Btw. There isn't a beforeGroup/afterGroup on the lifecyclelistener

**Comment by raniejade** [comment]
> Btw. There isn't a beforeGroup/afterGroup on the lifecyclelistener

Intentional, `LifecycleListener` is meant for notifying when a scope (group/test) is executed.
