### ISSUE TITLE
Add IDE inspection when a spek has no no-arg constructor

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#806]
See #801.

The plugin should recommend adding the `@Ignore` or mark it as abstract. annotation. Spek does not know how to instantiate a class that has a no-arg constructor (unless `@CreateWith` is specified), this can cause discovery failures preventing tests to be executed.

**Comment by schleifenkauz** [comment]
I could implement this

**Comment by schleifenkauz** [comment]
I have implemented this now. Do I need a permission to push the branch?

**Comment by raniejade** [comment]
Thanks for the interest! You don't have permission to push - the standard way of contributing is forking the repo, pushing the changes on the clone and then you can send in a pull request :).

**Comment by schleifenkauz** [comment]
#828
