### ISSUE TITLE
Confused about test styles

### ISSUE THREAD

**Issue by DanielSWolf** [JetBrains/spek#812]
I'm new to Spek and trying to find out which syntax to use. According to the documentation, there are two possible styles: [_Specification style_](https://www.spekframework.org/specification/) (`describe`, `it`) and [_Gherkin style_](https://www.spekframework.org/gherkin/) (`Feature`, `Scenario`, ...).

However, in the [Core Concepts documentation](https://www.spekframework.org/core-concepts/), tests are written in a third, otherwise undocumented style, using `group` and `test`.

Now I'm confused: Is that third style still valid and simply missing from the _Styles_ chapter? Or is it a documentation relic from Spek 1 and no longer supported?

If it's still supported: Are `group` and `test` simply aliases for `describe` and `it`, respectively? Can I mix them (`describe` -> `test`)?

**Comment by raniejade** [comment]
It’s the other way around, the different styles are just aliases to group/test. Please don’t use/mix them, treat group/test as an internal api. I used group/test in that section to show the difference of each scope.

**Comment by DanielSWolf** [comment]
I see. So `group`/`test` is the "default" style and the other two are just alternatives. Thank you for the explanation!

Maybe it might help others to mention this in the documentation.

**Comment by raniejade** [comment]
> So group/test is the "default" style and the other two are just alternatives

Please don't use them :) I'll eventually remove them in favor of making the `specification` and `gherkin` styles first class (instead of just aliases).

Closing this as answered.
