### ISSUE TITLE
Where can I find some good examples of Spek2 tests?

### ISSUE THREAD

**Issue by dhaksddj** [JetBrains/spek#827]
I checked the sample directory here but its just a simple test.

Any other projects making extensive use of Spek I can get ideas from?

**Comment by raniejade** [comment]
A few samples (in the integration-test module):
- https://github.com/spekframework/spek/blob/2.x/integration-test/src/commonTest/kotlin/org/spekframework/spek2/integration/SetSpec.kt
- https://github.com/spekframework/spek/blob/2.x/integration-test/src/commonTest/kotlin/org/spekframework/spek2/integration/SetFeature.kt
- https://github.com/spekframework/spek/tree/2.x/integration-test/src/jvmTest/kotlin/org/spekframework/spek2
