### ISSUE TITLE
Support IntelliJ IDEA 2019.3 

### ISSUE THREAD

**Issue by bdalenoord** [JetBrains/spek#829]
Issue #821 should add support for IntelliJ IDEA 2019.3, but as it is now publicly available, the plugin no longer works. When reviewing the change for that issue (https://github.com/spekframework/spek/pull/821/commits/48d34b26d2d7e242dfe5dc85da83c0295688cc00) it dawned upon me that only the Azure pipeline for testing that version was added, not for releasing it...

**Comment by bdalenoord** [comment]
I think the fix would be to add a `ij193` block on line https://github.com/spekframework/spek/blob/2.x/azure-pipelines.yml#L140.

**Comment by raniejade** [comment]
@bdalenoord you are correct, just the release step is missing. Would you like to send a PR? Otherwise, I'll have time in the weekend do it.

**Comment by robstoll** [comment]
Now the only thing missing is a release I guess or is the plugin waiting for approval from Intellij? Anyhow, I still have the `Incompatible with the current IntelliJ version`

**Comment by raniejade** [comment]
@robstoll so the merge will trigger a dev build which gets published to the dev channel (which is waiting for JB's approval). I need to do an actual _release_ (2.0.9) to get the plugin into the stable channel.
