### ISSUE TITLE
Spek executes code from different scenario

### ISSUE THREAD

**Issue by simonobusek** [JetBrains/spek#838]
Using Gherkin style of tests. Using plugin in Idea(2019.2) and running Spek with plugin(v. 2.0.9).

When I run Scenario B, some part of code defined in Scenario A is also executed. Anything written between Scenario and 1st step (Given, When, Then), respectively code out of scope of test steps is executed first. Im not sure if this is valid behaviour or should I avoid using any code in this place?  For example: I usually define properties used in whole scenario that are initialise in later steps. It is confusing during debug, if I run one specific scenario and as "side effect" code from different scenario is executed as well, causing issues. 

In example screenshot: Running scenario B, expected print message in log to be: E,B,F
But was actually: A,D,E,F,B

![Screenshot 2019-12-19 at 13 29 07](https://user-images.githubusercontent.com/15251514/71173671-9b402380-2263-11ea-90db-0bfcf3f47cc0.png)

**Comment by raniejade** [comment]
@simonobusek Sorry for the delayed reply! This is expected please read https://www.spekframework.org/core-concepts/
