### ISSUE TITLE
Support IntelliJ IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#844]
https://blog.jetbrains.com/idea/2020/01/intellij-idea-2020-1-eap/

**Comment by dsvensson** [comment]
any release soon? or is there some snapshot repo somewhere?

**Comment by raniejade** [comment]
@dsvensson a build is available in the dev channel https://plugins.jetbrains.com/plugin/10915-spek-framework/versions.
