### ISSUE TITLE
Add a "xtest" option to skip the test, similarly to "xit"

### ISSUE THREAD

**Issue by StragaSevera** [JetBrains/spek#845]
There is a useful way to skip a test using Specification stype - just add "x" before the test function and it will be disabled, like "xit" or "xcontext". However, I do not see the way to use this feature when using a default style, with "group" and "test. It would be great to have this!

**Comment by raniejade** [comment]
It's intentional, `group` and `test` should be treated as an internal (low level) API - it's not the *default style*.
