### ISSUE TITLE
Cannot set the SPEK_TIMEOUT property for IntelliJ Plugin

### ISSUE THREAD

**Issue by StragaSevera** [JetBrains/spek#846]
I want to disable timeouts, but for some reason I cannot get it working with the Spek plugin for IntelliJ.
My `build.gradle.kts` has: 
```
tasks {
    test {
        systemProperty("SPEK_TIMEOUT", 0)
        useJUnitPlatform {
            includeEngines("spek2")
        }
    }
}
```
, but it works only if I run the Gradle task for testing, not the IntelliJ plugin. How can I use this system property with the IntelliJ Plugin?

**Comment by raniejade** [comment]
It's a bit tedious in the plugin atm, you have to set it per run configuration via the `VM options` config.

![Screenshot from 2020-02-05 08-13-03](https://user-images.githubusercontent.com/1041919/73787461-7130c980-47ef-11ea-98e7-00113b84665c.png)

It would be better if we could set it globally via some settings in IJ.

**Comment by raniejade** [comment]
Closing in favor of #847. Also I'm disabling timeouts by default in #879.
