### ISSUE TITLE
Running tests from sample doesnt work

### ISSUE THREAD

**Issue by johanneskraem3r** [JetBrains/spek#854]
I'm trying to run the test of the sample by clicking the gutter icons ( like explained [in the docs](https://www.spekframework.org/running/) ), [see image](https://www.spekframework.org/images/gutter_icons.png), and it fails.

This is on Windows, on a newly cloned git repo, without any local changes.
Running the test talk works without any problem.

`

Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:createMockableJar, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources, :app:compileDebugSources] in project C:\repos\spek\samples\android

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:prepareLintJarForPublish UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:preDebugAndroidTestBuild SKIPPED
> Task :app:compileDebugAndroidTestAidl NO-SOURCE
> Task :app:createDebugCompatibleScreenManifests
> Task :app:mainApkListPersistenceDebug
> Task :app:processDebugManifest
> Task :app:processDebugAndroidTestManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.20}.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-core:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.20}' because of the following reason: debugRuntimeClasspath uses version 1.3.20
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-reflect:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.20}.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-core:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.20}' because of the following reason: debugRuntimeClasspath uses version 1.3.20

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.21.
     Required by:
         project :app > de.mannodermaus.junit5:android-test-core:1.0.0
         project :app > de.mannodermaus.junit5:android-test-runner:1.0.0
         project :app > de.mannodermaus.junit5:android-test-runner:1.0.0 > org.jetbrains.kotlin:kotlin-reflect:1.3.21
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-core:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.20}' because of the following reason: debugRuntimeClasspath uses version 1.3.20
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-reflect:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.20.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20
         project :app > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-core:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.20}' because of the following reason: debugRuntimeClasspath uses version 1.3.20
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-runner:1.0.0' --> 'org.jetbrains.kotlin:kotlin-reflect:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
           Dependency path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.20'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-stdlib:1.3.21
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'de.mannodermaus.junit5:android-test-core:1.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.20}' because of the following reason: debugRuntimeClasspath uses version 1.3.20

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
8 actionable tasks: 4 executed, 4 up-to-date`

**Comment by johanneskraem3r** [comment]
Changing the kotlin version up to 1.3.61 seems to fix it: 

(In from build.gradle ) : 

Change : 
    ext.kotlin_version = '1.3.20'
to: 
    ext.kotlin_version = '1.3.61'

**Comment by raniejade** [comment]
Nice find, thanks! I'll add this to my todo list.
