### ISSUE TITLE
Slow keyboard response on IDE after having a big Spek file

### ISSUE THREAD

**Issue by danielgomezrico** [JetBrains/spek#874]
# Dependencies
- spek_version: `2.1.0-alpha.0.14+a763c30` or `2.0.10`
- spek plugin: `2.0.10-Studio3.6`
- android studio `3.6.2`

# Description
When you have a big spek file (like 1000 lines) the IDE starts showing keyboard input *ultra slow*: 

**It happens even if you dont have the spek plugin enabled.**

![2020-04-07 21 30 44](https://user-images.githubusercontent.com/76348/78738805-5fb38d00-7918-11ea-912c-e96f491bf17a.gif)

# Sample Test
- Example repository: https://github.com/danielgomezrico/spek-slow-example
- Test: [UltraBigSlowSpec.kt](https://github.com/danielgomezrico/spek-slow-example/blob/master/app/src/test/kotlin/org/spekframework/speksample/UltraBigSlowSpec.kt).
and try to write some stub speks on it.

**Comment by danielgomezrico** [comment]
Looks like it is not related to spek but to android studio or intellij.

**Comment by neelkamath** [comment]
If someone seeing this issue still has this problem, it's because of the class constructor containing a large lambda. Simply [moving the lambda](https://youtrack.jetbrains.com/issue/KT-13474#focus=streamItem-27-1573280.0-0) outside the constructor solves the issue.
