### ISSUE TITLE
Handle expected exception

### ISSUE THREAD

**Issue by pilgr** [JetBrains/spek#89]
Is it possible to write tests where specific exception is expected, like using `@Test(expected = UnhandledException::class)` from JUnit ?
Thanks!

**Comment by artem-zinnatullin** [comment]
For now you definitely can use plain `try/catch` check inside of `it {}`

**Comment by raniejade** [comment]
If you use https://github.com/npryce/hamkrest you can do:

```kotlin
assertThat({throw ExampleException("testing")}, throws<ExampleException>())
// negation
assertThat({ /* do something */ }, !throws<Throwable>())
```

**Comment by mfulton26** [comment]
One of Spek's transitive dependencies is `kotlin-test` which has `assertFails` and `assertFailsWith`:

```kotlin
assertFailsWith<IllegalStateException> { 
    check(false)
}
```

See [kotlin/kotlin/test/TestAssertions.kt](https://github.com/JetBrains/kotlin/blob/d2bf4cbfa016fc1e27c9847fbf8f6e38400f3ce8/libraries/kotlin.test/shared/src/main/kotlin/kotlin/test/TestAssertions.kt) and [kotlin.jvm/kotlin/test/TestAssertionsJVM.kt](https://github.com/JetBrains/kotlin/blob/d2bf4cbfa016fc1e27c9847fbf8f6e38400f3ce8/libraries/kotlin.test/shared/src/main/kotlin.jvm/kotlin/test/TestAssertionsJVM.kt).
