### ISSUE TITLE
eclipse plugin

### ISSUE THREAD

**Issue by mfulton26** [JetBrains/spek#92]
Will an Eclipse plugin be created for Spek? I personally prefer IDEA but I do have coworkers who use Eclipse so to migrate to Spek without Eclipse support may be problematic. Thanks.

**Comment by artem-zinnatullin** [comment]
>may be problematic

Maybe it works? Spek uses JUnit reporting API, Eclipse should handle it I guess…

**Comment by mfulton26** [comment]
I just realized that as I was looking at the `Spek` class. Yes, I believe it should work out of the box. Thank you.

**Comment by piacenti** [comment]
@mfulton26 Were you able to get eclipse to recognize spek tests as tests to be run from the IDE itself?
