### ISSUE TITLE
Add option to disable "Spek discovery completed in X ms" (or just remove it entirely)

### ISSUE THREAD

**Issue by charleskorn** [JetBrains/spek#922]
After upgrading to 2.0.13, I'm getting messages like these in Gradle's output when running tests:

```
> Task :test

Gradle Test Executor 26 STANDARD_OUT
    Spek discovery completed in 360 ms
```

These aren't interesting to me and are just noise, and there doesn't appear to be any way to turn them off. 

The source appears to be: https://github.com/spekframework/spek/blob/2.0.13/spek-runtime/src/commonMain/kotlin/org/spekframework/spek2/runtime/SpekRuntime.kt#L62

**Comment by raniejade** [comment]
I think I'll add in an option to disable the log line - it's useful for debugging slowness in the discovery phase.
