### ISSUE TITLE
Move artifact publishing directly to Maven Central

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#949]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by robstoll** [comment]
It seems like 2.0.10, 2.0.11 and  2.012 have not been published to maven central. For instance:
https://repo.maven.apache.org/maven2/org/spekframework/spek2/spek-dsl-js/

**Comment by raniejade** [comment]
Yeah, forgot to click the "Sync to Maven Central" button. I'll do it now, the need for manually doing it will go away after this ticket.

**Comment by raniejade** [comment]
@robstoll everything should be synced now.

**Comment by robstoll** [comment]
Thanks, I can confirm that it works

**Comment by raniejade** [comment]
`2.0.16` is out which publishes directly to Maven Central.
