### ISSUE TITLE
Version for IntelliJ IDEA 2021.1

### ISSUE THREAD

**Issue by dnowak-wrldrmt** [JetBrains/spek#954]
Hi,

Could you, please, release version for IDEA 2021.1?

BR,
Darek

**Comment by raniejade** [comment]
Note to myself, latest build versions are here: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.1+latest+builds

**Comment by 3flex** [comment]
2021.1 is released, so it would be great to see a new version released with support :)

**Comment by raniejade** [comment]
Yep, just need to trigger a release - hopefully I get by to it this weekend.

**Comment by raniejade** [comment]
`2.0.16` is out, IJ plugin should be available by now.

**Comment by dnowak-wrldrmt** [comment]
Hi @raniejade, 2.0.16 is released but there is no variant for IDEA 2021.1. 

At least it is not visible on the plugin's page https://plugins.jetbrains.com/plugin/10915-spek-framework/versions and my IDEA 2021.1 did not find a matching plugin version, too.

**Comment by raniejade** [comment]
@dnowak-wrldrmt There was a mishap on our GH workflow - I'll manually publish the plugin, you should see it in a couple of hours.
