### ISSUE TITLE
Incorrect example in a doc section "core-concepts"

### ISSUE THREAD

**Issue by ultraon** [JetBrains/spek#957]
Hello, I've found that in a doc section "core-concepts" there is an incorrect example with Kotlin `lateinit var added: Boolean`, link is https://www.spekframework.org/core-concepts/ . Kotlin doesn't support `lateinit` feature for simple types. To fix it you just need to do the following: `var added = false`

**Comment by raniejade** [comment]
Resolved at 14af51d
