### ISSUE TITLE
Plugin build for IDEA 2021.1 failed to deploy

### ISSUE THREAD

**Issue by xian** [JetBrains/spek#963]
See https://github.com/spekframework/spek/runs/2263755561

Here's what's available in the JetBrains plugin marketplace:
![image](https://user-images.githubusercontent.com/40298/114755299-553b8880-9d0e-11eb-86a3-bc22a8ad05fb.png)

**Comment by raniejade** [comment]
Looks like there is a misconfiguration in one of our workflows. I'll probably upload the version manually.

**Comment by raniejade** [comment]
@xian upload done, can you check?

**Comment by xian** [comment]
Works, thanks @raniejade!
